/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _scr_tail: typeof import('./src/components/schemes/_scr_tail.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ContentDialog: typeof import('./src/components/ui/ContentDialog.vue')['default']
    DateRangePickerField: typeof import('./src/components/ui/DateRangePickerField.vue')['default']
    DateTimePickerModal: typeof import('./src/components/ui/DateTimePickerModal.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LobbyTabBar: typeof import('./src/components/lobby/LobbyTabBar.vue')['default']
    OptionPickerModal: typeof import('./src/components/ui/OptionPickerModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemeContentReadonlyPanel: typeof import('./src/components/schemes/SchemeContentReadonlyPanel.vue')['default']
    SchemeGroupInputPanel: typeof import('./src/components/schemes/SchemeGroupInputPanel.vue')['default']
    SchemeGroupPickPanel: typeof import('./src/components/schemes/SchemeGroupPickPanel.vue')['default']
    SchemeRenxuanDanshiPanel: typeof import('./src/components/schemes/SchemeRenxuanDanshiPanel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
