// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_audit.sql

package sqlcdb

import (
	"context"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :one
INSERT INTO admin_audit_logs (id, actor, action, ip)
VALUES (
    'AUD' || LPAD(nextval('admin_audit_log_seq')::text, 5, '0'),
    $1, $2, $3
)
RETURNING id, actor, action, ip, created_at
`

type InsertAdminAuditLogParams struct {
	Actor  string `json:"actor"`
	Action string `json:"action"`
	Ip     string `json:"ip"`
}

func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAdminAuditLog, arg.Actor, arg.Action, arg.Ip)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.Action,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, actor, action, ip, created_at
FROM admin_audit_logs
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListAdminAuditLogs(ctx context.Context, rowLimit int32) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLogs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
