// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_orders.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminBetOrders = `-- name: CountAdminBetOrders :one
SELECT COUNT(*)::bigint
FROM bet_orders b
INNER JOIN members m ON m.id = b.member_id
LEFT JOIN cloud_bet_records c ON c.bet_order_no = b.order_no
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR b.issue_no ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR m.account ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR c.scheme_name ILIKE '%' || $3::text || '%'
)
AND (
    $4::text IS NULL
    OR $4::text = ''
    OR b.lottery_code = $4::text
)
`

type CountAdminBetOrdersParams struct {
	IssueNo       pgtype.Text `json:"issue_no"`
	MemberAccount pgtype.Text `json:"member_account"`
	SchemeName    pgtype.Text `json:"scheme_name"`
	LotteryCode   pgtype.Text `json:"lottery_code"`
}

func (q *Queries) CountAdminBetOrders(ctx context.Context, arg CountAdminBetOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminBetOrders,
		arg.IssueNo,
		arg.MemberAccount,
		arg.SchemeName,
		arg.LotteryCode,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAdminChaseOrders = `-- name: CountAdminChaseOrders :one
SELECT COUNT(*)::bigint
FROM chase_orders c
INNER JOIN members m ON m.id = c.member_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR c.chase_no ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR m.account ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR c.status = $3::text
)
AND (
    $4::text IS NULL
    OR $4::text = ''
    OR c.lottery_code = $4::text
)
`

type CountAdminChaseOrdersParams struct {
	ChaseNo       pgtype.Text `json:"chase_no"`
	MemberAccount pgtype.Text `json:"member_account"`
	Status        pgtype.Text `json:"status"`
	LotteryCode   pgtype.Text `json:"lottery_code"`
}

func (q *Queries) CountAdminChaseOrders(ctx context.Context, arg CountAdminChaseOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminChaseOrders,
		arg.ChaseNo,
		arg.MemberAccount,
		arg.Status,
		arg.LotteryCode,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAdminLedgerEntries = `-- name: CountAdminLedgerEntries :one
SELECT COUNT(*)::bigint
FROM wallet_ledger l
INNER JOIN members m ON m.id = l.member_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR l.ledger_no ILIKE '%' || $1::text || '%'
    OR m.id::text ILIKE '%' || $1::text || '%'
    OR m.account ILIKE '%' || $1::text || '%'
    OR m.display_name ILIKE '%' || $1::text || '%'
    OR COALESCE(l.order_ref, '') ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountAdminLedgerEntries(ctx context.Context, keyword pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminLedgerEntries, keyword)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAdminBetOrders = `-- name: ListAdminBetOrders :many
SELECT
    COALESCE(
        NULLIF(TRIM(b.third_party_bet_id), ''),
        NULLIF(TRIM(c.third_party_bet_id), ''),
        ''
    ) AS third_party_bet_id,
    b.issue_no,
    m.account,
    b.lottery_name,
    COALESCE(c.scheme_name, '') AS scheme_name,
    b.amount::float8 AS amount,
    CASE
        WHEN b.status = 'win' THEN (b.amount + b.pnl)::float8
        ELSE 0
    END AS payout_amount,
    b.status,
    b.placed_at
FROM bet_orders b
INNER JOIN members m ON m.id = b.member_id
LEFT JOIN cloud_bet_records c ON c.bet_order_no = b.order_no
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR b.issue_no ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR m.account ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR c.scheme_name ILIKE '%' || $3::text || '%'
)
AND (
    $4::text IS NULL
    OR $4::text = ''
    OR b.lottery_code = $4::text
)
ORDER BY b.placed_at DESC, b.id DESC
LIMIT $6 OFFSET $5
`

type ListAdminBetOrdersParams struct {
	IssueNo       pgtype.Text `json:"issue_no"`
	MemberAccount pgtype.Text `json:"member_account"`
	SchemeName    pgtype.Text `json:"scheme_name"`
	LotteryCode   pgtype.Text `json:"lottery_code"`
	RowOffset     int32       `json:"row_offset"`
	RowLimit      int32       `json:"row_limit"`
}

type ListAdminBetOrdersRow struct {
	ThirdPartyBetID string             `json:"third_party_bet_id"`
	IssueNo         string             `json:"issue_no"`
	Account      string             `json:"account"`
	LotteryName  string             `json:"lottery_name"`
	SchemeName   string             `json:"scheme_name"`
	Amount       float64            `json:"amount"`
	PayoutAmount float64            `json:"payout_amount"`
	Status       string             `json:"status"`
	PlacedAt     pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListAdminBetOrders(ctx context.Context, arg ListAdminBetOrdersParams) ([]ListAdminBetOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminBetOrders,
		arg.IssueNo,
		arg.MemberAccount,
		arg.SchemeName,
		arg.LotteryCode,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminBetOrdersRow{}
	for rows.Next() {
		var i ListAdminBetOrdersRow
		if err := rows.Scan(
			&i.ThirdPartyBetID,
			&i.IssueNo,
			&i.Account,
			&i.LotteryName,
			&i.SchemeName,
			&i.Amount,
			&i.PayoutAmount,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminChaseOrders = `-- name: ListAdminChaseOrders :many
SELECT
    c.chase_no,
    m.account,
    c.lottery_name,
    c.total_issues,
    c.done_issues,
    c.amount::float8 AS amount,
    c.status,
    c.started_at
FROM chase_orders c
INNER JOIN members m ON m.id = c.member_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR c.chase_no ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR m.account ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR c.status = $3::text
)
AND (
    $4::text IS NULL
    OR $4::text = ''
    OR c.lottery_code = $4::text
)
ORDER BY c.started_at DESC, c.id DESC
LIMIT $6 OFFSET $5
`

type ListAdminChaseOrdersParams struct {
	ChaseNo       pgtype.Text `json:"chase_no"`
	MemberAccount pgtype.Text `json:"member_account"`
	Status        pgtype.Text `json:"status"`
	LotteryCode   pgtype.Text `json:"lottery_code"`
	RowOffset     int32       `json:"row_offset"`
	RowLimit      int32       `json:"row_limit"`
}

type ListAdminChaseOrdersRow struct {
	ChaseNo     string             `json:"chase_no"`
	Account     string             `json:"account"`
	LotteryName string             `json:"lottery_name"`
	TotalIssues int32              `json:"total_issues"`
	DoneIssues  int32              `json:"done_issues"`
	Amount      float64            `json:"amount"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ListAdminChaseOrders(ctx context.Context, arg ListAdminChaseOrdersParams) ([]ListAdminChaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAdminChaseOrders,
		arg.ChaseNo,
		arg.MemberAccount,
		arg.Status,
		arg.LotteryCode,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminChaseOrdersRow{}
	for rows.Next() {
		var i ListAdminChaseOrdersRow
		if err := rows.Scan(
			&i.ChaseNo,
			&i.Account,
			&i.LotteryName,
			&i.TotalIssues,
			&i.DoneIssues,
			&i.Amount,
			&i.Status,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminLedgerEntries = `-- name: ListAdminLedgerEntries :many
SELECT
    l.ledger_no,
    m.display_name,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.created_at
FROM wallet_ledger l
INNER JOIN members m ON m.id = l.member_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR l.ledger_no ILIKE '%' || $1::text || '%'
    OR m.id::text ILIKE '%' || $1::text || '%'
    OR m.account ILIKE '%' || $1::text || '%'
    OR m.display_name ILIKE '%' || $1::text || '%'
    OR COALESCE(l.order_ref, '') ILIKE '%' || $1::text || '%'
)
ORDER BY l.created_at DESC, l.id DESC
LIMIT $3 OFFSET $2
`

type ListAdminLedgerEntriesParams struct {
	Keyword   pgtype.Text `json:"keyword"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

type ListAdminLedgerEntriesRow struct {
	LedgerNo    string             `json:"ledger_no"`
	DisplayName string             `json:"display_name"`
	TxnType     string             `json:"txn_type"`
	DeltaAmount float64            `json:"delta_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdminLedgerEntries(ctx context.Context, arg ListAdminLedgerEntriesParams) ([]ListAdminLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminLedgerEntries, arg.Keyword, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminLedgerEntriesRow{}
	for rows.Next() {
		var i ListAdminLedgerEntriesRow
		if err := rows.Scan(
			&i.LedgerNo,
			&i.DisplayName,
			&i.TxnType,
			&i.DeltaAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
