// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_schemes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSchemeShareSnapshot = `-- name: DeleteSchemeShareSnapshot :execrows
DELETE FROM scheme_share_snapshots
WHERE id = $1
`

func (q *Queries) DeleteSchemeShareSnapshot(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchemeShareSnapshot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchemeInstanceByID = `-- name: GetSchemeInstanceByID :one
SELECT
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    created_at, updated_at
FROM scheme_instances
WHERE id = $1
`

type GetSchemeInstanceByIDRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchemeInstanceByID(ctx context.Context, id string) (GetSchemeInstanceByIDRow, error) {
	row := q.db.QueryRow(ctx, getSchemeInstanceByID, id)
	var i GetSchemeInstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminSchemeInstances = `-- name: ListAdminSchemeInstances :many
SELECT
    i.id,
    i.definition_id,
    m.id AS member_id,
    m.account,
    i.kind,
    i.scheme_name,
    i.lottery_code,
    i.lottery_label,
    i.status,
    i.status_reason,
    i.sim_bet,
    COALESCE(d.config->>'runTypeId', '') AS run_type,
    COALESCE(NULLIF(d.config->>'playTypeId', ''), NULLIF(d.config->>'typeId', ''), '') AS play_type_id,
    COALESCE(pt.label, '') AS play_type_label,
    i.created_at,
    i.updated_at
FROM scheme_instances i
INNER JOIN members m ON m.id = i.member_id
LEFT JOIN scheme_definitions d ON d.id = i.definition_id
LEFT JOIN lottery_catalog lc ON lc.code = i.lottery_code
LEFT JOIN play_types pt ON pt.template_code = COALESCE(NULLIF(d.config->>'playTemplate', ''), lc.play_template)
    AND pt.type_id = COALESCE(NULLIF(d.config->>'playTypeId', ''), NULLIF(d.config->>'typeId', ''))
    AND COALESCE(NULLIF(d.config->>'playTypeId', ''), NULLIF(d.config->>'typeId', '')) <> ''
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR (
        COALESCE(NULLIF($2::text, ''), 'account') = 'account'
        AND m.account ILIKE '%' || $1::text || '%'
    )
    OR (
        $2::text = 'schemeName'
        AND i.scheme_name ILIKE '%' || $1::text || '%'
    )
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR i.kind = $3::text
)
AND (
    $4::text IS NULL
    OR $4::text = ''
    OR i.status = $4::text
)
AND (
    $5::boolean IS NULL
    OR i.sim_bet = $5::boolean
)
AND (
    $6::text IS NULL
    OR $6::text = ''
    OR i.lottery_code = $6::text
)
ORDER BY i.updated_at DESC
LIMIT $7
`

type ListAdminSchemeInstancesParams struct {
	Keyword     pgtype.Text `json:"keyword"`
	SearchField pgtype.Text `json:"search_field"`
	Kind        pgtype.Text `json:"kind"`
	Status      pgtype.Text `json:"status"`
	SimBet      pgtype.Bool `json:"sim_bet"`
	LotteryCode pgtype.Text `json:"lottery_code"`
	RowLimit    int32       `json:"row_limit"`
}

type ListAdminSchemeInstancesRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Account      string             `json:"account"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	SimBet       bool               `json:"sim_bet"`
	RunType       interface{}        `json:"run_type"`
	PlayTypeID    interface{}        `json:"play_type_id"`
	PlayTypeLabel interface{}        `json:"play_type_label"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminSchemeInstances(ctx context.Context, arg ListAdminSchemeInstancesParams) ([]ListAdminSchemeInstancesRow, error) {
	rows, err := q.db.Query(ctx, listAdminSchemeInstances,
		arg.Keyword,
		arg.SearchField,
		arg.Kind,
		arg.Status,
		arg.SimBet,
		arg.LotteryCode,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSchemeInstancesRow{}
	for rows.Next() {
		var i ListAdminSchemeInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Account,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.SimBet,
			&i.RunType,
			&i.PlayTypeID,
			&i.PlayTypeLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSchemeShareSnapshots = `-- name: ListAdminSchemeShareSnapshots :many
SELECT id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config, created_at, updated_at
FROM scheme_share_snapshots
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR (
        COALESCE(NULLIF($2::text, ''), 'schemeName') = 'schemeName'
        AND scheme_name ILIKE '%' || $1::text || '%'
    )
    OR (
        $2::text = 'snapshotId'
        AND id ILIKE '%' || $1::text || '%'
    )
)
AND (
    $3::text IS NULL
    OR $3::text = ''
    OR lottery_code = $3::text
)
ORDER BY updated_at DESC
LIMIT $4
`

type ListAdminSchemeShareSnapshotsParams struct {
	Keyword     pgtype.Text `json:"keyword"`
	SearchField pgtype.Text `json:"search_field"`
	LotteryCode pgtype.Text `json:"lottery_code"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) ListAdminSchemeShareSnapshots(ctx context.Context, arg ListAdminSchemeShareSnapshotsParams) ([]SchemeShareSnapshot, error) {
	rows, err := q.db.Query(ctx, listAdminSchemeShareSnapshots, arg.Keyword, arg.SearchField, arg.LotteryCode, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemeShareSnapshot{}
	for rows.Next() {
		var i SchemeShareSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.PlayMethod,
			&i.FundYuan,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchemeInstanceStatusByAdmin = `-- name: UpdateSchemeInstanceStatusByAdmin :one
UPDATE scheme_instances
SET status = $2,
    status_reason = CASE WHEN $2 = 'paused' THEN 'manual' WHEN $2 = 'soft_stopped' THEN '' ELSE status_reason END,
    updated_at = now()
WHERE id = $1
RETURNING
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    created_at, updated_at
`

type UpdateSchemeInstanceStatusByAdminParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

type UpdateSchemeInstanceStatusByAdminRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatusByAdmin(ctx context.Context, arg UpdateSchemeInstanceStatusByAdminParams) (UpdateSchemeInstanceStatusByAdminRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatusByAdmin, arg.ID, arg.Status)
	var i UpdateSchemeInstanceStatusByAdminRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeShareSnapshotAdmin = `-- name: UpdateSchemeShareSnapshotAdmin :one
UPDATE scheme_share_snapshots
SET
    scheme_name = $2,
    lottery_code = $3,
    lottery_label = $4,
    play_method = $5,
    fund_yuan = $6,
    config = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config, created_at, updated_at
`

type UpdateSchemeShareSnapshotAdminParams struct {
	ID           string         `json:"id"`
	SchemeName   string         `json:"scheme_name"`
	LotteryCode  string         `json:"lottery_code"`
	LotteryLabel string         `json:"lottery_label"`
	PlayMethod   string         `json:"play_method"`
	FundYuan     pgtype.Numeric `json:"fund_yuan"`
	Config       []byte         `json:"config"`
}

func (q *Queries) UpdateSchemeShareSnapshotAdmin(ctx context.Context, arg UpdateSchemeShareSnapshotAdminParams) (SchemeShareSnapshot, error) {
	row := q.db.QueryRow(ctx, updateSchemeShareSnapshotAdmin,
		arg.ID,
		arg.SchemeName,
		arg.LotteryCode,
		arg.LotteryLabel,
		arg.PlayMethod,
		arg.FundYuan,
		arg.Config,
	)
	var i SchemeShareSnapshot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.PlayMethod,
		&i.FundYuan,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
