// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (account, password_hash, display_name, role_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account, display_name, role_id, status, last_login_at, created_at, updated_at
`

type CreateAdminUserParams struct {
	Account      string `json:"account"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	RoleID       string `json:"role_id"`
	Status       string `json:"status"`
}

type CreateAdminUserRow struct {
	ID          int64              `json:"id"`
	Account     string             `json:"account"`
	DisplayName string             `json:"display_name"`
	RoleID      string             `json:"role_id"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Account,
		arg.PasswordHash,
		arg.DisplayName,
		arg.RoleID,
		arg.Status,
	)
	var i CreateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.RoleID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :execrows
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT
    u.id,
    u.account,
    u.display_name,
    u.role_id,
    r.name AS role_name,
    u.status,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM admin_users u
JOIN admin_roles r ON r.id = u.role_id
WHERE u.id = $1
`

type GetAdminUserByIDRow struct {
	ID          int64              `json:"id"`
	Account     string             `json:"account"`
	DisplayName string             `json:"display_name"`
	RoleID      string             `json:"role_id"`
	RoleName    string             `json:"role_name"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAdminUserByID(ctx context.Context, id int64) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.RoleID,
		&i.RoleName,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUserForLogin = `-- name: GetAdminUserForLogin :one
SELECT id, account, password_hash, display_name, role_id, status
FROM admin_users
WHERE account = $1
`

type GetAdminUserForLoginRow struct {
	ID           int64  `json:"id"`
	Account      string `json:"account"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	RoleID       string `json:"role_id"`
	Status       string `json:"status"`
}

func (q *Queries) GetAdminUserForLogin(ctx context.Context, account string) (GetAdminUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getAdminUserForLogin, account)
	var i GetAdminUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.PasswordHash,
		&i.DisplayName,
		&i.RoleID,
		&i.Status,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
    u.id,
    u.account,
    u.display_name,
    u.role_id,
    r.name AS role_name,
    u.status,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM admin_users u
JOIN admin_roles r ON r.id = u.role_id
ORDER BY u.id ASC
`

type ListAdminUsersRow struct {
	ID          int64              `json:"id"`
	Account     string             `json:"account"`
	DisplayName string             `json:"display_name"`
	RoleID      string             `json:"role_id"`
	RoleName    string             `json:"role_name"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.DisplayName,
			&i.RoleID,
			&i.RoleName,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAdminLastLogin = `-- name: TouchAdminLastLogin :exec
UPDATE admin_users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchAdminLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAdminLastLogin, id)
	return err
}

const updateAdminUser = `-- name: UpdateAdminUser :one
UPDATE admin_users
SET
    display_name = $2,
    role_id = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, account, display_name, role_id, status, last_login_at, created_at, updated_at
`

type UpdateAdminUserParams struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	RoleID      string `json:"role_id"`
	Status      string `json:"status"`
}

type UpdateAdminUserRow struct {
	ID          int64              `json:"id"`
	Account     string             `json:"account"`
	DisplayName string             `json:"display_name"`
	RoleID      string             `json:"role_id"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) (UpdateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, updateAdminUser,
		arg.ID,
		arg.DisplayName,
		arg.RoleID,
		arg.Status,
	)
	var i UpdateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.RoleID,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminUserPassword = `-- name: UpdateAdminUserPassword :exec
UPDATE admin_users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateAdminUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateAdminUserPassword(ctx context.Context, arg UpdateAdminUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminUserPassword, arg.ID, arg.PasswordHash)
	return err
}
