// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_roles.sql

package sqlcdb

import (
	"context"
)

const deleteAdminRole = `-- name: DeleteAdminRole :execrows
DELETE FROM admin_roles WHERE id = $1
`

func (q *Queries) DeleteAdminRole(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAdminRoles = `-- name: ListAdminRoles :many
SELECT id, name, menu_paths, created_at, updated_at
FROM admin_roles
ORDER BY id ASC
`

func (q *Queries) ListAdminRoles(ctx context.Context) ([]AdminRole, error) {
	rows, err := q.db.Query(ctx, listAdminRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRole{}
	for rows.Next() {
		var i AdminRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MenuPaths,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdminRole = `-- name: UpsertAdminRole :one
INSERT INTO admin_roles (id, name, menu_paths, created_at, updated_at)
VALUES ($1, $2, $3::jsonb, now(), now())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    menu_paths = EXCLUDED.menu_paths,
    updated_at = now()
RETURNING id, name, menu_paths, created_at, updated_at
`

type UpsertAdminRoleParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Column3 []byte `json:"column_3"`
}

func (q *Queries) UpsertAdminRole(ctx context.Context, arg UpsertAdminRoleParams) (AdminRole, error) {
	row := q.db.QueryRow(ctx, upsertAdminRole, arg.ID, arg.Name, arg.Column3)
	var i AdminRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MenuPaths,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
