// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin_reports.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminLotteryStatByLottery = `-- name: AdminLotteryStatByLottery :many
SELECT
    b.lottery_name,
    COUNT(*)::bigint AS bet_count,
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS effective_bet,
    COALESCE(SUM(b.pnl) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS member_pnl
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
GROUP BY b.lottery_code, b.lottery_name
ORDER BY effective_bet DESC
`

type AdminLotteryStatByLotteryParams struct {
	PlacedAt   pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2 pgtype.Timestamptz `json:"placed_at_2"`
}

type AdminLotteryStatByLotteryRow struct {
	LotteryName  string  `json:"lottery_name"`
	BetCount     int64   `json:"bet_count"`
	EffectiveBet float64 `json:"effective_bet"`
	MemberPnl    float64 `json:"member_pnl"`
}

func (q *Queries) AdminLotteryStatByLottery(ctx context.Context, arg AdminLotteryStatByLotteryParams) ([]AdminLotteryStatByLotteryRow, error) {
	rows, err := q.db.Query(ctx, adminLotteryStatByLottery, arg.PlacedAt, arg.PlacedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLotteryStatByLotteryRow{}
	for rows.Next() {
		var i AdminLotteryStatByLotteryRow
		if err := rows.Scan(
			&i.LotteryName,
			&i.BetCount,
			&i.EffectiveBet,
			&i.MemberPnl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLotteryStatSummary = `-- name: AdminLotteryStatSummary :one
SELECT
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS effective_bet,
    COALESCE(SUM(b.amount + b.pnl) FILTER (WHERE b.status = 'win'), 0)::float8 AS payout
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
`

type AdminLotteryStatSummaryParams struct {
	PlacedAt   pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2 pgtype.Timestamptz `json:"placed_at_2"`
}

type AdminLotteryStatSummaryRow struct {
	EffectiveBet float64 `json:"effective_bet"`
	Payout       float64 `json:"payout"`
}

func (q *Queries) AdminLotteryStatSummary(ctx context.Context, arg AdminLotteryStatSummaryParams) (AdminLotteryStatSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminLotteryStatSummary, arg.PlacedAt, arg.PlacedAt_2)
	var i AdminLotteryStatSummaryRow
	err := row.Scan(&i.EffectiveBet, &i.Payout)
	return i, err
}

const adminDailyLotteryReport = `-- name: AdminDailyLotteryReport :many
SELECT
    (b.placed_at AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    b.lottery_code,
    b.lottery_name,
    COUNT(*)::bigint AS bet_count,
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS valid_bet,
    COALESCE(-SUM(b.pnl) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS platform_pnl
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
  AND ($3::text = '' OR b.lottery_code = $3)
GROUP BY stat_date, b.lottery_code, b.lottery_name
ORDER BY stat_date DESC, valid_bet DESC
`

type AdminDailyLotteryReportParams struct {
	PlacedAt    pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2  pgtype.Timestamptz `json:"placed_at_2"`
	LotteryCode string             `json:"lottery_code"`
}

type AdminDailyLotteryReportRow struct {
	StatDate    pgtype.Date `json:"stat_date"`
	LotteryCode string      `json:"lottery_code"`
	LotteryName string      `json:"lottery_name"`
	BetCount    int64       `json:"bet_count"`
	ValidBet    float64     `json:"valid_bet"`
	PlatformPnl float64     `json:"platform_pnl"`
}

func (q *Queries) AdminDailyLotteryReport(ctx context.Context, arg AdminDailyLotteryReportParams) ([]AdminDailyLotteryReportRow, error) {
	rows, err := q.db.Query(ctx, adminDailyLotteryReport, arg.PlacedAt, arg.PlacedAt_2, arg.LotteryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminDailyLotteryReportRow{}
	for rows.Next() {
		var i AdminDailyLotteryReportRow
		if err := rows.Scan(
			&i.StatDate,
			&i.LotteryCode,
			&i.LotteryName,
			&i.BetCount,
			&i.ValidBet,
			&i.PlatformPnl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminDailyLotterySummary = `-- name: AdminDailyLotterySummary :one
SELECT
    COUNT(*)::bigint AS bet_count,
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS valid_bet,
    COALESCE(-SUM(b.pnl) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS platform_pnl
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
  AND ($3::text = '' OR b.lottery_code = $3)
`

type AdminDailyLotterySummaryParams struct {
	PlacedAt    pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2  pgtype.Timestamptz `json:"placed_at_2"`
	LotteryCode string             `json:"lottery_code"`
}

type AdminDailyLotterySummaryRow struct {
	BetCount    int64   `json:"bet_count"`
	ValidBet    float64 `json:"valid_bet"`
	PlatformPnl float64 `json:"platform_pnl"`
}

func (q *Queries) AdminDailyLotterySummary(ctx context.Context, arg AdminDailyLotterySummaryParams) (AdminDailyLotterySummaryRow, error) {
	row := q.db.QueryRow(ctx, adminDailyLotterySummary, arg.PlacedAt, arg.PlacedAt_2, arg.LotteryCode)
	var i AdminDailyLotterySummaryRow
	err := row.Scan(&i.BetCount, &i.ValidBet, &i.PlatformPnl)
	return i, err
}

const adminPnlReportDaily = `-- name: AdminPnlReportDaily :many
SELECT
    (b.placed_at AT TIME ZONE 'Asia/Shanghai')::date AS stat_date,
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS valid_bet,
    COALESCE(-SUM(b.pnl) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS platform_pnl
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
GROUP BY stat_date
ORDER BY stat_date DESC
`

type AdminPnlReportDailyParams struct {
	PlacedAt   pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2 pgtype.Timestamptz `json:"placed_at_2"`
}

type AdminPnlReportDailyRow struct {
	StatDate    pgtype.Date `json:"stat_date"`
	ValidBet    float64     `json:"valid_bet"`
	PlatformPnl float64     `json:"platform_pnl"`
}

func (q *Queries) AdminPnlReportDaily(ctx context.Context, arg AdminPnlReportDailyParams) ([]AdminPnlReportDailyRow, error) {
	rows, err := q.db.Query(ctx, adminPnlReportDaily, arg.PlacedAt, arg.PlacedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPnlReportDailyRow{}
	for rows.Next() {
		var i AdminPnlReportDailyRow
		if err := rows.Scan(&i.StatDate, &i.ValidBet, &i.PlatformPnl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPnlReportSummary = `-- name: AdminPnlReportSummary :one
SELECT
    COALESCE(-SUM(b.pnl) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS platform_pnl,
    COALESCE(SUM(b.amount) FILTER (WHERE b.status IN ('win', 'lose')), 0)::float8 AS valid_bet
FROM bet_orders b
WHERE b.placed_at >= $1
  AND b.placed_at < $2
`

type AdminPnlReportSummaryParams struct {
	PlacedAt   pgtype.Timestamptz `json:"placed_at"`
	PlacedAt_2 pgtype.Timestamptz `json:"placed_at_2"`
}

type AdminPnlReportSummaryRow struct {
	PlatformPnl float64 `json:"platform_pnl"`
	ValidBet    float64 `json:"valid_bet"`
}

func (q *Queries) AdminPnlReportSummary(ctx context.Context, arg AdminPnlReportSummaryParams) (AdminPnlReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminPnlReportSummary, arg.PlacedAt, arg.PlacedAt_2)
	var i AdminPnlReportSummaryRow
	err := row.Scan(&i.PlatformPnl, &i.ValidBet)
	return i, err
}
