// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bet_orders.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBetOrderCursorAnchor = `-- name: GetBetOrderCursorAnchor :one
SELECT b.placed_at, b.id
FROM bet_orders b
WHERE b.member_id = $1
  AND b.order_no = $2
`

type GetBetOrderCursorAnchorParams struct {
	MemberID int64  `json:"member_id"`
	OrderNo  string `json:"order_no"`
}

type GetBetOrderCursorAnchorRow struct {
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
	ID       int64              `json:"id"`
}

func (q *Queries) GetBetOrderCursorAnchor(ctx context.Context, arg GetBetOrderCursorAnchorParams) (GetBetOrderCursorAnchorRow, error) {
	row := q.db.QueryRow(ctx, getBetOrderCursorAnchor, arg.MemberID, arg.OrderNo)
	var i GetBetOrderCursorAnchorRow
	err := row.Scan(&i.PlacedAt, &i.ID)
	return i, err
}

const insertBetOrder = `-- name: InsertBetOrder :one
INSERT INTO bet_orders (
    order_no, member_id, lottery_code, lottery_name, lottery_category,
    issue_no, amount, pnl, status, placed_at, play_method, bet_payload,
    outbound_lottery_code, outbound_play_code,
    guaji_account_id, third_party_bet_id, currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 0, 'pending', now(), $8, $9, $10, $11,
    $12, $13, $14
)
RETURNING id, order_no, lottery_code, lottery_name, issue_no, amount::float8 AS amount, status, placed_at
`

type InsertBetOrderParams struct {
	OrderNo             string         `json:"order_no"`
	MemberID            int64          `json:"member_id"`
	LotteryCode         string         `json:"lottery_code"`
	LotteryName         string         `json:"lottery_name"`
	LotteryCategory     string         `json:"lottery_category"`
	IssueNo             string         `json:"issue_no"`
	Amount              pgtype.Numeric `json:"amount"`
	PlayMethod          pgtype.Text    `json:"play_method"`
	BetPayload          []byte         `json:"bet_payload"`
	OutboundLotteryCode pgtype.Text    `json:"outbound_lottery_code"`
	OutboundPlayCode    pgtype.Text    `json:"outbound_play_code"`
	GuajiAccountID      pgtype.Int8    `json:"guaji_account_id"`
	ThirdPartyBetID     pgtype.Text    `json:"third_party_bet_id"`
	Currency            pgtype.Text    `json:"currency"`
}

type InsertBetOrderRow struct {
	ID          int64              `json:"id"`
	OrderNo     string             `json:"order_no"`
	LotteryCode string             `json:"lottery_code"`
	LotteryName string             `json:"lottery_name"`
	IssueNo     string             `json:"issue_no"`
	Amount      float64            `json:"amount"`
	Status      string             `json:"status"`
	PlacedAt    pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) InsertBetOrder(ctx context.Context, arg InsertBetOrderParams) (InsertBetOrderRow, error) {
	row := q.db.QueryRow(ctx, insertBetOrder,
		arg.OrderNo,
		arg.MemberID,
		arg.LotteryCode,
		arg.LotteryName,
		arg.LotteryCategory,
		arg.IssueNo,
		arg.Amount,
		arg.PlayMethod,
		arg.BetPayload,
		arg.OutboundLotteryCode,
		arg.OutboundPlayCode,
		arg.GuajiAccountID,
		arg.ThirdPartyBetID,
		arg.Currency,
	)
	var i InsertBetOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.LotteryCode,
		&i.LotteryName,
		&i.IssueNo,
		&i.Amount,
		&i.Status,
		&i.PlacedAt,
	)
	return i, err
}

const insertSettledBetOrder = `-- name: InsertSettledBetOrder :exec
INSERT INTO bet_orders (
    order_no, member_id, lottery_code, lottery_name, lottery_category,
    issue_no, amount, pnl, status, placed_at, settled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
)
`

type InsertSettledBetOrderParams struct {
	OrderNo         string         `json:"order_no"`
	MemberID        int64          `json:"member_id"`
	LotteryCode     string         `json:"lottery_code"`
	LotteryName     string         `json:"lottery_name"`
	LotteryCategory string         `json:"lottery_category"`
	IssueNo         string         `json:"issue_no"`
	Amount          pgtype.Numeric `json:"amount"`
	Pnl             pgtype.Numeric `json:"pnl"`
	Status          string         `json:"status"`
}

func (q *Queries) InsertSettledBetOrder(ctx context.Context, arg InsertSettledBetOrderParams) error {
	_, err := q.db.Exec(ctx, insertSettledBetOrder,
		arg.OrderNo,
		arg.MemberID,
		arg.LotteryCode,
		arg.LotteryName,
		arg.LotteryCategory,
		arg.IssueNo,
		arg.Amount,
		arg.Pnl,
		arg.Status,
	)
	return err
}

const listBetOrders = `-- name: ListBetOrders :many
SELECT
    b.id,
    b.order_no,
    b.third_party_bet_id,
    b.lottery_name,
    b.issue_no,
    b.amount::float8 AS amount,
    b.pnl::float8 AS pnl,
    b.status,
    b.placed_at
FROM bet_orders b
WHERE b.member_id = $1
  AND b.placed_at >= $2
  AND b.placed_at < $3
  AND (
    $4::text IS NULL
    OR b.status = $4::text
  )
  AND (
    $5::text IS NULL
    OR b.lottery_category = $5::text
  )
  AND (
    $6::text IS NULL
    OR b.lottery_code = $6::text
  )
  AND (
    $7::text IS NULL
    OR $7::text = ''
    OR b.order_no ILIKE '%' || $7::text || '%'
    OR b.third_party_bet_id ILIKE '%' || $7::text || '%'
  )
ORDER BY b.placed_at DESC, b.id DESC
LIMIT $8
`

type ListBetOrdersParams struct {
	MemberID        int64              `json:"member_id"`
	TimeFrom        pgtype.Timestamptz `json:"time_from"`
	TimeTo          pgtype.Timestamptz `json:"time_to"`
	Status          pgtype.Text        `json:"status"`
	LotteryCategory pgtype.Text        `json:"lottery_category"`
	LotteryCode     pgtype.Text        `json:"lottery_code"`
	OrderNo         pgtype.Text        `json:"order_no"`
	RowLimit        int32              `json:"row_limit"`
}

type ListBetOrdersRow struct {
	ID              int64              `json:"id"`
	OrderNo         string             `json:"order_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	LotteryName     string             `json:"lottery_name"`
	IssueNo         string             `json:"issue_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListBetOrders(ctx context.Context, arg ListBetOrdersParams) ([]ListBetOrdersRow, error) {
	rows, err := q.db.Query(ctx, listBetOrders,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.Status,
		arg.LotteryCategory,
		arg.LotteryCode,
		arg.OrderNo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBetOrdersRow{}
	for rows.Next() {
		var i ListBetOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ThirdPartyBetID,
			&i.LotteryName,
			&i.IssueNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetOrdersAfterCursor = `-- name: ListBetOrdersAfterCursor :many
SELECT
    b.id,
    b.order_no,
    b.third_party_bet_id,
    b.lottery_name,
    b.issue_no,
    b.amount::float8 AS amount,
    b.pnl::float8 AS pnl,
    b.status,
    b.placed_at
FROM bet_orders b
WHERE b.member_id = $1
  AND b.placed_at >= $2
  AND b.placed_at < $3
  AND (
    $4::text IS NULL
    OR b.status = $4::text
  )
  AND (
    $5::text IS NULL
    OR b.lottery_category = $5::text
  )
  AND (
    $6::text IS NULL
    OR b.lottery_code = $6::text
  )
  AND (
    $7::text IS NULL
    OR $7::text = ''
    OR b.order_no ILIKE '%' || $7::text || '%'
    OR b.third_party_bet_id ILIKE '%' || $7::text || '%'
  )
  AND (
    b.placed_at < $8
    OR (b.placed_at = $8 AND b.id < $9)
  )
ORDER BY b.placed_at DESC, b.id DESC
LIMIT $10
`

type ListBetOrdersAfterCursorParams struct {
	MemberID        int64              `json:"member_id"`
	TimeFrom        pgtype.Timestamptz `json:"time_from"`
	TimeTo          pgtype.Timestamptz `json:"time_to"`
	Status          pgtype.Text        `json:"status"`
	LotteryCategory pgtype.Text        `json:"lottery_category"`
	LotteryCode     pgtype.Text        `json:"lottery_code"`
	OrderNo         pgtype.Text        `json:"order_no"`
	CursorTime      pgtype.Timestamptz `json:"cursor_time"`
	CursorID        int64              `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListBetOrdersAfterCursorRow struct {
	ID              int64              `json:"id"`
	OrderNo         string             `json:"order_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	LotteryName     string             `json:"lottery_name"`
	IssueNo         string             `json:"issue_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListBetOrdersAfterCursor(ctx context.Context, arg ListBetOrdersAfterCursorParams) ([]ListBetOrdersAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listBetOrdersAfterCursor,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.Status,
		arg.LotteryCategory,
		arg.LotteryCode,
		arg.OrderNo,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBetOrdersAfterCursorRow{}
	for rows.Next() {
		var i ListBetOrdersAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.ThirdPartyBetID,
			&i.LotteryName,
			&i.IssueNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBetOrdersForSettlement = `-- name: ListPendingBetOrdersForSettlement :many
SELECT
    b.id,
    b.order_no,
    b.member_id,
    b.lottery_code,
    b.issue_no,
    b.amount::float8 AS amount,
    COALESCE(b.play_method, '') AS play_method,
    b.bet_payload,
    b.guaji_account_id
FROM bet_orders b
WHERE b.status = 'pending'
  AND b.guaji_account_id IS NULL
ORDER BY b.placed_at ASC, b.id ASC
LIMIT $1
`

type ListPendingBetOrdersForSettlementRow struct {
	ID             int64       `json:"id"`
	OrderNo        string      `json:"order_no"`
	MemberID       int64       `json:"member_id"`
	LotteryCode    string      `json:"lottery_code"`
	IssueNo        string      `json:"issue_no"`
	Amount         float64     `json:"amount"`
	PlayMethod     string      `json:"play_method"`
	BetPayload     []byte      `json:"bet_payload"`
	GuajiAccountID pgtype.Int8 `json:"guaji_account_id"`
}

func (q *Queries) ListPendingBetOrdersForSettlement(ctx context.Context, rowLimit int32) ([]ListPendingBetOrdersForSettlementRow, error) {
	rows, err := q.db.Query(ctx, listPendingBetOrdersForSettlement, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingBetOrdersForSettlementRow{}
	for rows.Next() {
		var i ListPendingBetOrdersForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.MemberID,
			&i.LotteryCode,
			&i.IssueNo,
			&i.Amount,
			&i.PlayMethod,
			&i.BetPayload,
			&i.GuajiAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGuajiBetOrders = `-- name: ListPendingGuajiBetOrders :many
SELECT
    b.id,
    b.order_no,
    b.member_id,
    b.guaji_account_id,
    b.third_party_bet_id,
    b.amount::float8 AS amount,
    COALESCE(b.currency, '') AS currency
FROM bet_orders b
WHERE b.status = 'pending'
  AND b.guaji_account_id IS NOT NULL
  AND b.third_party_bet_id IS NOT NULL
ORDER BY b.placed_at ASC, b.id ASC
LIMIT $1
`

type ListPendingGuajiBetOrdersRow struct {
	ID              int64       `json:"id"`
	OrderNo         string      `json:"order_no"`
	MemberID        int64       `json:"member_id"`
	GuajiAccountID  pgtype.Int8 `json:"guaji_account_id"`
	ThirdPartyBetID pgtype.Text `json:"third_party_bet_id"`
	Amount          float64     `json:"amount"`
	Currency        string      `json:"currency"`
}

func (q *Queries) ListPendingGuajiBetOrders(ctx context.Context, rowLimit int32) ([]ListPendingGuajiBetOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPendingGuajiBetOrders, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingGuajiBetOrdersRow{}
	for rows.Next() {
		var i ListPendingGuajiBetOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.MemberID,
			&i.GuajiAccountID,
			&i.ThirdPartyBetID,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleBetOrder = `-- name: SettleBetOrder :execrows
UPDATE bet_orders
SET status = $2,
    pnl = $3,
    settled_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
`

type SettleBetOrderParams struct {
	ID     int64          `json:"id"`
	Status string         `json:"status"`
	Pnl    pgtype.Numeric `json:"pnl"`
}

func (q *Queries) SettleBetOrder(ctx context.Context, arg SettleBetOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleBetOrder, arg.ID, arg.Status, arg.Pnl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
