// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chase_orders.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChaseOrderCursorAnchor = `-- name: GetChaseOrderCursorAnchor :one
SELECT c.started_at, c.id
FROM chase_orders c
WHERE c.member_id = $1
  AND c.chase_no = $2
`

type GetChaseOrderCursorAnchorParams struct {
	MemberID int64  `json:"member_id"`
	ChaseNo  string `json:"chase_no"`
}

type GetChaseOrderCursorAnchorRow struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ID        int64              `json:"id"`
}

func (q *Queries) GetChaseOrderCursorAnchor(ctx context.Context, arg GetChaseOrderCursorAnchorParams) (GetChaseOrderCursorAnchorRow, error) {
	row := q.db.QueryRow(ctx, getChaseOrderCursorAnchor, arg.MemberID, arg.ChaseNo)
	var i GetChaseOrderCursorAnchorRow
	err := row.Scan(&i.StartedAt, &i.ID)
	return i, err
}

const listChaseOrders = `-- name: ListChaseOrders :many
SELECT
    c.id,
    c.chase_no,
    c.lottery_name,
    c.lottery_category,
    c.total_issues,
    c.done_issues,
    c.amount::float8 AS amount,
    c.status,
    c.started_at
FROM chase_orders c
WHERE c.member_id = $1
  AND c.started_at >= $2
  AND c.started_at < $3
  AND (
    $4::text IS NULL
    OR c.lottery_category = $4::text
  )
ORDER BY c.started_at DESC, c.id DESC
LIMIT $5
`

type ListChaseOrdersParams struct {
	MemberID        int64              `json:"member_id"`
	TimeFrom        pgtype.Timestamptz `json:"time_from"`
	TimeTo          pgtype.Timestamptz `json:"time_to"`
	LotteryCategory pgtype.Text        `json:"lottery_category"`
	RowLimit        int32              `json:"row_limit"`
}

type ListChaseOrdersRow struct {
	ID              int64              `json:"id"`
	ChaseNo         string             `json:"chase_no"`
	LotteryName     string             `json:"lottery_name"`
	LotteryCategory string             `json:"lottery_category"`
	TotalIssues     int32              `json:"total_issues"`
	DoneIssues      int32              `json:"done_issues"`
	Amount          float64            `json:"amount"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ListChaseOrders(ctx context.Context, arg ListChaseOrdersParams) ([]ListChaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listChaseOrders,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.LotteryCategory,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaseOrdersRow{}
	for rows.Next() {
		var i ListChaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ChaseNo,
			&i.LotteryName,
			&i.LotteryCategory,
			&i.TotalIssues,
			&i.DoneIssues,
			&i.Amount,
			&i.Status,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaseOrdersAfterCursor = `-- name: ListChaseOrdersAfterCursor :many
SELECT
    c.id,
    c.chase_no,
    c.lottery_name,
    c.lottery_category,
    c.total_issues,
    c.done_issues,
    c.amount::float8 AS amount,
    c.status,
    c.started_at
FROM chase_orders c
WHERE c.member_id = $1
  AND c.started_at >= $2
  AND c.started_at < $3
  AND (
    $4::text IS NULL
    OR c.lottery_category = $4::text
  )
  AND (
    c.started_at < $5
    OR (c.started_at = $5 AND c.id < $6)
  )
ORDER BY c.started_at DESC, c.id DESC
LIMIT $7
`

type ListChaseOrdersAfterCursorParams struct {
	MemberID        int64              `json:"member_id"`
	TimeFrom        pgtype.Timestamptz `json:"time_from"`
	TimeTo          pgtype.Timestamptz `json:"time_to"`
	LotteryCategory pgtype.Text        `json:"lottery_category"`
	CursorTime      pgtype.Timestamptz `json:"cursor_time"`
	CursorID        int64              `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListChaseOrdersAfterCursorRow struct {
	ID              int64              `json:"id"`
	ChaseNo         string             `json:"chase_no"`
	LotteryName     string             `json:"lottery_name"`
	LotteryCategory string             `json:"lottery_category"`
	TotalIssues     int32              `json:"total_issues"`
	DoneIssues      int32              `json:"done_issues"`
	Amount          float64            `json:"amount"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ListChaseOrdersAfterCursor(ctx context.Context, arg ListChaseOrdersAfterCursorParams) ([]ListChaseOrdersAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listChaseOrdersAfterCursor,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.LotteryCategory,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaseOrdersAfterCursorRow{}
	for rows.Next() {
		var i ListChaseOrdersAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.ChaseNo,
			&i.LotteryName,
			&i.LotteryCategory,
			&i.TotalIssues,
			&i.DoneIssues,
			&i.Amount,
			&i.Status,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
