// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cloud_bet_records.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existsCloudBetRecordForInstancePeriod = `-- name: ExistsCloudBetRecordForInstancePeriod :one
SELECT EXISTS(
    SELECT 1 FROM cloud_bet_records
    WHERE scheme_id = $1 AND period_no = $2
)::bool AS exists
`

type ExistsCloudBetRecordForInstancePeriodParams struct {
	SchemeID string `json:"scheme_id"`
	PeriodNo string `json:"period_no"`
}

func (q *Queries) ExistsCloudBetRecordForInstancePeriod(ctx context.Context, arg ExistsCloudBetRecordForInstancePeriodParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCloudBetRecordForInstancePeriod, arg.SchemeID, arg.PeriodNo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCloudBetRecordCursorAnchor = `-- name: GetCloudBetRecordCursorAnchor :one
SELECT c.placed_at, c.id
FROM cloud_bet_records c
WHERE c.member_id = $1
  AND c.record_no = $2
`

type GetCloudBetRecordCursorAnchorParams struct {
	MemberID int64  `json:"member_id"`
	RecordNo string `json:"record_no"`
}

type GetCloudBetRecordCursorAnchorRow struct {
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
	ID       int64              `json:"id"`
}

func (q *Queries) GetCloudBetRecordCursorAnchor(ctx context.Context, arg GetCloudBetRecordCursorAnchorParams) (GetCloudBetRecordCursorAnchorRow, error) {
	row := q.db.QueryRow(ctx, getCloudBetRecordCursorAnchor, arg.MemberID, arg.RecordNo)
	var i GetCloudBetRecordCursorAnchorRow
	err := row.Scan(&i.PlacedAt, &i.ID)
	return i, err
}

const insertCloudBetRecord = `-- name: InsertCloudBetRecord :exec
INSERT INTO cloud_bet_records (
    record_no, member_id, sim_bet, scheme_id, scheme_name,
    period_no, play_type, multiplier, round_label, amount, pnl, status, bet_content,
    guaji_account_id, third_party_bet_id, bet_order_no, placed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now()
)
`

type InsertCloudBetRecordParams struct {
	RecordNo        string         `json:"record_no"`
	MemberID        int64          `json:"member_id"`
	SimBet          bool           `json:"sim_bet"`
	SchemeID        string         `json:"scheme_id"`
	SchemeName      string         `json:"scheme_name"`
	PeriodNo        string         `json:"period_no"`
	PlayType        string         `json:"play_type"`
	Multiplier      string         `json:"multiplier"`
	RoundLabel      string         `json:"round_label"`
	Amount          pgtype.Numeric `json:"amount"`
	Pnl             pgtype.Numeric `json:"pnl"`
	Status          string         `json:"status"`
	BetContent      string         `json:"bet_content"`
	GuajiAccountID  pgtype.Int8    `json:"guaji_account_id"`
	ThirdPartyBetID pgtype.Text    `json:"third_party_bet_id"`
	BetOrderNo      pgtype.Text    `json:"bet_order_no"`
}

func (q *Queries) InsertCloudBetRecord(ctx context.Context, arg InsertCloudBetRecordParams) error {
	_, err := q.db.Exec(ctx, insertCloudBetRecord,
		arg.RecordNo,
		arg.MemberID,
		arg.SimBet,
		arg.SchemeID,
		arg.SchemeName,
		arg.PeriodNo,
		arg.PlayType,
		arg.Multiplier,
		arg.RoundLabel,
		arg.Amount,
		arg.Pnl,
		arg.Status,
		arg.BetContent,
		arg.GuajiAccountID,
		arg.ThirdPartyBetID,
		arg.BetOrderNo,
	)
	return err
}

const listCloudBetRecords = `-- name: ListCloudBetRecords :many
SELECT
    c.record_no,
    COALESCE(
        NULLIF(TRIM(c.third_party_bet_id), ''),
        (
            SELECT NULLIF(TRIM(bo.third_party_bet_id), '')
            FROM bet_orders bo
            WHERE bo.member_id = c.member_id
              AND NULLIF(TRIM(bo.third_party_bet_id), '') IS NOT NULL
              AND (
                (NULLIF(TRIM(c.bet_order_no), '') IS NOT NULL AND bo.order_no = c.bet_order_no)
                OR (
                    bo.issue_no = c.period_no
                    AND bo.guaji_account_id IS NOT NULL
                    AND bo.placed_at BETWEEN c.placed_at - INTERVAL '10 minutes' AND c.placed_at + INTERVAL '10 minutes'
                )
              )
            ORDER BY
                CASE WHEN bo.order_no = c.bet_order_no THEN 0 ELSE 1 END,
                ABS(EXTRACT(EPOCH FROM (bo.placed_at - c.placed_at)))
            LIMIT 1
        )
    ) AS third_party_bet_id,
    c.scheme_id,
    c.scheme_name,
    c.period_no,
    c.third_party_period,
    c.play_type,
    c.multiplier,
    c.round_label,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.bet_content,
    c.placed_at
FROM cloud_bet_records c
WHERE c.member_id = $1
  AND c.sim_bet = $2
  AND c.placed_at >= $3
  AND c.placed_at < $4
ORDER BY c.placed_at DESC, c.id DESC
`

type ListCloudBetRecordsParams struct {
	MemberID int64              `json:"member_id"`
	SimBet   bool               `json:"sim_bet"`
	SinceAt  pgtype.Timestamptz `json:"since_at"`
	UntilAt  pgtype.Timestamptz `json:"until_at"`
}

type ListCloudBetRecordsRow struct {
	RecordNo         string             `json:"record_no"`
	ThirdPartyBetID  interface{}        `json:"third_party_bet_id"`
	SchemeID         string             `json:"scheme_id"`
	SchemeName       string             `json:"scheme_name"`
	PeriodNo         string             `json:"period_no"`
	ThirdPartyPeriod pgtype.Text        `json:"third_party_period"`
	PlayType         string             `json:"play_type"`
	Multiplier       string             `json:"multiplier"`
	RoundLabel       string             `json:"round_label"`
	Amount           float64            `json:"amount"`
	Pnl              float64            `json:"pnl"`
	Status           string             `json:"status"`
	BetContent       string             `json:"bet_content"`
	PlacedAt         pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecords(ctx context.Context, arg ListCloudBetRecordsParams) ([]ListCloudBetRecordsRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecords,
		arg.MemberID,
		arg.SimBet,
		arg.SinceAt,
		arg.UntilAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsRow{}
	for rows.Next() {
		var i ListCloudBetRecordsRow
		if err := rows.Scan(
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeID,
			&i.SchemeName,
			&i.PeriodNo,
			&i.ThirdPartyPeriod,
			&i.PlayType,
			&i.Multiplier,
			&i.RoundLabel,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.BetContent,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsByDefinition = `-- name: ListCloudBetRecordsByDefinition :many
SELECT
    c.id,
    c.record_no,
    c.third_party_bet_id,
    c.scheme_name,
    si.lottery_label,
    c.period_no,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.placed_at
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
WHERE c.member_id = $1
  AND si.definition_id = $2
  AND c.placed_at >= $3
  AND c.placed_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR c.record_no ILIKE '%' || $5::text || '%'
    OR c.bet_order_no ILIKE '%' || $5::text || '%'
    OR c.third_party_bet_id ILIKE '%' || $5::text || '%'
  )
  AND (
    NOT c.sim_bet
    AND $6::bigint IS NOT NULL
    AND c.guaji_account_id = $6::bigint
  )
ORDER BY c.placed_at DESC, c.id DESC
LIMIT $7
`

type ListCloudBetRecordsByDefinitionParams struct {
	MemberID       int64              `json:"member_id"`
	DefinitionID   string             `json:"definition_id"`
	SinceAt        pgtype.Timestamptz `json:"since_at"`
	UntilAt        pgtype.Timestamptz `json:"until_at"`
	OrderNo        pgtype.Text        `json:"order_no"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListCloudBetRecordsByDefinitionRow struct {
	ID              int64              `json:"id"`
	RecordNo        string             `json:"record_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	SchemeName      string             `json:"scheme_name"`
	LotteryLabel    string             `json:"lottery_label"`
	PeriodNo        string             `json:"period_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsByDefinition(ctx context.Context, arg ListCloudBetRecordsByDefinitionParams) ([]ListCloudBetRecordsByDefinitionRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsByDefinition,
		arg.MemberID,
		arg.DefinitionID,
		arg.SinceAt,
		arg.UntilAt,
		arg.OrderNo,
		arg.GuajiAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsByDefinitionRow{}
	for rows.Next() {
		var i ListCloudBetRecordsByDefinitionRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeName,
			&i.LotteryLabel,
			&i.PeriodNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsByDefinitionAfterCursor = `-- name: ListCloudBetRecordsByDefinitionAfterCursor :many
SELECT
    c.id,
    c.record_no,
    c.third_party_bet_id,
    c.scheme_name,
    si.lottery_label,
    c.period_no,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.placed_at
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
WHERE c.member_id = $1
  AND si.definition_id = $2
  AND c.placed_at >= $3
  AND c.placed_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR c.record_no ILIKE '%' || $5::text || '%'
    OR c.bet_order_no ILIKE '%' || $5::text || '%'
    OR c.third_party_bet_id ILIKE '%' || $5::text || '%'
  )
  AND (
    NOT c.sim_bet
    AND $6::bigint IS NOT NULL
    AND c.guaji_account_id = $6::bigint
  )
  AND (
    c.placed_at < $7
    OR (c.placed_at = $7 AND c.id < $8)
  )
ORDER BY c.placed_at DESC, c.id DESC
LIMIT $9
`

type ListCloudBetRecordsByDefinitionAfterCursorParams struct {
	MemberID       int64              `json:"member_id"`
	DefinitionID   string             `json:"definition_id"`
	SinceAt        pgtype.Timestamptz `json:"since_at"`
	UntilAt        pgtype.Timestamptz `json:"until_at"`
	OrderNo        pgtype.Text        `json:"order_no"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	CursorTime     pgtype.Timestamptz `json:"cursor_time"`
	CursorID       int64              `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListCloudBetRecordsByDefinitionAfterCursorRow struct {
	ID              int64              `json:"id"`
	RecordNo        string             `json:"record_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	SchemeName      string             `json:"scheme_name"`
	LotteryLabel    string             `json:"lottery_label"`
	PeriodNo        string             `json:"period_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsByDefinitionAfterCursor(ctx context.Context, arg ListCloudBetRecordsByDefinitionAfterCursorParams) ([]ListCloudBetRecordsByDefinitionAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsByDefinitionAfterCursor,
		arg.MemberID,
		arg.DefinitionID,
		arg.SinceAt,
		arg.UntilAt,
		arg.OrderNo,
		arg.GuajiAccountID,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsByDefinitionAfterCursorRow{}
	for rows.Next() {
		var i ListCloudBetRecordsByDefinitionAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeName,
			&i.LotteryLabel,
			&i.PeriodNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsByLottery = `-- name: ListCloudBetRecordsByLottery :many
SELECT
    c.id,
    c.record_no,
    c.third_party_bet_id,
    c.scheme_name,
    si.lottery_label,
    c.period_no,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.placed_at
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
WHERE c.member_id = $1
  AND si.lottery_code = $2
  AND c.placed_at >= $3
  AND c.placed_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR c.record_no ILIKE '%' || $5::text || '%'
    OR c.bet_order_no ILIKE '%' || $5::text || '%'
    OR c.third_party_bet_id ILIKE '%' || $5::text || '%'
  )
  AND (
    NOT c.sim_bet
    AND $6::bigint IS NOT NULL
    AND c.guaji_account_id = $6::bigint
  )
ORDER BY c.placed_at DESC, c.id DESC
LIMIT $7
`

type ListCloudBetRecordsByLotteryParams struct {
	MemberID       int64              `json:"member_id"`
	LotteryCode    string             `json:"lottery_code"`
	SinceAt        pgtype.Timestamptz `json:"since_at"`
	UntilAt        pgtype.Timestamptz `json:"until_at"`
	OrderNo        pgtype.Text        `json:"order_no"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListCloudBetRecordsByLotteryRow struct {
	ID              int64              `json:"id"`
	RecordNo        string             `json:"record_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	SchemeName      string             `json:"scheme_name"`
	LotteryLabel    string             `json:"lottery_label"`
	PeriodNo        string             `json:"period_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsByLottery(ctx context.Context, arg ListCloudBetRecordsByLotteryParams) ([]ListCloudBetRecordsByLotteryRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsByLottery,
		arg.MemberID,
		arg.LotteryCode,
		arg.SinceAt,
		arg.UntilAt,
		arg.OrderNo,
		arg.GuajiAccountID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsByLotteryRow{}
	for rows.Next() {
		var i ListCloudBetRecordsByLotteryRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeName,
			&i.LotteryLabel,
			&i.PeriodNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsByLotteryAfterCursor = `-- name: ListCloudBetRecordsByLotteryAfterCursor :many
SELECT
    c.id,
    c.record_no,
    c.third_party_bet_id,
    c.scheme_name,
    si.lottery_label,
    c.period_no,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.placed_at
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
WHERE c.member_id = $1
  AND si.lottery_code = $2
  AND c.placed_at >= $3
  AND c.placed_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR c.record_no ILIKE '%' || $5::text || '%'
    OR c.bet_order_no ILIKE '%' || $5::text || '%'
    OR c.third_party_bet_id ILIKE '%' || $5::text || '%'
  )
  AND (
    NOT c.sim_bet
    AND $6::bigint IS NOT NULL
    AND c.guaji_account_id = $6::bigint
  )
  AND (
    c.placed_at < $7
    OR (c.placed_at = $7 AND c.id < $8)
  )
ORDER BY c.placed_at DESC, c.id DESC
LIMIT $9
`

type ListCloudBetRecordsByLotteryAfterCursorParams struct {
	MemberID       int64              `json:"member_id"`
	LotteryCode    string             `json:"lottery_code"`
	SinceAt        pgtype.Timestamptz `json:"since_at"`
	UntilAt        pgtype.Timestamptz `json:"until_at"`
	OrderNo        pgtype.Text        `json:"order_no"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	CursorTime     pgtype.Timestamptz `json:"cursor_time"`
	CursorID       int64              `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListCloudBetRecordsByLotteryAfterCursorRow struct {
	ID              int64              `json:"id"`
	RecordNo        string             `json:"record_no"`
	ThirdPartyBetID pgtype.Text        `json:"third_party_bet_id"`
	SchemeName      string             `json:"scheme_name"`
	LotteryLabel    string             `json:"lottery_label"`
	PeriodNo        string             `json:"period_no"`
	Amount          float64            `json:"amount"`
	Pnl             float64            `json:"pnl"`
	Status          string             `json:"status"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsByLotteryAfterCursor(ctx context.Context, arg ListCloudBetRecordsByLotteryAfterCursorParams) ([]ListCloudBetRecordsByLotteryAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsByLotteryAfterCursor,
		arg.MemberID,
		arg.LotteryCode,
		arg.SinceAt,
		arg.UntilAt,
		arg.OrderNo,
		arg.GuajiAccountID,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsByLotteryAfterCursorRow{}
	for rows.Next() {
		var i ListCloudBetRecordsByLotteryAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeName,
			&i.LotteryLabel,
			&i.PeriodNo,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsByScheme = `-- name: ListCloudBetRecordsByScheme :many
SELECT
    c.record_no,
    c.scheme_id,
    c.scheme_name,
    c.period_no,
    c.third_party_period,
    c.play_type,
    c.multiplier,
    c.round_label,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.placed_at
FROM cloud_bet_records c
WHERE c.member_id = $1
  AND c.sim_bet = $2
  AND c.scheme_id = $3
  AND c.placed_at >= $4
  AND c.placed_at < $5
ORDER BY c.placed_at DESC, c.id DESC
`

type ListCloudBetRecordsBySchemeParams struct {
	MemberID int64              `json:"member_id"`
	SimBet   bool               `json:"sim_bet"`
	SchemeID string             `json:"scheme_id"`
	SinceAt  pgtype.Timestamptz `json:"since_at"`
	UntilAt  pgtype.Timestamptz `json:"until_at"`
}

type ListCloudBetRecordsBySchemeRow struct {
	RecordNo         string             `json:"record_no"`
	SchemeID         string             `json:"scheme_id"`
	SchemeName       string             `json:"scheme_name"`
	PeriodNo         string             `json:"period_no"`
	ThirdPartyPeriod pgtype.Text        `json:"third_party_period"`
	PlayType         string             `json:"play_type"`
	Multiplier       string             `json:"multiplier"`
	RoundLabel       string             `json:"round_label"`
	Amount           float64            `json:"amount"`
	Pnl              float64            `json:"pnl"`
	Status           string             `json:"status"`
	PlacedAt         pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsByScheme(ctx context.Context, arg ListCloudBetRecordsBySchemeParams) ([]ListCloudBetRecordsBySchemeRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsByScheme,
		arg.MemberID,
		arg.SimBet,
		arg.SchemeID,
		arg.SinceAt,
		arg.UntilAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsBySchemeRow{}
	for rows.Next() {
		var i ListCloudBetRecordsBySchemeRow
		if err := rows.Scan(
			&i.RecordNo,
			&i.SchemeID,
			&i.SchemeName,
			&i.PeriodNo,
			&i.ThirdPartyPeriod,
			&i.PlayType,
			&i.Multiplier,
			&i.RoundLabel,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCloudBetRecordsFiltered = `-- name: ListCloudBetRecordsFiltered :many
SELECT
    c.record_no,
    COALESCE(
        NULLIF(TRIM(c.third_party_bet_id), ''),
        (
            SELECT NULLIF(TRIM(bo.third_party_bet_id), '')
            FROM bet_orders bo
            WHERE bo.member_id = c.member_id
              AND NULLIF(TRIM(bo.third_party_bet_id), '') IS NOT NULL
              AND (
                (NULLIF(TRIM(c.bet_order_no), '') IS NOT NULL AND bo.order_no = c.bet_order_no)
                OR (
                    bo.issue_no = c.period_no
                    AND bo.guaji_account_id IS NOT NULL
                    AND bo.placed_at BETWEEN c.placed_at - INTERVAL '10 minutes' AND c.placed_at + INTERVAL '10 minutes'
                )
              )
            ORDER BY
                CASE WHEN bo.order_no = c.bet_order_no THEN 0 ELSE 1 END,
                ABS(EXTRACT(EPOCH FROM (bo.placed_at - c.placed_at)))
            LIMIT 1
        )
    ) AS third_party_bet_id,
    c.scheme_id,
    c.scheme_name,
    si.lottery_code,
    c.period_no,
    c.third_party_period,
    c.play_type,
    c.multiplier,
    c.round_label,
    c.amount::float8 AS amount,
    c.pnl::float8 AS pnl,
    c.status,
    c.bet_content,
    c.placed_at
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
WHERE c.member_id = $1
  AND c.placed_at >= $2
  AND c.placed_at < $3
  AND (
    $4::boolean IS NULL
    OR c.sim_bet = $4::boolean
  )
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR si.lottery_code = $5::text
  )
  AND (
    $4::boolean IS NOT DISTINCT FROM true
    OR (
      NOT c.sim_bet
      AND $6::bigint IS NOT NULL
      AND c.guaji_account_id = $6::bigint
      AND NULLIF(TRIM(c.third_party_bet_id), '') IS NOT NULL
    )
  )
ORDER BY c.placed_at DESC, c.id DESC
`

type ListCloudBetRecordsFilteredParams struct {
	MemberID       int64              `json:"member_id"`
	SinceAt        pgtype.Timestamptz `json:"since_at"`
	UntilAt        pgtype.Timestamptz `json:"until_at"`
	SimBet         pgtype.Bool        `json:"sim_bet"`
	LotteryCode    pgtype.Text        `json:"lottery_code"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
}

type ListCloudBetRecordsFilteredRow struct {
	RecordNo         string             `json:"record_no"`
	ThirdPartyBetID  interface{}        `json:"third_party_bet_id"`
	SchemeID         string             `json:"scheme_id"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	PeriodNo         string             `json:"period_no"`
	ThirdPartyPeriod pgtype.Text        `json:"third_party_period"`
	PlayType         string             `json:"play_type"`
	Multiplier       string             `json:"multiplier"`
	RoundLabel       string             `json:"round_label"`
	Amount           float64            `json:"amount"`
	Pnl              float64            `json:"pnl"`
	Status           string             `json:"status"`
	BetContent       string             `json:"bet_content"`
	PlacedAt         pgtype.Timestamptz `json:"placed_at"`
}

func (q *Queries) ListCloudBetRecordsFiltered(ctx context.Context, arg ListCloudBetRecordsFilteredParams) ([]ListCloudBetRecordsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listCloudBetRecordsFiltered,
		arg.MemberID,
		arg.SinceAt,
		arg.UntilAt,
		arg.SimBet,
		arg.LotteryCode,
		arg.GuajiAccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCloudBetRecordsFilteredRow{}
	for rows.Next() {
		var i ListCloudBetRecordsFilteredRow
		if err := rows.Scan(
			&i.RecordNo,
			&i.ThirdPartyBetID,
			&i.SchemeID,
			&i.SchemeName,
			&i.LotteryCode,
			&i.PeriodNo,
			&i.ThirdPartyPeriod,
			&i.PlayType,
			&i.Multiplier,
			&i.RoundLabel,
			&i.Amount,
			&i.Pnl,
			&i.Status,
			&i.BetContent,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCloudBetRecordFromSettlement = `-- name: UpdateCloudBetRecordFromSettlement :execrows
UPDATE cloud_bet_records
SET status = $2,
    pnl = $3
WHERE bet_order_no = $1
  AND status = 'pending'
`

type UpdateCloudBetRecordFromSettlementParams struct {
	BetOrderNo pgtype.Text    `json:"bet_order_no"`
	Status     string         `json:"status"`
	Pnl        pgtype.Numeric `json:"pnl"`
}

func (q *Queries) UpdateCloudBetRecordFromSettlement(ctx context.Context, arg UpdateCloudBetRecordFromSettlementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCloudBetRecordFromSettlement, arg.BetOrderNo, arg.Status, arg.Pnl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
