// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cloud_settings.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberCloudSettings = `-- name: GetMemberCloudSettings :one
SELECT member_id, total_stop_loss, total_take_profit, plan_multiplier, break_period_stop, created_at, updated_at
FROM member_cloud_settings
WHERE member_id = $1
`

func (q *Queries) GetMemberCloudSettings(ctx context.Context, memberID int64) (MemberCloudSetting, error) {
	row := q.db.QueryRow(ctx, getMemberCloudSettings, memberID)
	var i MemberCloudSetting
	err := row.Scan(
		&i.MemberID,
		&i.TotalStopLoss,
		&i.TotalTakeProfit,
		&i.PlanMultiplier,
		&i.BreakPeriodStop,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMemberCloudSettings = `-- name: UpsertMemberCloudSettings :one
INSERT INTO member_cloud_settings (
    member_id, total_stop_loss, total_take_profit, plan_multiplier, break_period_stop, updated_at
) VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (member_id) DO UPDATE SET
    total_stop_loss = EXCLUDED.total_stop_loss,
    total_take_profit = EXCLUDED.total_take_profit,
    plan_multiplier = EXCLUDED.plan_multiplier,
    break_period_stop = EXCLUDED.break_period_stop,
    updated_at = now()
RETURNING member_id, total_stop_loss, total_take_profit, plan_multiplier, break_period_stop, created_at, updated_at
`

type UpsertMemberCloudSettingsParams struct {
	MemberID        int64          `json:"member_id"`
	TotalStopLoss   pgtype.Numeric `json:"total_stop_loss"`
	TotalTakeProfit pgtype.Numeric `json:"total_take_profit"`
	PlanMultiplier  pgtype.Numeric `json:"plan_multiplier"`
	BreakPeriodStop bool           `json:"break_period_stop"`
}

func (q *Queries) UpsertMemberCloudSettings(ctx context.Context, arg UpsertMemberCloudSettingsParams) (MemberCloudSetting, error) {
	row := q.db.QueryRow(ctx, upsertMemberCloudSettings,
		arg.MemberID,
		arg.TotalStopLoss,
		arg.TotalTakeProfit,
		arg.PlanMultiplier,
		arg.BreakPeriodStop,
	)
	var i MemberCloudSetting
	err := row.Scan(
		&i.MemberID,
		&i.TotalStopLoss,
		&i.TotalTakeProfit,
		&i.PlanMultiplier,
		&i.BreakPeriodStop,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
