// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cms_customer_service.sql

package sqlcdb

import (
	"context"
)

const deleteCustomerServiceAgent = `-- name: DeleteCustomerServiceAgent :exec
DELETE FROM cms_customer_service_agents WHERE id = $1
`

func (q *Queries) DeleteCustomerServiceAgent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCustomerServiceAgent, id)
	return err
}

const listCustomerServiceAgents = `-- name: ListCustomerServiceAgents :many
SELECT id, name, tg_link, work_hours, sort, enabled, created_at, updated_at
FROM cms_customer_service_agents
ORDER BY sort ASC, id ASC
`

func (q *Queries) ListCustomerServiceAgents(ctx context.Context) ([]CmsCustomerServiceAgent, error) {
	rows, err := q.db.Query(ctx, listCustomerServiceAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmsCustomerServiceAgent{}
	for rows.Next() {
		var i CmsCustomerServiceAgent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TgLink,
			&i.WorkHours,
			&i.Sort,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCustomerServiceAgents = `-- name: ListEnabledCustomerServiceAgents :many
SELECT id, name, tg_link, work_hours, sort
FROM cms_customer_service_agents
WHERE enabled = true
ORDER BY sort ASC, id ASC
`

type ListEnabledCustomerServiceAgentsRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TgLink    string `json:"tg_link"`
	WorkHours string `json:"work_hours"`
	Sort      int32  `json:"sort"`
}

func (q *Queries) ListEnabledCustomerServiceAgents(ctx context.Context) ([]ListEnabledCustomerServiceAgentsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledCustomerServiceAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledCustomerServiceAgentsRow{}
	for rows.Next() {
		var i ListEnabledCustomerServiceAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TgLink,
			&i.WorkHours,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomerServiceAgent = `-- name: UpsertCustomerServiceAgent :one
INSERT INTO cms_customer_service_agents (id, name, tg_link, work_hours, sort, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    tg_link = EXCLUDED.tg_link,
    work_hours = EXCLUDED.work_hours,
    sort = EXCLUDED.sort,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, name, tg_link, work_hours, sort, enabled, created_at, updated_at
`

type UpsertCustomerServiceAgentParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TgLink    string `json:"tg_link"`
	WorkHours string `json:"work_hours"`
	Sort      int32  `json:"sort"`
	Enabled   bool   `json:"enabled"`
}

func (q *Queries) UpsertCustomerServiceAgent(ctx context.Context, arg UpsertCustomerServiceAgentParams) (CmsCustomerServiceAgent, error) {
	row := q.db.QueryRow(ctx, upsertCustomerServiceAgent,
		arg.ID,
		arg.Name,
		arg.TgLink,
		arg.WorkHours,
		arg.Sort,
		arg.Enabled,
	)
	var i CmsCustomerServiceAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TgLink,
		&i.WorkHours,
		&i.Sort,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
