// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: content.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnnouncementAdmin = `-- name: DeleteAnnouncementAdmin :exec
DELETE FROM cms_announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncementAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementAdmin, id)
	return err
}

const deleteFaqArticleAdmin = `-- name: DeleteFaqArticleAdmin :exec
DELETE FROM cms_faq_articles WHERE id = $1
`

func (q *Queries) DeleteFaqArticleAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFaqArticleAdmin, id)
	return err
}

const deleteHelpArticleAdmin = `-- name: DeleteHelpArticleAdmin :exec
DELETE FROM cms_help_articles WHERE id = $1
`

func (q *Queries) DeleteHelpArticleAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteHelpArticleAdmin, id)
	return err
}

const getFaqArticle = `-- name: GetFaqArticle :one
SELECT id, title, body_html
FROM cms_faq_articles
WHERE id = $1
`

type GetFaqArticleRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) GetFaqArticle(ctx context.Context, id string) (GetFaqArticleRow, error) {
	row := q.db.QueryRow(ctx, getFaqArticle, id)
	var i GetFaqArticleRow
	err := row.Scan(&i.ID, &i.Title, &i.BodyHtml)
	return i, err
}

const getPromoChannelAdmin = `-- name: GetPromoChannelAdmin :one
SELECT default_material, invite_code_required
FROM cms_promo_channel
WHERE id = 'default'
`

type GetPromoChannelAdminRow struct {
	DefaultMaterial    string `json:"default_material"`
	InviteCodeRequired bool   `json:"invite_code_required"`
}

func (q *Queries) GetPromoChannelAdmin(ctx context.Context) (GetPromoChannelAdminRow, error) {
	row := q.db.QueryRow(ctx, getPromoChannelAdmin)
	var i GetPromoChannelAdminRow
	err := row.Scan(&i.DefaultMaterial, &i.InviteCodeRequired)
	return i, err
}

const getPublishedAnnouncement = `-- name: GetPublishedAnnouncement :one
SELECT id, title, published_at, body_html
FROM cms_announcements
WHERE id = $1 AND status = 'published'
`

type GetPublishedAnnouncementRow struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	BodyHtml    string             `json:"body_html"`
}

func (q *Queries) GetPublishedAnnouncement(ctx context.Context, id string) (GetPublishedAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, getPublishedAnnouncement, id)
	var i GetPublishedAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PublishedAt,
		&i.BodyHtml,
	)
	return i, err
}

const getSiteBrandAdmin = `-- name: GetSiteBrandAdmin :one
SELECT site_name, logo_url, tagline
FROM cms_site_brand
WHERE id = 'default'
`

type GetSiteBrandAdminRow struct {
	SiteName string `json:"site_name"`
	LogoUrl  string `json:"logo_url"`
	Tagline  string `json:"tagline"`
}

func (q *Queries) GetSiteBrandAdmin(ctx context.Context) (GetSiteBrandAdminRow, error) {
	row := q.db.QueryRow(ctx, getSiteBrandAdmin)
	var i GetSiteBrandAdminRow
	err := row.Scan(&i.SiteName, &i.LogoUrl, &i.Tagline)
	return i, err
}

const getSiteBrandPublic = `-- name: GetSiteBrandPublic :one
SELECT site_name, logo_url, tagline
FROM cms_site_brand
WHERE id = 'default'
`

type GetSiteBrandPublicRow struct {
	SiteName string `json:"site_name"`
	LogoUrl  string `json:"logo_url"`
	Tagline  string `json:"tagline"`
}

func (q *Queries) GetSiteBrandPublic(ctx context.Context) (GetSiteBrandPublicRow, error) {
	row := q.db.QueryRow(ctx, getSiteBrandPublic)
	var i GetSiteBrandPublicRow
	err := row.Scan(&i.SiteName, &i.LogoUrl, &i.Tagline)
	return i, err
}

const insertMemberFeedback = `-- name: InsertMemberFeedback :one
INSERT INTO member_feedback (member_id, subject, content)
VALUES ($1, $2, $3)
RETURNING id, subject, content, created_at
`

type InsertMemberFeedbackParams struct {
	MemberID int64  `json:"member_id"`
	Subject  string `json:"subject"`
	Content  string `json:"content"`
}

type InsertMemberFeedbackRow struct {
	ID        int64              `json:"id"`
	Subject   string             `json:"subject"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertMemberFeedback(ctx context.Context, arg InsertMemberFeedbackParams) (InsertMemberFeedbackRow, error) {
	row := q.db.QueryRow(ctx, insertMemberFeedback, arg.MemberID, arg.Subject, arg.Content)
	var i InsertMemberFeedbackRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listAnnouncementsAdmin = `-- name: ListAnnouncementsAdmin :many
SELECT id, title, status, published_at, body_html, pinned
FROM cms_announcements
ORDER BY pinned DESC, published_at DESC NULLS LAST, id DESC
`

type ListAnnouncementsAdminRow struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	BodyHtml    string             `json:"body_html"`
	Pinned      bool               `json:"pinned"`
}

func (q *Queries) ListAnnouncementsAdmin(ctx context.Context) ([]ListAnnouncementsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsAdminRow{}
	for rows.Next() {
		var i ListAnnouncementsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.PublishedAt,
			&i.BodyHtml,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFaqArticles = `-- name: ListFaqArticles :many
SELECT id, title, sort
FROM cms_faq_articles
ORDER BY sort ASC, id ASC
`

type ListFaqArticlesRow struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Sort  int32  `json:"sort"`
}

func (q *Queries) ListFaqArticles(ctx context.Context) ([]ListFaqArticlesRow, error) {
	rows, err := q.db.Query(ctx, listFaqArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFaqArticlesRow{}
	for rows.Next() {
		var i ListFaqArticlesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Sort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFaqArticlesAdmin = `-- name: ListFaqArticlesAdmin :many
SELECT id, title, sort, body_html
FROM cms_faq_articles
ORDER BY sort ASC, id ASC
`

type ListFaqArticlesAdminRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) ListFaqArticlesAdmin(ctx context.Context) ([]ListFaqArticlesAdminRow, error) {
	rows, err := q.db.Query(ctx, listFaqArticlesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFaqArticlesAdminRow{}
	for rows.Next() {
		var i ListFaqArticlesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sort,
			&i.BodyHtml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHelpArticles = `-- name: ListHelpArticles :many
SELECT id, title, sort, body_html
FROM cms_help_articles
ORDER BY sort ASC, id ASC
`

type ListHelpArticlesRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) ListHelpArticles(ctx context.Context) ([]ListHelpArticlesRow, error) {
	rows, err := q.db.Query(ctx, listHelpArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHelpArticlesRow{}
	for rows.Next() {
		var i ListHelpArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sort,
			&i.BodyHtml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHelpArticlesAdmin = `-- name: ListHelpArticlesAdmin :many
SELECT id, title, sort, body_html
FROM cms_help_articles
ORDER BY sort ASC, id ASC
`

type ListHelpArticlesAdminRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) ListHelpArticlesAdmin(ctx context.Context) ([]ListHelpArticlesAdminRow, error) {
	rows, err := q.db.Query(ctx, listHelpArticlesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHelpArticlesAdminRow{}
	for rows.Next() {
		var i ListHelpArticlesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sort,
			&i.BodyHtml,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLobbySlotsAdmin = `-- name: ListLobbySlotsAdmin :many
SELECT id, slot_key, title, brief, sort, enabled
FROM cms_lobby_slots
ORDER BY sort ASC, id ASC
`

type ListLobbySlotsAdminRow struct {
	ID      string `json:"id"`
	SlotKey string `json:"slot_key"`
	Title   string `json:"title"`
	Brief   string `json:"brief"`
	Sort    int32  `json:"sort"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) ListLobbySlotsAdmin(ctx context.Context) ([]ListLobbySlotsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLobbySlotsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLobbySlotsAdminRow{}
	for rows.Next() {
		var i ListLobbySlotsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.SlotKey,
			&i.Title,
			&i.Brief,
			&i.Sort,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLobbySlotsPublic = `-- name: ListLobbySlotsPublic :many
SELECT slot_key, title, brief, sort
FROM cms_lobby_slots
WHERE enabled = true
ORDER BY sort ASC, id ASC
`

type ListLobbySlotsPublicRow struct {
	SlotKey string `json:"slot_key"`
	Title   string `json:"title"`
	Brief   string `json:"brief"`
	Sort    int32  `json:"sort"`
}

func (q *Queries) ListLobbySlotsPublic(ctx context.Context) ([]ListLobbySlotsPublicRow, error) {
	rows, err := q.db.Query(ctx, listLobbySlotsPublic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLobbySlotsPublicRow{}
	for rows.Next() {
		var i ListLobbySlotsPublicRow
		if err := rows.Scan(
			&i.SlotKey,
			&i.Title,
			&i.Brief,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAnnouncements = `-- name: ListPublishedAnnouncements :many
SELECT a.id, a.title, a.published_at,
       EXISTS (
           SELECT 1 FROM member_announcement_reads r
           WHERE r.member_id = $1 AND r.announcement_id = a.id
       ) AS is_read
FROM cms_announcements a
WHERE a.status = 'published'
ORDER BY a.pinned DESC, a.published_at DESC NULLS LAST, a.id DESC
`

type ListPublishedAnnouncementsRow struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	IsRead      bool               `json:"is_read"`
}

func (q *Queries) ListPublishedAnnouncements(ctx context.Context, memberID int64) ([]ListPublishedAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedAnnouncements, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedAnnouncementsRow{}
	for rows.Next() {
		var i ListPublishedAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PublishedAt,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnnouncementAdmin = `-- name: UpsertAnnouncementAdmin :one
INSERT INTO cms_announcements (id, title, status, published_at, body_html, pinned)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    status = EXCLUDED.status,
    published_at = EXCLUDED.published_at,
    body_html = EXCLUDED.body_html,
    pinned = CASE WHEN EXCLUDED.status = 'draft' THEN false ELSE cms_announcements.pinned END
RETURNING id, title, status, published_at, body_html, pinned
`

type UpsertAnnouncementAdminParams struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	BodyHtml    string             `json:"body_html"`
	Pinned      bool               `json:"pinned"`
}

type UpsertAnnouncementAdminRow struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	BodyHtml    string             `json:"body_html"`
	Pinned      bool               `json:"pinned"`
}

func (q *Queries) UpsertAnnouncementAdmin(ctx context.Context, arg UpsertAnnouncementAdminParams) (UpsertAnnouncementAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertAnnouncementAdmin,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.PublishedAt,
		arg.BodyHtml,
		arg.Pinned,
	)
	var i UpsertAnnouncementAdminRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.PublishedAt,
		&i.BodyHtml,
		&i.Pinned,
	)
	return i, err
}

const clearAnnouncementPinsAdmin = `-- name: ClearAnnouncementPinsAdmin :exec
UPDATE cms_announcements SET pinned = false WHERE pinned = true
`

func (q *Queries) ClearAnnouncementPinsAdmin(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAnnouncementPinsAdmin)
	return err
}

const setAnnouncementPinnedAdmin = `-- name: SetAnnouncementPinnedAdmin :one
UPDATE cms_announcements
SET pinned = $2
WHERE id = $1
RETURNING id, title, status, published_at, body_html, pinned
`

type SetAnnouncementPinnedAdminParams struct {
	ID     string `json:"id"`
	Pinned bool   `json:"pinned"`
}

type SetAnnouncementPinnedAdminRow = UpsertAnnouncementAdminRow

func (q *Queries) SetAnnouncementPinnedAdmin(ctx context.Context, arg SetAnnouncementPinnedAdminParams) (SetAnnouncementPinnedAdminRow, error) {
	row := q.db.QueryRow(ctx, setAnnouncementPinnedAdmin, arg.ID, arg.Pinned)
	var i SetAnnouncementPinnedAdminRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.PublishedAt,
		&i.BodyHtml,
		&i.Pinned,
	)
	return i, err
}

const upsertAnnouncementRead = `-- name: UpsertAnnouncementRead :exec
INSERT INTO member_announcement_reads (member_id, announcement_id, read_at)
VALUES ($1, $2, now())
ON CONFLICT (member_id, announcement_id) DO UPDATE SET read_at = EXCLUDED.read_at
`

type UpsertAnnouncementReadParams struct {
	MemberID       int64  `json:"member_id"`
	AnnouncementID string `json:"announcement_id"`
}

func (q *Queries) UpsertAnnouncementRead(ctx context.Context, arg UpsertAnnouncementReadParams) error {
	_, err := q.db.Exec(ctx, upsertAnnouncementRead, arg.MemberID, arg.AnnouncementID)
	return err
}

const upsertFaqArticleAdmin = `-- name: UpsertFaqArticleAdmin :one
INSERT INTO cms_faq_articles (id, title, sort, body_html)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    sort = EXCLUDED.sort,
    body_html = EXCLUDED.body_html
RETURNING id, title, sort, body_html
`

type UpsertFaqArticleAdminParams struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

type UpsertFaqArticleAdminRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) UpsertFaqArticleAdmin(ctx context.Context, arg UpsertFaqArticleAdminParams) (UpsertFaqArticleAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertFaqArticleAdmin,
		arg.ID,
		arg.Title,
		arg.Sort,
		arg.BodyHtml,
	)
	var i UpsertFaqArticleAdminRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Sort,
		&i.BodyHtml,
	)
	return i, err
}

const upsertHelpArticleAdmin = `-- name: UpsertHelpArticleAdmin :one
INSERT INTO cms_help_articles (id, title, sort, body_html)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    sort = EXCLUDED.sort,
    body_html = EXCLUDED.body_html
RETURNING id, title, sort, body_html
`

type UpsertHelpArticleAdminParams struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

type UpsertHelpArticleAdminRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Sort     int32  `json:"sort"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) UpsertHelpArticleAdmin(ctx context.Context, arg UpsertHelpArticleAdminParams) (UpsertHelpArticleAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertHelpArticleAdmin,
		arg.ID,
		arg.Title,
		arg.Sort,
		arg.BodyHtml,
	)
	var i UpsertHelpArticleAdminRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Sort,
		&i.BodyHtml,
	)
	return i, err
}

const upsertLobbySlotAdmin = `-- name: UpsertLobbySlotAdmin :one
INSERT INTO cms_lobby_slots (id, slot_key, title, brief, sort, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    slot_key = EXCLUDED.slot_key,
    title = EXCLUDED.title,
    brief = EXCLUDED.brief,
    sort = EXCLUDED.sort,
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, slot_key, title, brief, sort, enabled
`

type UpsertLobbySlotAdminParams struct {
	ID      string `json:"id"`
	SlotKey string `json:"slot_key"`
	Title   string `json:"title"`
	Brief   string `json:"brief"`
	Sort    int32  `json:"sort"`
	Enabled bool   `json:"enabled"`
}

type UpsertLobbySlotAdminRow struct {
	ID      string `json:"id"`
	SlotKey string `json:"slot_key"`
	Title   string `json:"title"`
	Brief   string `json:"brief"`
	Sort    int32  `json:"sort"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpsertLobbySlotAdmin(ctx context.Context, arg UpsertLobbySlotAdminParams) (UpsertLobbySlotAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertLobbySlotAdmin,
		arg.ID,
		arg.SlotKey,
		arg.Title,
		arg.Brief,
		arg.Sort,
		arg.Enabled,
	)
	var i UpsertLobbySlotAdminRow
	err := row.Scan(
		&i.ID,
		&i.SlotKey,
		&i.Title,
		&i.Brief,
		&i.Sort,
		&i.Enabled,
	)
	return i, err
}

const upsertPromoChannelAdmin = `-- name: UpsertPromoChannelAdmin :one
INSERT INTO cms_promo_channel (id, default_material, invite_code_required)
VALUES ('default', $1, $2)
ON CONFLICT (id) DO UPDATE SET
    default_material = EXCLUDED.default_material,
    invite_code_required = EXCLUDED.invite_code_required,
    updated_at = now()
RETURNING default_material, invite_code_required
`

type UpsertPromoChannelAdminParams struct {
	DefaultMaterial    string `json:"default_material"`
	InviteCodeRequired bool   `json:"invite_code_required"`
}

type UpsertPromoChannelAdminRow struct {
	DefaultMaterial    string `json:"default_material"`
	InviteCodeRequired bool   `json:"invite_code_required"`
}

func (q *Queries) UpsertPromoChannelAdmin(ctx context.Context, arg UpsertPromoChannelAdminParams) (UpsertPromoChannelAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertPromoChannelAdmin, arg.DefaultMaterial, arg.InviteCodeRequired)
	var i UpsertPromoChannelAdminRow
	err := row.Scan(&i.DefaultMaterial, &i.InviteCodeRequired)
	return i, err
}

const upsertSiteBrandAdmin = `-- name: UpsertSiteBrandAdmin :one
INSERT INTO cms_site_brand (id, site_name, logo_url, tagline)
VALUES ('default', $1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    site_name = EXCLUDED.site_name,
    logo_url = EXCLUDED.logo_url,
    tagline = EXCLUDED.tagline,
    updated_at = now()
RETURNING site_name, logo_url, tagline
`

type UpsertSiteBrandAdminParams struct {
	SiteName string `json:"site_name"`
	LogoUrl  string `json:"logo_url"`
	Tagline  string `json:"tagline"`
}

type UpsertSiteBrandAdminRow struct {
	SiteName string `json:"site_name"`
	LogoUrl  string `json:"logo_url"`
	Tagline  string `json:"tagline"`
}

func (q *Queries) UpsertSiteBrandAdmin(ctx context.Context, arg UpsertSiteBrandAdminParams) (UpsertSiteBrandAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertSiteBrandAdmin, arg.SiteName, arg.LogoUrl, arg.Tagline)
	var i UpsertSiteBrandAdminRow
	err := row.Scan(&i.SiteName, &i.LogoUrl, &i.Tagline)
	return i, err
}
