// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copy_hall.sql

package sqlcdb

import (
	"context"
)

const deleteAllCopyHallRankSlots = `-- name: DeleteAllCopyHallRankSlots :exec
DELETE FROM copy_hall_rank_slots
`

func (q *Queries) DeleteAllCopyHallRankSlots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCopyHallRankSlots)
	return err
}

const deleteCopyHallBoardSlots = `-- name: DeleteCopyHallBoardSlots :exec
DELETE FROM copy_hall_rank_slots
WHERE board_kind = $1
`

func (q *Queries) DeleteCopyHallBoardSlots(ctx context.Context, boardKind string) error {
	_, err := q.db.Exec(ctx, deleteCopyHallBoardSlots, boardKind)
	return err
}

const listAllCopyHallRankSlots = `-- name: ListAllCopyHallRankSlots :many
SELECT lottery_code, board_kind, rank, scheme_id, scheme_name, play_method, play_type_id, sub_play_id
FROM copy_hall_rank_slots
ORDER BY board_kind ASC, rank ASC
`

type ListAllCopyHallRankSlotsRow struct {
	LotteryCode string `json:"lottery_code"`
	BoardKind   string `json:"board_kind"`
	Rank        int32  `json:"rank"`
	SchemeID    string `json:"scheme_id"`
	SchemeName  string `json:"scheme_name"`
	PlayMethod  string `json:"play_method"`
	PlayTypeID  string `json:"play_type_id"`
	SubPlayID   string `json:"sub_play_id"`
}

func (q *Queries) ListAllCopyHallRankSlots(ctx context.Context) ([]ListAllCopyHallRankSlotsRow, error) {
	rows, err := q.db.Query(ctx, listAllCopyHallRankSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCopyHallRankSlotsRow{}
	for rows.Next() {
		var i ListAllCopyHallRankSlotsRow
		if err := rows.Scan(
			&i.LotteryCode,
			&i.BoardKind,
			&i.Rank,
			&i.SchemeID,
			&i.SchemeName,
			&i.PlayMethod,
			&i.PlayTypeID,
			&i.SubPlayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCopyHallRankSlots = `-- name: ListCopyHallRankSlots :many
SELECT lottery_code, rank, scheme_id, scheme_name, play_method, play_type_id, sub_play_id
FROM copy_hall_rank_slots
WHERE board_kind = $1
ORDER BY rank ASC
`

type ListCopyHallRankSlotsRow struct {
	LotteryCode string `json:"lottery_code"`
	Rank        int32  `json:"rank"`
	SchemeID    string `json:"scheme_id"`
	SchemeName  string `json:"scheme_name"`
	PlayMethod  string `json:"play_method"`
	PlayTypeID  string `json:"play_type_id"`
	SubPlayID   string `json:"sub_play_id"`
}

func (q *Queries) ListCopyHallRankSlots(ctx context.Context, boardKind string) ([]ListCopyHallRankSlotsRow, error) {
	rows, err := q.db.Query(ctx, listCopyHallRankSlots, boardKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCopyHallRankSlotsRow{}
	for rows.Next() {
		var i ListCopyHallRankSlotsRow
		if err := rows.Scan(
			&i.LotteryCode,
			&i.Rank,
			&i.SchemeID,
			&i.SchemeName,
			&i.PlayMethod,
			&i.PlayTypeID,
			&i.SubPlayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCopyHallRankSlot = `-- name: UpsertCopyHallRankSlot :exec
INSERT INTO copy_hall_rank_slots (lottery_code, board_kind, rank, scheme_id, scheme_name, play_method, play_type_id, sub_play_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (board_kind, rank)
DO UPDATE SET
    lottery_code = EXCLUDED.lottery_code,
    scheme_id = EXCLUDED.scheme_id,
    scheme_name = EXCLUDED.scheme_name,
    play_method = EXCLUDED.play_method,
    play_type_id = EXCLUDED.play_type_id,
    sub_play_id = EXCLUDED.sub_play_id,
    updated_at = now()
`

type UpsertCopyHallRankSlotParams struct {
	LotteryCode string `json:"lottery_code"`
	BoardKind   string `json:"board_kind"`
	Rank        int32  `json:"rank"`
	SchemeID    string `json:"scheme_id"`
	SchemeName  string `json:"scheme_name"`
	PlayMethod  string `json:"play_method"`
	PlayTypeID  string `json:"play_type_id"`
	SubPlayID   string `json:"sub_play_id"`
}

func (q *Queries) UpsertCopyHallRankSlot(ctx context.Context, arg UpsertCopyHallRankSlotParams) error {
	_, err := q.db.Exec(ctx, upsertCopyHallRankSlot,
		arg.LotteryCode,
		arg.BoardKind,
		arg.Rank,
		arg.SchemeID,
		arg.SchemeName,
		arg.PlayMethod,
		arg.PlayTypeID,
		arg.SubPlayID,
	)
	return err
}
