// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fund_records.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemberFundRecords = `-- name: CountMemberFundRecords :one
SELECT COUNT(*)::bigint AS count
FROM wallet_ledger l
WHERE l.member_id = $1
  AND l.guaji_account_id = $2
  AND l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $3
  AND l.created_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
`

type CountMemberFundRecordsParams struct {
	MemberID       int64              `json:"member_id"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	TimeFrom       pgtype.Timestamptz `json:"time_from"`
	TimeTo         pgtype.Timestamptz `json:"time_to"`
	FlowDir        pgtype.Text        `json:"flow_dir"`
	Currency       pgtype.Text        `json:"currency"`
}

func (q *Queries) CountMemberFundRecords(ctx context.Context, arg CountMemberFundRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberFundRecords,
		arg.MemberID,
		arg.GuajiAccountID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.FlowDir,
		arg.Currency,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMemberFundRecords = `-- name: ListMemberFundRecords :many
SELECT
    l.id,
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.currency, 'CNY') AS currency,
    l.created_at,
    COALESCE(sch.scheme_name, '') AS scheme_name
FROM wallet_ledger l
LEFT JOIN LATERAL (
    SELECT c.scheme_name
    FROM cloud_bet_records c
    WHERE c.member_id = l.member_id
      AND (
        (NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref)
        OR (
          NULLIF(TRIM(l.order_ref), '') IS NULL
          AND ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at))) <= 5
          AND ABS(c.amount::float8 - ABS(l.delta_amount::float8)) < 0.001
          AND c.guaji_account_id IS NOT DISTINCT FROM l.guaji_account_id
        )
      )
    ORDER BY
      CASE WHEN NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref THEN 0 ELSE 1 END,
      ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at)))
    LIMIT 1
) sch ON true
WHERE l.member_id = $1
  AND l.guaji_account_id = $2
  AND l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $3
  AND l.created_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $7
`

type ListMemberFundRecordsParams struct {
	MemberID       int64              `json:"member_id"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	TimeFrom       pgtype.Timestamptz `json:"time_from"`
	TimeTo         pgtype.Timestamptz `json:"time_to"`
	FlowDir        pgtype.Text        `json:"flow_dir"`
	Currency       pgtype.Text        `json:"currency"`
	RowLimit       int32              `json:"row_limit"`
}

type ListMemberFundRecordsRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchemeName   string             `json:"scheme_name"`
}

func (q *Queries) ListMemberFundRecords(ctx context.Context, arg ListMemberFundRecordsParams) ([]ListMemberFundRecordsRow, error) {
	rows, err := q.db.Query(ctx, listMemberFundRecords,
		arg.MemberID,
		arg.GuajiAccountID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.FlowDir,
		arg.Currency,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberFundRecordsRow{}
	for rows.Next() {
		var i ListMemberFundRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.Currency,
			&i.CreatedAt,
			&i.SchemeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberFundRecordsAfterCursor = `-- name: ListMemberFundRecordsAfterCursor :many
SELECT
    l.id,
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.currency, 'CNY') AS currency,
    l.created_at,
    COALESCE(sch.scheme_name, '') AS scheme_name
FROM wallet_ledger l
LEFT JOIN LATERAL (
    SELECT c.scheme_name
    FROM cloud_bet_records c
    WHERE c.member_id = l.member_id
      AND (
        (NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref)
        OR (
          NULLIF(TRIM(l.order_ref), '') IS NULL
          AND ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at))) <= 5
          AND ABS(c.amount::float8 - ABS(l.delta_amount::float8)) < 0.001
          AND c.guaji_account_id IS NOT DISTINCT FROM l.guaji_account_id
        )
      )
    ORDER BY
      CASE WHEN NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref THEN 0 ELSE 1 END,
      ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at)))
    LIMIT 1
) sch ON true
WHERE l.member_id = $1
  AND l.guaji_account_id = $2
  AND l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $3
  AND l.created_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
  AND (
    l.created_at < $7
    OR (l.created_at = $7 AND l.id < $8)
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $9
`

type ListMemberFundRecordsAfterCursorParams struct {
	MemberID       int64              `json:"member_id"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	TimeFrom       pgtype.Timestamptz `json:"time_from"`
	TimeTo         pgtype.Timestamptz `json:"time_to"`
	FlowDir        pgtype.Text        `json:"flow_dir"`
	Currency       pgtype.Text        `json:"currency"`
	CursorTime     pgtype.Timestamptz `json:"cursor_time"`
	CursorID       int64              `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListMemberFundRecordsAfterCursorRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchemeName   string             `json:"scheme_name"`
}

func (q *Queries) ListMemberFundRecordsAfterCursor(ctx context.Context, arg ListMemberFundRecordsAfterCursorParams) ([]ListMemberFundRecordsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listMemberFundRecordsAfterCursor,
		arg.MemberID,
		arg.GuajiAccountID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.FlowDir,
		arg.Currency,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberFundRecordsAfterCursorRow{}
	for rows.Next() {
		var i ListMemberFundRecordsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.Currency,
			&i.CreatedAt,
			&i.SchemeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberFundRecordsPaged = `-- name: ListMemberFundRecordsPaged :many
SELECT
    l.id,
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.currency, 'CNY') AS currency,
    l.created_at,
    COALESCE(sch.scheme_name, '') AS scheme_name
FROM wallet_ledger l
LEFT JOIN LATERAL (
    SELECT c.scheme_name
    FROM cloud_bet_records c
    WHERE c.member_id = l.member_id
      AND (
        (NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref)
        OR (
          NULLIF(TRIM(l.order_ref), '') IS NULL
          AND ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at))) <= 5
          AND ABS(c.amount::float8 - ABS(l.delta_amount::float8)) < 0.001
          AND c.guaji_account_id IS NOT DISTINCT FROM l.guaji_account_id
        )
      )
    ORDER BY
      CASE WHEN NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref THEN 0 ELSE 1 END,
      ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at)))
    LIMIT 1
) sch ON true
WHERE l.member_id = $1
  AND l.guaji_account_id = $2
  AND l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $3
  AND l.created_at < $4
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $8 OFFSET $7
`

type ListMemberFundRecordsPagedParams struct {
	MemberID       int64              `json:"member_id"`
	GuajiAccountID pgtype.Int8        `json:"guaji_account_id"`
	TimeFrom       pgtype.Timestamptz `json:"time_from"`
	TimeTo         pgtype.Timestamptz `json:"time_to"`
	FlowDir        pgtype.Text        `json:"flow_dir"`
	Currency       pgtype.Text        `json:"currency"`
	RowOffset      int32              `json:"row_offset"`
	RowLimit       int32              `json:"row_limit"`
}

type ListMemberFundRecordsPagedRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchemeName   string             `json:"scheme_name"`
}

func (q *Queries) ListMemberFundRecordsPaged(ctx context.Context, arg ListMemberFundRecordsPagedParams) ([]ListMemberFundRecordsPagedRow, error) {
	rows, err := q.db.Query(ctx, listMemberFundRecordsPaged,
		arg.MemberID,
		arg.GuajiAccountID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.FlowDir,
		arg.Currency,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberFundRecordsPagedRow{}
	for rows.Next() {
		var i ListMemberFundRecordsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.Currency,
			&i.CreatedAt,
			&i.SchemeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminFundRecords = `-- name: CountAdminFundRecords :one
SELECT COUNT(*)::bigint
FROM wallet_ledger l
INNER JOIN members m ON m.id = l.member_id
WHERE l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $1
  AND l.created_at < $2
  AND (
    $3::text IS NULL
    OR $3::text = ''
    OR m.account ILIKE '%' || $3::text || '%'
  )
  AND (
    $4::text IS NULL
    OR $4::text = ''
    OR l.ledger_no ILIKE '%' || $4::text || '%'
  )
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
`

type CountAdminFundRecordsParams struct {
	TimeFrom      pgtype.Timestamptz `json:"time_from"`
	TimeTo        pgtype.Timestamptz `json:"time_to"`
	MemberAccount pgtype.Text        `json:"member_account"`
	LedgerNo      pgtype.Text        `json:"ledger_no"`
	FlowDir       pgtype.Text        `json:"flow_dir"`
	Currency      pgtype.Text        `json:"currency"`
}

func (q *Queries) CountAdminFundRecords(ctx context.Context, arg CountAdminFundRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminFundRecords,
		arg.TimeFrom,
		arg.TimeTo,
		arg.MemberAccount,
		arg.LedgerNo,
		arg.FlowDir,
		arg.Currency,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAdminFundRecordsPaged = `-- name: ListAdminFundRecordsPaged :many
SELECT
    l.id,
    l.ledger_no,
    m.account,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.currency, 'CNY') AS currency,
    l.created_at,
    COALESCE(sch.scheme_name, '') AS scheme_name
FROM wallet_ledger l
INNER JOIN members m ON m.id = l.member_id
LEFT JOIN LATERAL (
    SELECT c.scheme_name
    FROM cloud_bet_records c
    WHERE c.member_id = l.member_id
      AND (
        (NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref)
        OR (
          NULLIF(TRIM(l.order_ref), '') IS NULL
          AND ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at))) <= 5
          AND ABS(c.amount::float8 - ABS(l.delta_amount::float8)) < 0.001
          AND c.guaji_account_id IS NOT DISTINCT FROM l.guaji_account_id
        )
      )
    ORDER BY
      CASE WHEN NULLIF(TRIM(l.order_ref), '') IS NOT NULL AND c.bet_order_no = l.order_ref THEN 0 ELSE 1 END,
      ABS(EXTRACT(EPOCH FROM (c.placed_at - l.created_at)))
    LIMIT 1
) sch ON true
WHERE l.txn_type IN ('bet_debit', 'payout')
  AND l.created_at >= $1
  AND l.created_at < $2
  AND (
    $3::text IS NULL
    OR $3::text = ''
    OR m.account ILIKE '%' || $3::text || '%'
  )
  AND (
    $4::text IS NULL
    OR $4::text = ''
    OR l.ledger_no ILIKE '%' || $4::text || '%'
  )
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR $5::text = 'all'
    OR ($5::text = 'income' AND l.delta_amount > 0)
    OR ($5::text = 'expense' AND l.delta_amount < 0)
  )
  AND (
    $6::text IS NULL
    OR $6::text = ''
    OR COALESCE(l.currency, 'CNY') = $6::text
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $8 OFFSET $7
`

type ListAdminFundRecordsPagedParams struct {
	TimeFrom      pgtype.Timestamptz `json:"time_from"`
	TimeTo        pgtype.Timestamptz `json:"time_to"`
	MemberAccount pgtype.Text        `json:"member_account"`
	LedgerNo      pgtype.Text        `json:"ledger_no"`
	FlowDir       pgtype.Text        `json:"flow_dir"`
	Currency      pgtype.Text        `json:"currency"`
	RowOffset     int32              `json:"row_offset"`
	RowLimit      int32              `json:"row_limit"`
}

type ListAdminFundRecordsPagedRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	Account      string             `json:"account"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	Currency     string             `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchemeName   string             `json:"scheme_name"`
}

func (q *Queries) ListAdminFundRecordsPaged(ctx context.Context, arg ListAdminFundRecordsPagedParams) ([]ListAdminFundRecordsPagedRow, error) {
	rows, err := q.db.Query(ctx, listAdminFundRecordsPaged,
		arg.TimeFrom,
		arg.TimeTo,
		arg.MemberAccount,
		arg.LedgerNo,
		arg.FlowDir,
		arg.Currency,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminFundRecordsPagedRow{}
	for rows.Next() {
		var i ListAdminFundRecordsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.Account,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.Currency,
			&i.CreatedAt,
			&i.SchemeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRechargeOrders = `-- name: ListMemberRechargeOrders :many
SELECT order_no, amount, channel, status, paid_at, created_at
FROM recharge_orders
WHERE member_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMemberRechargeOrdersParams struct {
	MemberID int64 `json:"member_id"`
	RowLimit int32 `json:"row_limit"`
}

type ListMemberRechargeOrdersRow struct {
	OrderNo   string             `json:"order_no"`
	Amount    pgtype.Numeric     `json:"amount"`
	Channel   string             `json:"channel"`
	Status    string             `json:"status"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMemberRechargeOrders(ctx context.Context, arg ListMemberRechargeOrdersParams) ([]ListMemberRechargeOrdersRow, error) {
	rows, err := q.db.Query(ctx, listMemberRechargeOrders, arg.MemberID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberRechargeOrdersRow{}
	for rows.Next() {
		var i ListMemberRechargeOrdersRow
		if err := rows.Scan(
			&i.OrderNo,
			&i.Amount,
			&i.Channel,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
