// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lottery_catalog.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLotteryCatalogWithTemplate = `-- name: CountLotteryCatalogWithTemplate :one
SELECT COUNT(*)::int AS count
FROM lottery_catalog
WHERE play_template IS NOT NULL AND play_template <> ''
`

func (q *Queries) CountLotteryCatalogWithTemplate(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countLotteryCatalogWithTemplate)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLotteryCatalogByCode = `-- name: GetLotteryCatalogByCode :one
SELECT
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
FROM lottery_catalog
WHERE code = $1
`

type GetLotteryCatalogByCodeRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) GetLotteryCatalogByCode(ctx context.Context, code string) (GetLotteryCatalogByCodeRow, error) {
	row := q.db.QueryRow(ctx, getLotteryCatalogByCode, code)
	var i GetLotteryCatalogByCodeRow
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CategoryCode,
		&i.PlayTemplate,
		&i.BallCount,
		&i.DrawInterval,
		&i.SortOrder,
		&i.OnSale,
		&i.SaleStatus,
		&i.OutboundLotteryCode,
	)
	return i, err
}

const listLotteryCatalog = `-- name: ListLotteryCatalog :many
SELECT
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
FROM lottery_catalog
ORDER BY sort_order ASC, code ASC
`

type ListLotteryCatalogRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) ListLotteryCatalog(ctx context.Context) ([]ListLotteryCatalogRow, error) {
	rows, err := q.db.Query(ctx, listLotteryCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteryCatalogRow{}
	for rows.Next() {
		var i ListLotteryCatalogRow
		if err := rows.Scan(
			&i.Code,
			&i.DisplayName,
			&i.CategoryCode,
			&i.PlayTemplate,
			&i.BallCount,
			&i.DrawInterval,
			&i.SortOrder,
			&i.OnSale,
			&i.SaleStatus,
			&i.OutboundLotteryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotteryCatalogOnSale = `-- name: ListLotteryCatalogOnSale :many
SELECT
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
FROM lottery_catalog
WHERE sale_status = 'on_sale'
ORDER BY sort_order ASC, code ASC
`

type ListLotteryCatalogOnSaleRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) ListLotteryCatalogOnSale(ctx context.Context) ([]ListLotteryCatalogOnSaleRow, error) {
	rows, err := q.db.Query(ctx, listLotteryCatalogOnSale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteryCatalogOnSaleRow{}
	for rows.Next() {
		var i ListLotteryCatalogOnSaleRow
		if err := rows.Scan(
			&i.Code,
			&i.DisplayName,
			&i.CategoryCode,
			&i.PlayTemplate,
			&i.BallCount,
			&i.DrawInterval,
			&i.SortOrder,
			&i.OnSale,
			&i.SaleStatus,
			&i.OutboundLotteryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchLotteryCatalogMaintenance = `-- name: PatchLotteryCatalogMaintenance :one
UPDATE lottery_catalog
SET
    display_name = $2,
    outbound_lottery_code = $3,
    sort_order = $4,
    sale_status = $5::lottery_sale_status,
    on_sale = ($5 = 'on_sale'::lottery_sale_status),
    updated_at = now()
WHERE code = $1
  AND sale_status = 'maintenance'::lottery_sale_status
RETURNING
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
`

type PatchLotteryCatalogMaintenanceParams struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
	SortOrder           int32       `json:"sort_order"`
	Column5             interface{} `json:"column_5"`
}

type PatchLotteryCatalogMaintenanceRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) PatchLotteryCatalogMaintenance(ctx context.Context, arg PatchLotteryCatalogMaintenanceParams) (PatchLotteryCatalogMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, patchLotteryCatalogMaintenance,
		arg.Code,
		arg.DisplayName,
		arg.OutboundLotteryCode,
		arg.SortOrder,
		arg.Column5,
	)
	var i PatchLotteryCatalogMaintenanceRow
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CategoryCode,
		&i.PlayTemplate,
		&i.BallCount,
		&i.DrawInterval,
		&i.SortOrder,
		&i.OnSale,
		&i.SaleStatus,
		&i.OutboundLotteryCode,
	)
	return i, err
}

const setLotteryCatalogMaintenance = `-- name: SetLotteryCatalogMaintenance :one
UPDATE lottery_catalog
SET
    sale_status = 'maintenance'::lottery_sale_status,
    on_sale = false,
    updated_at = now()
WHERE code = $1
  AND sale_status = 'on_sale'::lottery_sale_status
RETURNING
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
`

type SetLotteryCatalogMaintenanceRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) SetLotteryCatalogMaintenance(ctx context.Context, code string) (SetLotteryCatalogMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, setLotteryCatalogMaintenance, code)
	var i SetLotteryCatalogMaintenanceRow
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CategoryCode,
		&i.PlayTemplate,
		&i.BallCount,
		&i.DrawInterval,
		&i.SortOrder,
		&i.OnSale,
		&i.SaleStatus,
		&i.OutboundLotteryCode,
	)
	return i, err
}

const syncLotteryCatalogGuaji = `-- name: SyncLotteryCatalogGuaji :one
UPDATE lottery_catalog
SET
    display_name = $2,
    outbound_lottery_code = $3,
    updated_at = now()
WHERE code = $1
RETURNING
    code,
    display_name,
    category_code,
    play_template,
    ball_count,
    draw_interval,
    sort_order,
    on_sale,
    sale_status,
    outbound_lottery_code
`

type SyncLotteryCatalogGuajiParams struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

type SyncLotteryCatalogGuajiRow struct {
	Code                string      `json:"code"`
	DisplayName         string      `json:"display_name"`
	CategoryCode        pgtype.Text `json:"category_code"`
	PlayTemplate        pgtype.Text `json:"play_template"`
	BallCount           pgtype.Int2 `json:"ball_count"`
	DrawInterval        pgtype.Text `json:"draw_interval"`
	SortOrder           int32       `json:"sort_order"`
	OnSale              bool        `json:"on_sale"`
	SaleStatus          interface{} `json:"sale_status"`
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
}

func (q *Queries) SyncLotteryCatalogGuaji(ctx context.Context, arg SyncLotteryCatalogGuajiParams) (SyncLotteryCatalogGuajiRow, error) {
	row := q.db.QueryRow(ctx, syncLotteryCatalogGuaji, arg.Code, arg.DisplayName, arg.OutboundLotteryCode)
	var i SyncLotteryCatalogGuajiRow
	err := row.Scan(
		&i.Code,
		&i.DisplayName,
		&i.CategoryCode,
		&i.PlayTemplate,
		&i.BallCount,
		&i.DrawInterval,
		&i.SortOrder,
		&i.OnSale,
		&i.SaleStatus,
		&i.OutboundLotteryCode,
	)
	return i, err
}

const updateSchemeDefinitionsLotteryLabel = `-- name: UpdateSchemeDefinitionsLotteryLabel :exec
UPDATE scheme_definitions
SET lottery_label = $2, updated_at = now()
WHERE lottery_code = $1
`

type UpdateSchemeDefinitionsLotteryLabelParams struct {
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
}

func (q *Queries) UpdateSchemeDefinitionsLotteryLabel(ctx context.Context, arg UpdateSchemeDefinitionsLotteryLabelParams) error {
	_, err := q.db.Exec(ctx, updateSchemeDefinitionsLotteryLabel, arg.LotteryCode, arg.LotteryLabel)
	return err
}

const updateSchemeInstancesLotteryLabel = `-- name: UpdateSchemeInstancesLotteryLabel :exec
UPDATE scheme_instances
SET lottery_label = $2, updated_at = now()
WHERE lottery_code = $1
`

type UpdateSchemeInstancesLotteryLabelParams struct {
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
}

func (q *Queries) UpdateSchemeInstancesLotteryLabel(ctx context.Context, arg UpdateSchemeInstancesLotteryLabelParams) error {
	_, err := q.db.Exec(ctx, updateSchemeInstancesLotteryLabel, arg.LotteryCode, arg.LotteryLabel)
	return err
}

const updateSchemeShareSnapshotsLotteryLabel = `-- name: UpdateSchemeShareSnapshotsLotteryLabel :exec
UPDATE scheme_share_snapshots
SET lottery_label = $2, updated_at = now()
WHERE lottery_code = $1
`

type UpdateSchemeShareSnapshotsLotteryLabelParams struct {
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
}

func (q *Queries) UpdateSchemeShareSnapshotsLotteryLabel(ctx context.Context, arg UpdateSchemeShareSnapshotsLotteryLabelParams) error {
	_, err := q.db.Exec(ctx, updateSchemeShareSnapshotsLotteryLabel, arg.LotteryCode, arg.LotteryLabel)
	return err
}
