// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lottery_draws.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstLotteryDrawAfterIssue = `-- name: GetFirstLotteryDrawAfterIssue :one
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE lottery_code = $1
  AND issue_no > $2
ORDER BY issue_no ASC
LIMIT 1
`

type GetFirstLotteryDrawAfterIssueParams struct {
	LotteryCode string `json:"lottery_code"`
	IssueNo     string `json:"issue_no"`
}

type GetFirstLotteryDrawAfterIssueRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) GetFirstLotteryDrawAfterIssue(ctx context.Context, arg GetFirstLotteryDrawAfterIssueParams) (GetFirstLotteryDrawAfterIssueRow, error) {
	row := q.db.QueryRow(ctx, getFirstLotteryDrawAfterIssue, arg.LotteryCode, arg.IssueNo)
	var i GetFirstLotteryDrawAfterIssueRow
	err := row.Scan(
		&i.ID,
		&i.LotteryCode,
		&i.IssueNo,
		&i.PeriodShort,
		&i.Balls,
		&i.SumValue,
		&i.DrawnAt,
	)
	return i, err
}

const getLatestLotteryDraw = `-- name: GetLatestLotteryDraw :one
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE lottery_code = $1
ORDER BY drawn_at DESC, id DESC
LIMIT 1
`

type GetLatestLotteryDrawRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) GetLatestLotteryDraw(ctx context.Context, lotteryCode string) (GetLatestLotteryDrawRow, error) {
	row := q.db.QueryRow(ctx, getLatestLotteryDraw, lotteryCode)
	var i GetLatestLotteryDrawRow
	err := row.Scan(
		&i.ID,
		&i.LotteryCode,
		&i.IssueNo,
		&i.PeriodShort,
		&i.Balls,
		&i.SumValue,
		&i.DrawnAt,
	)
	return i, err
}

const getLotteryDrawByID = `-- name: GetLotteryDrawByID :one
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE id = $1 AND lottery_code = $2
`

type GetLotteryDrawByIDParams struct {
	ID          int64  `json:"id"`
	LotteryCode string `json:"lottery_code"`
}

type GetLotteryDrawByIDRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) GetLotteryDrawByID(ctx context.Context, arg GetLotteryDrawByIDParams) (GetLotteryDrawByIDRow, error) {
	row := q.db.QueryRow(ctx, getLotteryDrawByID, arg.ID, arg.LotteryCode)
	var i GetLotteryDrawByIDRow
	err := row.Scan(
		&i.ID,
		&i.LotteryCode,
		&i.IssueNo,
		&i.PeriodShort,
		&i.Balls,
		&i.SumValue,
		&i.DrawnAt,
	)
	return i, err
}

const getLotteryDrawByIssue = `-- name: GetLotteryDrawByIssue :one
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE lottery_code = $1 AND issue_no = $2
`

type GetLotteryDrawByIssueParams struct {
	LotteryCode string `json:"lottery_code"`
	IssueNo     string `json:"issue_no"`
}

type GetLotteryDrawByIssueRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) GetLotteryDrawByIssue(ctx context.Context, arg GetLotteryDrawByIssueParams) (GetLotteryDrawByIssueRow, error) {
	row := q.db.QueryRow(ctx, getLotteryDrawByIssue, arg.LotteryCode, arg.IssueNo)
	var i GetLotteryDrawByIssueRow
	err := row.Scan(
		&i.ID,
		&i.LotteryCode,
		&i.IssueNo,
		&i.PeriodShort,
		&i.Balls,
		&i.SumValue,
		&i.DrawnAt,
	)
	return i, err
}

const insertLotteryDraw = `-- name: InsertLotteryDraw :one
INSERT INTO lottery_draws (lottery_code, issue_no, period_short, balls, sum_value, drawn_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (lottery_code, issue_no) DO NOTHING
RETURNING id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
`

type InsertLotteryDrawParams struct {
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

type InsertLotteryDrawRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) InsertLotteryDraw(ctx context.Context, arg InsertLotteryDrawParams) (InsertLotteryDrawRow, error) {
	row := q.db.QueryRow(ctx, insertLotteryDraw,
		arg.LotteryCode,
		arg.IssueNo,
		arg.PeriodShort,
		arg.Balls,
		arg.SumValue,
		arg.DrawnAt,
	)
	var i InsertLotteryDrawRow
	err := row.Scan(
		&i.ID,
		&i.LotteryCode,
		&i.IssueNo,
		&i.PeriodShort,
		&i.Balls,
		&i.SumValue,
		&i.DrawnAt,
	)
	return i, err
}

const listLotteryDraws = `-- name: ListLotteryDraws :many
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE lottery_code = $1
ORDER BY drawn_at DESC, id DESC
LIMIT $2
`

type ListLotteryDrawsParams struct {
	LotteryCode string `json:"lottery_code"`
	RowLimit    int32  `json:"row_limit"`
}

type ListLotteryDrawsRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) ListLotteryDraws(ctx context.Context, arg ListLotteryDrawsParams) ([]ListLotteryDrawsRow, error) {
	rows, err := q.db.Query(ctx, listLotteryDraws, arg.LotteryCode, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteryDrawsRow{}
	for rows.Next() {
		var i ListLotteryDrawsRow
		if err := rows.Scan(
			&i.ID,
			&i.LotteryCode,
			&i.IssueNo,
			&i.PeriodShort,
			&i.Balls,
			&i.SumValue,
			&i.DrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotteryDrawsAfterCursor = `-- name: ListLotteryDrawsAfterCursor :many
SELECT id, lottery_code, issue_no, period_short, balls, sum_value, drawn_at
FROM lottery_draws
WHERE lottery_code = $1
  AND (
    drawn_at < $2
    OR (drawn_at = $2 AND id < $3)
  )
ORDER BY drawn_at DESC, id DESC
LIMIT $4
`

type ListLotteryDrawsAfterCursorParams struct {
	LotteryCode string             `json:"lottery_code"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    int64              `json:"cursor_id"`
	RowLimit    int32              `json:"row_limit"`
}

type ListLotteryDrawsAfterCursorRow struct {
	ID          int64              `json:"id"`
	LotteryCode string             `json:"lottery_code"`
	IssueNo     string             `json:"issue_no"`
	PeriodShort string             `json:"period_short"`
	Balls       []byte             `json:"balls"`
	SumValue    int32              `json:"sum_value"`
	DrawnAt     pgtype.Timestamptz `json:"drawn_at"`
}

func (q *Queries) ListLotteryDrawsAfterCursor(ctx context.Context, arg ListLotteryDrawsAfterCursorParams) ([]ListLotteryDrawsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listLotteryDrawsAfterCursor,
		arg.LotteryCode,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteryDrawsAfterCursorRow{}
	for rows.Next() {
		var i ListLotteryDrawsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.LotteryCode,
			&i.IssueNo,
			&i.PeriodShort,
			&i.Balls,
			&i.SumValue,
			&i.DrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
