// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lottery_catalog_purge.sql

package sqlcdb

import (
	"context"
)

const deleteAdminAuditLogsForLegacyLotteries = `-- name: DeleteAdminAuditLogsForLegacyLotteries :exec
DELETE FROM admin_audit_logs a
WHERE EXISTS (
    SELECT 1 FROM unnest($1::text[]) AS c(code)
    WHERE a.action ILIKE '%' || c.code || '%'
)
`

func (q *Queries) DeleteAdminAuditLogsForLegacyLotteries(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteAdminAuditLogsForLegacyLotteries, dollar_1)
	return err
}

const deleteBetOrdersByLotteryCodes = `-- name: DeleteBetOrdersByLotteryCodes :exec
DELETE FROM bet_orders
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteBetOrdersByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteBetOrdersByLotteryCodes, dollar_1)
	return err
}

const deleteChaseOrdersByLotteryCodes = `-- name: DeleteChaseOrdersByLotteryCodes :exec
DELETE FROM chase_orders
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteChaseOrdersByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteChaseOrdersByLotteryCodes, dollar_1)
	return err
}

const deleteCloudBetRecordsForLotteryCodes = `-- name: DeleteCloudBetRecordsForLotteryCodes :exec
DELETE FROM cloud_bet_records cbr
USING scheme_instances si
WHERE cbr.scheme_id = si.id
  AND si.lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteCloudBetRecordsForLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteCloudBetRecordsForLotteryCodes, dollar_1)
	return err
}

const deleteCopyHallRankSlotsByLotteryCodes = `-- name: DeleteCopyHallRankSlotsByLotteryCodes :exec
DELETE FROM copy_hall_rank_slots
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteCopyHallRankSlotsByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteCopyHallRankSlotsByLotteryCodes, dollar_1)
	return err
}

const deleteLotteryCatalogByCodes = `-- name: DeleteLotteryCatalogByCodes :exec
DELETE FROM lottery_catalog
WHERE code = ANY($1::text[])
`

func (q *Queries) DeleteLotteryCatalogByCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteLotteryCatalogByCodes, dollar_1)
	return err
}

const deleteLotteryDrawsByLotteryCodes = `-- name: DeleteLotteryDrawsByLotteryCodes :exec
DELETE FROM lottery_draws
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteLotteryDrawsByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteLotteryDrawsByLotteryCodes, dollar_1)
	return err
}

const deleteLotterySchemeOptionSetsByLotteryCodes = `-- name: DeleteLotterySchemeOptionSetsByLotteryCodes :exec
DELETE FROM lottery_scheme_option_sets
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteLotterySchemeOptionSetsByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteLotterySchemeOptionSetsByLotteryCodes, dollar_1)
	return err
}

const deleteSchemeDefinitionsByLotteryCodes = `-- name: DeleteSchemeDefinitionsByLotteryCodes :exec
DELETE FROM scheme_definitions
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteSchemeDefinitionsByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteSchemeDefinitionsByLotteryCodes, dollar_1)
	return err
}

const deleteSchemeShareSnapshotsByLotteryCodes = `-- name: DeleteSchemeShareSnapshotsByLotteryCodes :exec
DELETE FROM scheme_share_snapshots
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteSchemeShareSnapshotsByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteSchemeShareSnapshotsByLotteryCodes, dollar_1)
	return err
}

const deleteSchemeTemplatesByLotteryCodes = `-- name: DeleteSchemeTemplatesByLotteryCodes :exec
DELETE FROM scheme_templates
WHERE lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteSchemeTemplatesByLotteryCodes(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteSchemeTemplatesByLotteryCodes, dollar_1)
	return err
}

const deleteWalletLedgerForBetOrders = `-- name: DeleteWalletLedgerForBetOrders :exec
DELETE FROM wallet_ledger wl
USING bet_orders b
WHERE wl.order_ref = b.order_no
  AND b.lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteWalletLedgerForBetOrders(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteWalletLedgerForBetOrders, dollar_1)
	return err
}

const deleteWalletLedgerForChaseOrders = `-- name: DeleteWalletLedgerForChaseOrders :exec
DELETE FROM wallet_ledger wl
USING chase_orders c
WHERE wl.order_ref = c.chase_no
  AND c.lottery_code = ANY($1::text[])
`

func (q *Queries) DeleteWalletLedgerForChaseOrders(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteWalletLedgerForChaseOrders, dollar_1)
	return err
}
