// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: maintenance.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaintenanceAdmin = `-- name: GetMaintenanceAdmin :one
SELECT enabled, popup_announcement_id, title, message
FROM cms_maintenance
WHERE id = 'default'
`

type GetMaintenanceAdminRow struct {
	Enabled             bool        `json:"enabled"`
	PopupAnnouncementID pgtype.Text `json:"popup_announcement_id"`
	Title               string      `json:"title"`
	Message             string      `json:"message"`
}

func (q *Queries) GetMaintenanceAdmin(ctx context.Context) (GetMaintenanceAdminRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceAdmin)
	var i GetMaintenanceAdminRow
	err := row.Scan(
		&i.Enabled,
		&i.PopupAnnouncementID,
		&i.Title,
		&i.Message,
	)
	return i, err
}

const getPublishedAnnouncementBrief = `-- name: GetPublishedAnnouncementBrief :one
SELECT id, title, body_html
FROM cms_announcements
WHERE id = $1 AND status = 'published'
`

type GetPublishedAnnouncementBriefRow struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	BodyHtml string `json:"body_html"`
}

func (q *Queries) GetPublishedAnnouncementBrief(ctx context.Context, id string) (GetPublishedAnnouncementBriefRow, error) {
	row := q.db.QueryRow(ctx, getPublishedAnnouncementBrief, id)
	var i GetPublishedAnnouncementBriefRow
	err := row.Scan(&i.ID, &i.Title, &i.BodyHtml)
	return i, err
}

const upsertMaintenanceAdmin = `-- name: UpsertMaintenanceAdmin :one
INSERT INTO cms_maintenance (id, enabled, popup_announcement_id, title, message)
VALUES ('default', $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    popup_announcement_id = EXCLUDED.popup_announcement_id,
    title = EXCLUDED.title,
    message = EXCLUDED.message,
    updated_at = now()
RETURNING enabled, popup_announcement_id, title, message
`

type UpsertMaintenanceAdminParams struct {
	Enabled             bool        `json:"enabled"`
	PopupAnnouncementID pgtype.Text `json:"popup_announcement_id"`
	Title               string      `json:"title"`
	Message             string      `json:"message"`
}

type UpsertMaintenanceAdminRow struct {
	Enabled             bool        `json:"enabled"`
	PopupAnnouncementID pgtype.Text `json:"popup_announcement_id"`
	Title               string      `json:"title"`
	Message             string      `json:"message"`
}

func (q *Queries) UpsertMaintenanceAdmin(ctx context.Context, arg UpsertMaintenanceAdminParams) (UpsertMaintenanceAdminRow, error) {
	row := q.db.QueryRow(ctx, upsertMaintenanceAdmin,
		arg.Enabled,
		arg.PopupAnnouncementID,
		arg.Title,
		arg.Message,
	)
	var i UpsertMaintenanceAdminRow
	err := row.Scan(
		&i.Enabled,
		&i.PopupAnnouncementID,
		&i.Title,
		&i.Message,
	)
	return i, err
}
