// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: member_lookback.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberLookbackSettings = `-- name: GetMemberLookbackSettings :one
SELECT
    member_id, run_mode, apply_formal, apply_sim, judgment,
    single_profit_threshold, single_loss_threshold,
    overall_profit_threshold, overall_loss_threshold,
    scheme_wins_min, scheme_wins_max,
    period_profit, period_loss,
    created_at, updated_at
FROM member_lookback_settings
WHERE member_id = $1
`

type GetMemberLookbackSettingsRow struct {
	MemberID               int64              `json:"member_id"`
	RunMode                string             `json:"run_mode"`
	ApplyFormal            bool               `json:"apply_formal"`
	ApplySim               bool               `json:"apply_sim"`
	Judgment               string             `json:"judgment"`
	SingleProfitThreshold  pgtype.Numeric     `json:"single_profit_threshold"`
	SingleLossThreshold    pgtype.Numeric     `json:"single_loss_threshold"`
	OverallProfitThreshold pgtype.Numeric     `json:"overall_profit_threshold"`
	OverallLossThreshold   pgtype.Numeric     `json:"overall_loss_threshold"`
	SchemeWinsMin          pgtype.Numeric     `json:"scheme_wins_min"`
	SchemeWinsMax          pgtype.Numeric     `json:"scheme_wins_max"`
	PeriodProfit           pgtype.Numeric     `json:"period_profit"`
	PeriodLoss             pgtype.Numeric     `json:"period_loss"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberLookbackSettings(ctx context.Context, memberID int64) (GetMemberLookbackSettingsRow, error) {
	row := q.db.QueryRow(ctx, getMemberLookbackSettings, memberID)
	var i GetMemberLookbackSettingsRow
	err := row.Scan(
		&i.MemberID,
		&i.RunMode,
		&i.ApplyFormal,
		&i.ApplySim,
		&i.Judgment,
		&i.SingleProfitThreshold,
		&i.SingleLossThreshold,
		&i.OverallProfitThreshold,
		&i.OverallLossThreshold,
		&i.SchemeWinsMin,
		&i.SchemeWinsMax,
		&i.PeriodProfit,
		&i.PeriodLoss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMemberLookbackSettings = `-- name: UpsertMemberLookbackSettings :one
INSERT INTO member_lookback_settings (
    member_id, run_mode, apply_formal, apply_sim, judgment,
    single_profit_threshold, single_loss_threshold,
    overall_profit_threshold, overall_loss_threshold,
    scheme_wins_min, scheme_wins_max,
    period_profit, period_loss, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now()
)
ON CONFLICT (member_id) DO UPDATE SET
    run_mode = EXCLUDED.run_mode,
    apply_formal = EXCLUDED.apply_formal,
    apply_sim = EXCLUDED.apply_sim,
    judgment = EXCLUDED.judgment,
    single_profit_threshold = EXCLUDED.single_profit_threshold,
    single_loss_threshold = EXCLUDED.single_loss_threshold,
    overall_profit_threshold = EXCLUDED.overall_profit_threshold,
    overall_loss_threshold = EXCLUDED.overall_loss_threshold,
    scheme_wins_min = EXCLUDED.scheme_wins_min,
    scheme_wins_max = EXCLUDED.scheme_wins_max,
    period_profit = EXCLUDED.period_profit,
    period_loss = EXCLUDED.period_loss,
    updated_at = now()
RETURNING
    member_id, run_mode, apply_formal, apply_sim, judgment,
    single_profit_threshold, single_loss_threshold,
    overall_profit_threshold, overall_loss_threshold,
    scheme_wins_min, scheme_wins_max,
    period_profit, period_loss,
    created_at, updated_at
`

type UpsertMemberLookbackSettingsParams struct {
	MemberID               int64          `json:"member_id"`
	RunMode                string         `json:"run_mode"`
	ApplyFormal            bool           `json:"apply_formal"`
	ApplySim               bool           `json:"apply_sim"`
	Judgment               string         `json:"judgment"`
	SingleProfitThreshold  pgtype.Numeric `json:"single_profit_threshold"`
	SingleLossThreshold    pgtype.Numeric `json:"single_loss_threshold"`
	OverallProfitThreshold pgtype.Numeric `json:"overall_profit_threshold"`
	OverallLossThreshold   pgtype.Numeric `json:"overall_loss_threshold"`
	SchemeWinsMin          pgtype.Numeric `json:"scheme_wins_min"`
	SchemeWinsMax          pgtype.Numeric `json:"scheme_wins_max"`
	PeriodProfit           pgtype.Numeric `json:"period_profit"`
	PeriodLoss             pgtype.Numeric `json:"period_loss"`
}

type UpsertMemberLookbackSettingsRow struct {
	MemberID               int64              `json:"member_id"`
	RunMode                string             `json:"run_mode"`
	ApplyFormal            bool               `json:"apply_formal"`
	ApplySim               bool               `json:"apply_sim"`
	Judgment               string             `json:"judgment"`
	SingleProfitThreshold  pgtype.Numeric     `json:"single_profit_threshold"`
	SingleLossThreshold    pgtype.Numeric     `json:"single_loss_threshold"`
	OverallProfitThreshold pgtype.Numeric     `json:"overall_profit_threshold"`
	OverallLossThreshold   pgtype.Numeric     `json:"overall_loss_threshold"`
	SchemeWinsMin          pgtype.Numeric     `json:"scheme_wins_min"`
	SchemeWinsMax          pgtype.Numeric     `json:"scheme_wins_max"`
	PeriodProfit           pgtype.Numeric     `json:"period_profit"`
	PeriodLoss             pgtype.Numeric     `json:"period_loss"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertMemberLookbackSettings(ctx context.Context, arg UpsertMemberLookbackSettingsParams) (UpsertMemberLookbackSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertMemberLookbackSettings,
		arg.MemberID,
		arg.RunMode,
		arg.ApplyFormal,
		arg.ApplySim,
		arg.Judgment,
		arg.SingleProfitThreshold,
		arg.SingleLossThreshold,
		arg.OverallProfitThreshold,
		arg.OverallLossThreshold,
		arg.SchemeWinsMin,
		arg.SchemeWinsMax,
		arg.PeriodProfit,
		arg.PeriodLoss,
	)
	var i UpsertMemberLookbackSettingsRow
	err := row.Scan(
		&i.MemberID,
		&i.RunMode,
		&i.ApplyFormal,
		&i.ApplySim,
		&i.Judgment,
		&i.SingleProfitThreshold,
		&i.SingleLossThreshold,
		&i.OverallProfitThreshold,
		&i.OverallLossThreshold,
		&i.SchemeWinsMin,
		&i.SchemeWinsMax,
		&i.PeriodProfit,
		&i.PeriodLoss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
