// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: members.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateMemberPasswordByID = `-- name: AdminUpdateMemberPasswordByID :execrows
UPDATE members
SET password_hash = $2,
    updated_at = now()
WHERE id = $1
`

type AdminUpdateMemberPasswordByIDParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) AdminUpdateMemberPasswordByID(ctx context.Context, arg AdminUpdateMemberPasswordByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateMemberPasswordByID, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateMemberStatus = `-- name: AdminUpdateMemberStatus :execrows
UPDATE members
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type AdminUpdateMemberStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) AdminUpdateMemberStatus(ctx context.Context, arg AdminUpdateMemberStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateMemberStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAdminMembers = `-- name: CountAdminMembers :one
SELECT COUNT(*)::bigint
FROM members m
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR (
        $2::text = 'guajiAccount'
        AND EXISTS (
            SELECT 1
            FROM member_guaji_accounts g
            WHERE g.member_id = m.id
              AND g.guaji_username ILIKE '%' || $1::text || '%'
        )
    )
    OR (
        $2::text = 'account'
        AND m.account ILIKE '%' || $1::text || '%'
    )
    OR (
        $2::text = 'id'
        AND m.id::text = $1::text
    )
)
`

type CountAdminMembersParams struct {
	Keyword     pgtype.Text `json:"keyword"`
	SearchField string      `json:"search_field"`
}

func (q *Queries) CountAdminMembers(ctx context.Context, arg CountAdminMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminMembers, arg.Keyword, arg.SearchField)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getMemberAccountByID = `-- name: GetMemberAccountByID :one
SELECT account FROM members WHERE id = $1
`

func (q *Queries) GetMemberAccountByID(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getMemberAccountByID, id)
	var account string
	err := row.Scan(&account)
	return account, err
}

const getMemberByAccount = `-- name: GetMemberByAccount :one
SELECT
    m.id,
    m.account,
    m.display_name,
    m.status,
    m.registered_at,
    m.last_login_at
FROM members m
WHERE m.account = $1
  AND m.status = 'active'
`

type GetMemberByAccountRow struct {
	ID           int64              `json:"id"`
	Account      string             `json:"account"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetMemberByAccount(ctx context.Context, account string) (GetMemberByAccountRow, error) {
	row := q.db.QueryRow(ctx, getMemberByAccount, account)
	var i GetMemberByAccountRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT
    m.id,
    m.account,
    m.display_name,
    m.status,
    m.registered_at,
    m.last_login_at,
    COALESCE(w.balance, 0)::float8 AS balance
FROM members m
LEFT JOIN member_wallets w ON w.member_id = m.id
WHERE m.id = $1
`

type GetMemberByIDRow struct {
	ID           int64              `json:"id"`
	Account      string             `json:"account"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	Balance      float64            `json:"balance"`
}

func (q *Queries) GetMemberByID(ctx context.Context, id int64) (GetMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i GetMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.Status,
		&i.RegisteredAt,
		&i.LastLoginAt,
		&i.Balance,
	)
	return i, err
}

const getMemberForLogin = `-- name: GetMemberForLogin :one
SELECT
    m.id,
    m.account,
    m.display_name,
    m.password_hash,
    m.status
FROM members m
WHERE m.account = $1
`

type GetMemberForLoginRow struct {
	ID           int64  `json:"id"`
	Account      string `json:"account"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	Status       string `json:"status"`
}

func (q *Queries) GetMemberForLogin(ctx context.Context, account string) (GetMemberForLoginRow, error) {
	row := q.db.QueryRow(ctx, getMemberForLogin, account)
	var i GetMemberForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
	)
	return i, err
}

const getMemberFundAuth = `-- name: GetMemberFundAuth :one
SELECT m.id, m.fund_password_hash
FROM members m
WHERE m.account = $1
  AND m.status = 'active'
`

type GetMemberFundAuthRow struct {
	ID               int64       `json:"id"`
	FundPasswordHash pgtype.Text `json:"fund_password_hash"`
}

func (q *Queries) GetMemberFundAuth(ctx context.Context, account string) (GetMemberFundAuthRow, error) {
	row := q.db.QueryRow(ctx, getMemberFundAuth, account)
	var i GetMemberFundAuthRow
	err := row.Scan(&i.ID, &i.FundPasswordHash)
	return i, err
}

const getMemberProfileByAccount = `-- name: GetMemberProfileByAccount :one
SELECT
    m.id,
    m.account,
    m.display_name,
    w.balance::float8 AS balance,
    w.frozen_balance::float8 AS frozen_balance,
    w.currency,
    (m.fund_password_hash IS NOT NULL) AS has_fund_password
FROM members m
JOIN member_wallets w ON w.member_id = m.id
WHERE m.account = $1
  AND m.status = 'active'
`

type GetMemberProfileByAccountRow struct {
	ID              int64       `json:"id"`
	Account         string      `json:"account"`
	DisplayName     string      `json:"display_name"`
	Balance         float64     `json:"balance"`
	FrozenBalance   float64     `json:"frozen_balance"`
	Currency        string      `json:"currency"`
	HasFundPassword interface{} `json:"has_fund_password"`
}

func (q *Queries) GetMemberProfileByAccount(ctx context.Context, account string) (GetMemberProfileByAccountRow, error) {
	row := q.db.QueryRow(ctx, getMemberProfileByAccount, account)
	var i GetMemberProfileByAccountRow
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.DisplayName,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.HasFundPassword,
	)
	return i, err
}

const getMemberWalletByMemberID = `-- name: GetMemberWalletByMemberID :one
SELECT
    w.balance::float8 AS balance,
    w.frozen_balance::float8 AS frozen_balance,
    w.currency,
    w.version,
    w.updated_at
FROM member_wallets w
WHERE w.member_id = $1
`

type GetMemberWalletByMemberIDRow struct {
	Balance       float64            `json:"balance"`
	FrozenBalance float64            `json:"frozen_balance"`
	Currency      string             `json:"currency"`
	Version       int64              `json:"version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberWalletByMemberID(ctx context.Context, memberID int64) (GetMemberWalletByMemberIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberWalletByMemberID, memberID)
	var i GetMemberWalletByMemberIDRow
	err := row.Scan(
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletLedgerCursorAnchor = `-- name: GetWalletLedgerCursorAnchor :one
SELECT l.created_at, l.id
FROM wallet_ledger l
WHERE l.member_id = $1
  AND l.ledger_no = $2
`

type GetWalletLedgerCursorAnchorParams struct {
	MemberID int64  `json:"member_id"`
	LedgerNo string `json:"ledger_no"`
}

type GetWalletLedgerCursorAnchorRow struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ID        int64              `json:"id"`
}

func (q *Queries) GetWalletLedgerCursorAnchor(ctx context.Context, arg GetWalletLedgerCursorAnchorParams) (GetWalletLedgerCursorAnchorRow, error) {
	row := q.db.QueryRow(ctx, getWalletLedgerCursorAnchor, arg.MemberID, arg.LedgerNo)
	var i GetWalletLedgerCursorAnchorRow
	err := row.Scan(&i.CreatedAt, &i.ID)
	return i, err
}

const listAdminMembers = `-- name: ListAdminMembers :many
SELECT
    m.id,
    m.account,
    m.display_name,
    m.status,
    m.registered_at,
    m.last_login_at
FROM members m
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR (
        $2::text = 'guajiAccount'
        AND EXISTS (
            SELECT 1
            FROM member_guaji_accounts g
            WHERE g.member_id = m.id
              AND g.guaji_username ILIKE '%' || $1::text || '%'
        )
    )
    OR (
        $2::text = 'account'
        AND m.account ILIKE '%' || $1::text || '%'
    )
    OR (
        $2::text = 'id'
        AND m.id::text = $1::text
    )
)
ORDER BY m.registered_at DESC, m.id DESC
LIMIT $4 OFFSET $3
`

type ListAdminMembersParams struct {
	Keyword     pgtype.Text `json:"keyword"`
	SearchField string      `json:"search_field"`
	RowOffset   int32       `json:"row_offset"`
	RowLimit    int32       `json:"row_limit"`
}

type ListAdminMembersRow struct {
	ID           int64              `json:"id"`
	Account      string             `json:"account"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListAdminMembers(ctx context.Context, arg ListAdminMembersParams) ([]ListAdminMembersRow, error) {
	rows, err := q.db.Query(ctx, listAdminMembers,
		arg.Keyword,
		arg.SearchField,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminMembersRow{}
	for rows.Next() {
		var i ListAdminMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.DisplayName,
			&i.Status,
			&i.RegisteredAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletLedger = `-- name: ListWalletLedger :many
SELECT
    l.id,
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.order_ref, '') AS order_ref,
    l.created_at
FROM wallet_ledger l
WHERE l.member_id = $1
  AND l.created_at >= $2
  AND l.created_at < $3
  AND (
    $4::text IS NULL
    OR l.txn_type = $4::text
  )
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR l.order_ref ILIKE '%' || $5::text || '%'
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $6
`

type ListWalletLedgerParams struct {
	MemberID int64              `json:"member_id"`
	TimeFrom pgtype.Timestamptz `json:"time_from"`
	TimeTo   pgtype.Timestamptz `json:"time_to"`
	TxnType  pgtype.Text        `json:"txn_type"`
	OrderRef pgtype.Text        `json:"order_ref"`
	RowLimit int32              `json:"row_limit"`
}

type ListWalletLedgerRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	OrderRef     string             `json:"order_ref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletLedger(ctx context.Context, arg ListWalletLedgerParams) ([]ListWalletLedgerRow, error) {
	rows, err := q.db.Query(ctx, listWalletLedger,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.TxnType,
		arg.OrderRef,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletLedgerRow{}
	for rows.Next() {
		var i ListWalletLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.OrderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletLedgerAdmin = `-- name: ListWalletLedgerAdmin :many
SELECT
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.order_ref, '') AS order_ref,
    l.created_at
FROM wallet_ledger l
WHERE l.member_id = $1
  AND (
    $2::text IS NULL
    OR $2::text = ''
    OR l.txn_type = $2::text
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $3
`

type ListWalletLedgerAdminParams struct {
	MemberID int64       `json:"member_id"`
	TxnType  pgtype.Text `json:"txn_type"`
	RowLimit int32       `json:"row_limit"`
}

type ListWalletLedgerAdminRow struct {
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	OrderRef     string             `json:"order_ref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletLedgerAdmin(ctx context.Context, arg ListWalletLedgerAdminParams) ([]ListWalletLedgerAdminRow, error) {
	rows, err := q.db.Query(ctx, listWalletLedgerAdmin, arg.MemberID, arg.TxnType, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletLedgerAdminRow{}
	for rows.Next() {
		var i ListWalletLedgerAdminRow
		if err := rows.Scan(
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.OrderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletLedgerAfterCursor = `-- name: ListWalletLedgerAfterCursor :many
SELECT
    l.id,
    l.ledger_no,
    l.txn_type,
    l.delta_amount::float8 AS delta_amount,
    l.balance_after::float8 AS balance_after,
    COALESCE(l.order_ref, '') AS order_ref,
    l.created_at
FROM wallet_ledger l
WHERE l.member_id = $1
  AND l.created_at >= $2
  AND l.created_at < $3
  AND (
    $4::text IS NULL
    OR l.txn_type = $4::text
  )
  AND (
    $5::text IS NULL
    OR $5::text = ''
    OR l.order_ref ILIKE '%' || $5::text || '%'
  )
  AND (
    l.created_at < $6
    OR (l.created_at = $6 AND l.id < $7)
  )
ORDER BY l.created_at DESC, l.id DESC
LIMIT $8
`

type ListWalletLedgerAfterCursorParams struct {
	MemberID   int64              `json:"member_id"`
	TimeFrom   pgtype.Timestamptz `json:"time_from"`
	TimeTo     pgtype.Timestamptz `json:"time_to"`
	TxnType    pgtype.Text        `json:"txn_type"`
	OrderRef   pgtype.Text        `json:"order_ref"`
	CursorTime pgtype.Timestamptz `json:"cursor_time"`
	CursorID   int64              `json:"cursor_id"`
	RowLimit   int32              `json:"row_limit"`
}

type ListWalletLedgerAfterCursorRow struct {
	ID           int64              `json:"id"`
	LedgerNo     string             `json:"ledger_no"`
	TxnType      string             `json:"txn_type"`
	DeltaAmount  float64            `json:"delta_amount"`
	BalanceAfter float64            `json:"balance_after"`
	OrderRef     string             `json:"order_ref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletLedgerAfterCursor(ctx context.Context, arg ListWalletLedgerAfterCursorParams) ([]ListWalletLedgerAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listWalletLedgerAfterCursor,
		arg.MemberID,
		arg.TimeFrom,
		arg.TimeTo,
		arg.TxnType,
		arg.OrderRef,
		arg.CursorTime,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletLedgerAfterCursorRow{}
	for rows.Next() {
		var i ListWalletLedgerAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerNo,
			&i.TxnType,
			&i.DeltaAmount,
			&i.BalanceAfter,
			&i.OrderRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemberFundPassword = `-- name: SetMemberFundPassword :execrows
UPDATE members
SET fund_password_hash = $2,
    updated_at = now()
WHERE id = $1
`

type SetMemberFundPasswordParams struct {
	ID               int64       `json:"id"`
	FundPasswordHash pgtype.Text `json:"fund_password_hash"`
}

func (q *Queries) SetMemberFundPassword(ctx context.Context, arg SetMemberFundPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberFundPassword, arg.ID, arg.FundPasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMemberLastLogin = `-- name: TouchMemberLastLogin :exec
UPDATE members
SET last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchMemberLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchMemberLastLogin, id)
	return err
}
