// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: member_lookback_runtime.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberLookbackRuntime = `-- name: GetMemberLookbackRuntime :one

SELECT member_id, sim_bet, session_pnl, period_issue, period_pnl, period_hit_count, total_hit_count, updated_at

FROM member_lookback_runtime

WHERE member_id = $1 AND sim_bet = $2
`

type GetMemberLookbackRuntimeParams struct {
	MemberID int64 `json:"member_id"`
	SimBet   bool  `json:"sim_bet"`
}

type GetMemberLookbackRuntimeRow struct {
	MemberID       int64              `json:"member_id"`
	SimBet         bool               `json:"sim_bet"`
	SessionPnl     pgtype.Numeric     `json:"session_pnl"`
	PeriodIssue    string             `json:"period_issue"`
	PeriodPnl      pgtype.Numeric     `json:"period_pnl"`
	PeriodHitCount int32              `json:"period_hit_count"`
	TotalHitCount  int32              `json:"total_hit_count"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberLookbackRuntime(ctx context.Context, arg GetMemberLookbackRuntimeParams) (GetMemberLookbackRuntimeRow, error) {
	row := q.db.QueryRow(ctx, getMemberLookbackRuntime, arg.MemberID, arg.SimBet)
	var i GetMemberLookbackRuntimeRow
	err := row.Scan(
		&i.MemberID,
		&i.SimBet,
		&i.SessionPnl,
		&i.PeriodIssue,
		&i.PeriodPnl,
		&i.PeriodHitCount,
		&i.TotalHitCount,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunningSchemeInstanceIDsByMemberSimBet = `-- name: ListRunningSchemeInstanceIDsByMemberSimBet :many

SELECT id FROM scheme_instances

WHERE member_id = $1 AND sim_bet = $2 AND status = 'running'
`

type ListRunningSchemeInstanceIDsByMemberSimBetParams struct {
	MemberID int64 `json:"member_id"`
	SimBet   bool  `json:"sim_bet"`
}

func (q *Queries) ListRunningSchemeInstanceIDsByMemberSimBet(ctx context.Context, arg ListRunningSchemeInstanceIDsByMemberSimBetParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRunningSchemeInstanceIDsByMemberSimBet, arg.MemberID, arg.SimBet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMemberLookbackRuntime = `-- name: ResetMemberLookbackRuntime :one

UPDATE member_lookback_runtime

SET session_pnl = 0, period_pnl = 0, period_hit_count = 0, total_hit_count = 0, updated_at = now()

WHERE member_id = $1 AND sim_bet = $2

RETURNING member_id, sim_bet, session_pnl, period_issue, period_pnl, period_hit_count, total_hit_count, updated_at
`

type ResetMemberLookbackRuntimeParams struct {
	MemberID int64 `json:"member_id"`
	SimBet   bool  `json:"sim_bet"`
}

type ResetMemberLookbackRuntimeRow struct {
	MemberID       int64              `json:"member_id"`
	SimBet         bool               `json:"sim_bet"`
	SessionPnl     pgtype.Numeric     `json:"session_pnl"`
	PeriodIssue    string             `json:"period_issue"`
	PeriodPnl      pgtype.Numeric     `json:"period_pnl"`
	PeriodHitCount int32              `json:"period_hit_count"`
	TotalHitCount  int32              `json:"total_hit_count"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResetMemberLookbackRuntime(ctx context.Context, arg ResetMemberLookbackRuntimeParams) (ResetMemberLookbackRuntimeRow, error) {
	row := q.db.QueryRow(ctx, resetMemberLookbackRuntime, arg.MemberID, arg.SimBet)
	var i ResetMemberLookbackRuntimeRow
	err := row.Scan(
		&i.MemberID,
		&i.SimBet,
		&i.SessionPnl,
		&i.PeriodIssue,
		&i.PeriodPnl,
		&i.PeriodHitCount,
		&i.TotalHitCount,
		&i.UpdatedAt,
	)
	return i, err
}

const resetSchemeInstanceLookbackRound = `-- name: ResetSchemeInstanceLookbackRound :one
-- 仅归零倍投轮次/回头盈亏；保留出号游标（定码轮换/高级定码轮换跳局）

UPDATE scheme_instances

SET round_index = 0,

    multiplier = $2,

    lookback_pnl = 0,

    updated_at = now()

WHERE id = $1

  AND status = 'running'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    round_index, last_settled_issue,

    created_at, updated_at
`

type ResetSchemeInstanceLookbackRoundParams struct {
	ID         string         `json:"id"`
	Multiplier pgtype.Numeric `json:"multiplier"`
}

type ResetSchemeInstanceLookbackRoundRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	RoundIndex       int32              `json:"round_index"`
	LastSettledIssue pgtype.Text        `json:"last_settled_issue"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResetSchemeInstanceLookbackRound(ctx context.Context, arg ResetSchemeInstanceLookbackRoundParams) (ResetSchemeInstanceLookbackRoundRow, error) {
	row := q.db.QueryRow(ctx, resetSchemeInstanceLookbackRound, arg.ID, arg.Multiplier)
	var i ResetSchemeInstanceLookbackRoundRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RoundIndex,
		&i.LastSettledIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMemberLookbackRuntime = `-- name: UpsertMemberLookbackRuntime :one

INSERT INTO member_lookback_runtime (

    member_id, sim_bet, session_pnl, period_issue, period_pnl, period_hit_count, total_hit_count, updated_at

) VALUES ($1, $2, $3, $4, $5, $6, $7, now())

ON CONFLICT (member_id, sim_bet) DO UPDATE SET

    session_pnl = EXCLUDED.session_pnl,

    period_issue = EXCLUDED.period_issue,

    period_pnl = EXCLUDED.period_pnl,

    period_hit_count = EXCLUDED.period_hit_count,

    total_hit_count = EXCLUDED.total_hit_count,

    updated_at = now()

RETURNING member_id, sim_bet, session_pnl, period_issue, period_pnl, period_hit_count, total_hit_count, updated_at
`

type UpsertMemberLookbackRuntimeParams struct {
	MemberID       int64          `json:"member_id"`
	SimBet         bool           `json:"sim_bet"`
	SessionPnl     pgtype.Numeric `json:"session_pnl"`
	PeriodIssue    string         `json:"period_issue"`
	PeriodPnl      pgtype.Numeric `json:"period_pnl"`
	PeriodHitCount int32          `json:"period_hit_count"`
	TotalHitCount  int32          `json:"total_hit_count"`
}

type UpsertMemberLookbackRuntimeRow struct {
	MemberID       int64              `json:"member_id"`
	SimBet         bool               `json:"sim_bet"`
	SessionPnl     pgtype.Numeric     `json:"session_pnl"`
	PeriodIssue    string             `json:"period_issue"`
	PeriodPnl      pgtype.Numeric     `json:"period_pnl"`
	PeriodHitCount int32              `json:"period_hit_count"`
	TotalHitCount  int32              `json:"total_hit_count"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertMemberLookbackRuntime(ctx context.Context, arg UpsertMemberLookbackRuntimeParams) (UpsertMemberLookbackRuntimeRow, error) {
	row := q.db.QueryRow(ctx, upsertMemberLookbackRuntime,
		arg.MemberID,
		arg.SimBet,
		arg.SessionPnl,
		arg.PeriodIssue,
		arg.PeriodPnl,
		arg.PeriodHitCount,
		arg.TotalHitCount,
	)
	var i UpsertMemberLookbackRuntimeRow
	err := row.Scan(
		&i.MemberID,
		&i.SimBet,
		&i.SessionPnl,
		&i.PeriodIssue,
		&i.PeriodPnl,
		&i.PeriodHitCount,
		&i.TotalHitCount,
		&i.UpdatedAt,
	)
	return i, err
}
