// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: member_guaji_accounts.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateMemberGuajiAccount = `-- name: ActivateMemberGuajiAccount :one
UPDATE member_guaji_accounts
SET is_active = true,
    last_token_error = NULL,
    updated_at = now()
WHERE id = $1 AND member_id = $2
RETURNING
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
`

type ActivateMemberGuajiAccountParams struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"member_id"`
}

type ActivateMemberGuajiAccountRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ActivateMemberGuajiAccount(ctx context.Context, arg ActivateMemberGuajiAccountParams) (ActivateMemberGuajiAccountRow, error) {
	row := q.db.QueryRow(ctx, activateMemberGuajiAccount, arg.ID, arg.MemberID)
	var i ActivateMemberGuajiAccountRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMemberGuajiAccounts = `-- name: CountMemberGuajiAccounts :one
SELECT COUNT(*)::bigint AS count
FROM member_guaji_accounts
WHERE member_id = $1
`

func (q *Queries) CountMemberGuajiAccounts(ctx context.Context, memberID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberGuajiAccounts, memberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateAllMemberGuajiAccounts = `-- name: DeactivateAllMemberGuajiAccounts :exec
UPDATE member_guaji_accounts
SET is_active = false, updated_at = now()
WHERE member_id = $1 AND is_active = true
`

func (q *Queries) DeactivateAllMemberGuajiAccounts(ctx context.Context, memberID int64) error {
	_, err := q.db.Exec(ctx, deactivateAllMemberGuajiAccounts, memberID)
	return err
}

const deleteMemberGuajiAccount = `-- name: DeleteMemberGuajiAccount :execrows
DELETE FROM member_guaji_accounts
WHERE id = $1 AND member_id = $2
`

type DeleteMemberGuajiAccountParams struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"member_id"`
}

func (q *Queries) DeleteMemberGuajiAccount(ctx context.Context, arg DeleteMemberGuajiAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemberGuajiAccount, arg.ID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAllMemberGuajiAccountsByMemberID = `-- name: DeleteAllMemberGuajiAccountsByMemberID :execrows
DELETE FROM member_guaji_accounts
WHERE member_id = $1
`

func (q *Queries) DeleteAllMemberGuajiAccountsByMemberID(ctx context.Context, memberID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllMemberGuajiAccountsByMemberID, memberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveMemberGuajiAccount = `-- name: GetActiveMemberGuajiAccount :one
SELECT
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
FROM member_guaji_accounts
WHERE member_id = $1 AND is_active = true
LIMIT 1
`

type GetActiveMemberGuajiAccountRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveMemberGuajiAccount(ctx context.Context, memberID int64) (GetActiveMemberGuajiAccountRow, error) {
	row := q.db.QueryRow(ctx, getActiveMemberGuajiAccount, memberID)
	var i GetActiveMemberGuajiAccountRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberGuajiAccountByIDAndMember = `-- name: GetMemberGuajiAccountByIDAndMember :one
SELECT
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
FROM member_guaji_accounts
WHERE id = $1 AND member_id = $2
`

type GetMemberGuajiAccountByIDAndMemberParams struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"member_id"`
}

type GetMemberGuajiAccountByIDAndMemberRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberGuajiAccountByIDAndMember(ctx context.Context, arg GetMemberGuajiAccountByIDAndMemberParams) (GetMemberGuajiAccountByIDAndMemberRow, error) {
	row := q.db.QueryRow(ctx, getMemberGuajiAccountByIDAndMember, arg.ID, arg.MemberID)
	var i GetMemberGuajiAccountByIDAndMemberRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberGuajiAccountByUsername = `-- name: GetMemberGuajiAccountByUsername :one
SELECT
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
FROM member_guaji_accounts
WHERE guaji_username = $1
`

type GetMemberGuajiAccountByUsernameRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberGuajiAccountByUsername(ctx context.Context, guajiUsername string) (GetMemberGuajiAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getMemberGuajiAccountByUsername, guajiUsername)
	var i GetMemberGuajiAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemberGuajiAccount = `-- name: InsertMemberGuajiAccount :one
INSERT INTO member_guaji_accounts (
    member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), $9, NULL
)
RETURNING
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
`

type InsertMemberGuajiAccountParams struct {
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
}

type InsertMemberGuajiAccountRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertMemberGuajiAccount(ctx context.Context, arg InsertMemberGuajiAccountParams) (InsertMemberGuajiAccountRow, error) {
	row := q.db.QueryRow(ctx, insertMemberGuajiAccount,
		arg.MemberID,
		arg.GuajiUsername,
		arg.PasswordEnc,
		arg.MfaMaterialEnc,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
		arg.IsActive,
		arg.LastSyncAt,
	)
	var i InsertMemberGuajiAccountRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGuajiBalancesByMemberIDs = `-- name: ListActiveGuajiBalancesByMemberIDs :many
SELECT
    member_id,
    balance_usdt::float8 AS balance_usdt,
    balance_trx::float8 AS balance_trx,
    balance_cny::float8 AS balance_cny
FROM member_guaji_accounts
WHERE member_id = ANY($1::bigint[])
  AND is_active = true
`

type ListActiveGuajiBalancesByMemberIDsRow struct {
	MemberID    int64   `json:"member_id"`
	BalanceUsdt float64 `json:"balance_usdt"`
	BalanceTrx  float64 `json:"balance_trx"`
	BalanceCny  float64 `json:"balance_cny"`
}

func (q *Queries) ListActiveGuajiBalancesByMemberIDs(ctx context.Context, dollar_1 []int64) ([]ListActiveGuajiBalancesByMemberIDsRow, error) {
	rows, err := q.db.Query(ctx, listActiveGuajiBalancesByMemberIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGuajiBalancesByMemberIDsRow{}
	for rows.Next() {
		var i ListActiveGuajiBalancesByMemberIDsRow
		if err := rows.Scan(
			&i.MemberID,
			&i.BalanceUsdt,
			&i.BalanceTrx,
			&i.BalanceCny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberGuajiAccountsAdmin = `-- name: ListMemberGuajiAccountsAdmin :many
SELECT
    id, member_id, guaji_username, is_active, bound_at, last_sync_at,
    last_token_error, last_bet_at, created_at, updated_at
FROM member_guaji_accounts
WHERE member_id = $1
ORDER BY is_active DESC, bound_at DESC
`

type ListMemberGuajiAccountsAdminRow struct {
	ID             int64              `json:"id"`
	MemberID       int64              `json:"member_id"`
	GuajiUsername  string             `json:"guaji_username"`
	IsActive       bool               `json:"is_active"`
	BoundAt        pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt     pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError pgtype.Text        `json:"last_token_error"`
	LastBetAt      pgtype.Timestamptz `json:"last_bet_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMemberGuajiAccountsAdmin(ctx context.Context, memberID int64) ([]ListMemberGuajiAccountsAdminRow, error) {
	rows, err := q.db.Query(ctx, listMemberGuajiAccountsAdmin, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberGuajiAccountsAdminRow{}
	for rows.Next() {
		var i ListMemberGuajiAccountsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.GuajiUsername,
			&i.IsActive,
			&i.BoundAt,
			&i.LastSyncAt,
			&i.LastTokenError,
			&i.LastBetAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberGuajiAccountsByMember = `-- name: ListMemberGuajiAccountsByMember :many
SELECT
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
FROM member_guaji_accounts
WHERE member_id = $1
ORDER BY is_active DESC, bound_at DESC
`

type ListMemberGuajiAccountsByMemberRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMemberGuajiAccountsByMember(ctx context.Context, memberID int64) ([]ListMemberGuajiAccountsByMemberRow, error) {
	rows, err := q.db.Query(ctx, listMemberGuajiAccountsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberGuajiAccountsByMemberRow{}
	for rows.Next() {
		var i ListMemberGuajiAccountsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.GuajiUsername,
			&i.PasswordEnc,
			&i.MfaMaterialEnc,
			&i.AccessTokenEnc,
			&i.RefreshTokenEnc,
			&i.TokenExpiresAt,
			&i.IsActive,
			&i.BoundAt,
			&i.LastSyncAt,
			&i.LastTokenError,
			&i.LastBetAt,
			&i.ReauthFailCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberGuajiAccountBalances = `-- name: UpdateMemberGuajiAccountBalances :exec
UPDATE member_guaji_accounts
SET balance_usdt = $2,
    balance_trx = $3,
    balance_cny = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateMemberGuajiAccountBalancesParams struct {
	ID          int64          `json:"id"`
	BalanceUsdt pgtype.Numeric `json:"balance_usdt"`
	BalanceTrx  pgtype.Numeric `json:"balance_trx"`
	BalanceCny  pgtype.Numeric `json:"balance_cny"`
}

func (q *Queries) UpdateMemberGuajiAccountBalances(ctx context.Context, arg UpdateMemberGuajiAccountBalancesParams) error {
	_, err := q.db.Exec(ctx, updateMemberGuajiAccountBalances,
		arg.ID,
		arg.BalanceUsdt,
		arg.BalanceTrx,
		arg.BalanceCny,
	)
	return err
}

const updateMemberGuajiAccountMFAMaterial = `-- name: UpdateMemberGuajiAccountMFAMaterial :exec
UPDATE member_guaji_accounts
SET mfa_material_enc = $3,
    updated_at = now()
WHERE id = $1 AND member_id = $2
`

type UpdateMemberGuajiAccountMFAMaterialParams struct {
	ID             int64       `json:"id"`
	MemberID       int64       `json:"member_id"`
	MfaMaterialEnc pgtype.Text `json:"mfa_material_enc"`
}

func (q *Queries) UpdateMemberGuajiAccountMFAMaterial(ctx context.Context, arg UpdateMemberGuajiAccountMFAMaterialParams) error {
	_, err := q.db.Exec(ctx, updateMemberGuajiAccountMFAMaterial, arg.ID, arg.MemberID, arg.MfaMaterialEnc)
	return err
}

const updateMemberGuajiAccountTokenError = `-- name: UpdateMemberGuajiAccountTokenError :exec
UPDATE member_guaji_accounts
SET last_token_error = $3,
    reauth_fail_count = reauth_fail_count + 1,
    updated_at = now()
WHERE id = $1 AND member_id = $2
`

type UpdateMemberGuajiAccountTokenErrorParams struct {
	ID             int64       `json:"id"`
	MemberID       int64       `json:"member_id"`
	LastTokenError pgtype.Text `json:"last_token_error"`
}

func (q *Queries) UpdateMemberGuajiAccountTokenError(ctx context.Context, arg UpdateMemberGuajiAccountTokenErrorParams) error {
	_, err := q.db.Exec(ctx, updateMemberGuajiAccountTokenError, arg.ID, arg.MemberID, arg.LastTokenError)
	return err
}

const updateMemberGuajiAccountTokens = `-- name: UpdateMemberGuajiAccountTokens :one
UPDATE member_guaji_accounts
SET access_token_enc = $3,
    refresh_token_enc = $4,
    token_expires_at = $5,
    last_sync_at = now(),
    last_token_error = NULL,
    reauth_fail_count = 0,
    updated_at = now()
WHERE id = $1 AND member_id = $2
RETURNING
    id, member_id, guaji_username, password_enc, mfa_material_enc,
    access_token_enc, refresh_token_enc, token_expires_at, is_active,
    bound_at, last_sync_at, last_token_error, last_bet_at, reauth_fail_count,
    created_at, updated_at
`

type UpdateMemberGuajiAccountTokensParams struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
}

type UpdateMemberGuajiAccountTokensRow struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMemberGuajiAccountTokens(ctx context.Context, arg UpdateMemberGuajiAccountTokensParams) (UpdateMemberGuajiAccountTokensRow, error) {
	row := q.db.QueryRow(ctx, updateMemberGuajiAccountTokens,
		arg.ID,
		arg.MemberID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.TokenExpiresAt,
	)
	var i UpdateMemberGuajiAccountTokensRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GuajiUsername,
		&i.PasswordEnc,
		&i.MfaMaterialEnc,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.TokenExpiresAt,
		&i.IsActive,
		&i.BoundAt,
		&i.LastSyncAt,
		&i.LastTokenError,
		&i.LastBetAt,
		&i.ReauthFailCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
