// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 后台操作审计留痕
type AdminAuditLog struct {
	ID string `json:"id"`
	// 操作者账号（admin 登录名）
	Actor string `json:"actor"`
	// 动作描述
	Action string `json:"action"`
	// 来源 IP
	Ip        string             `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Admin 角色 RBAC：菜单 path 前缀白名单
type AdminRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// 可见菜单 path 数组；「/」表示全部
	MenuPaths []byte             `json:"menu_paths"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Admin 后台账号；登录后角色由 role_id 绑定，不再前端自选
type AdminUser struct {
	ID int64 `json:"id"`
	// 登录账号
	Account string `json:"account"`
	// 登录密码 bcrypt 哈希
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	// 绑定角色，关联 admin_roles.id
	RoleID string `json:"role_id"`
	// active=正常 disabled=停用
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// 会员投注订单表：全站投注记录（区别于云端方案近 N 日汇总）
type BetOrder struct {
	// 主键
	ID int64 `json:"id"`
	// 投注单号，全局唯一
	OrderNo string `json:"order_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 彩种编码（对内，如 tencent_ffc）
	LotteryCode string `json:"lottery_code"`
	// 彩种展示名称（对外，如 时时彩 A）
	LotteryName string `json:"lottery_name"`
	// 彩种大类：ssc=时时彩，pk10=PK10，k3=快三，x5=11选5，other=其他
	LotteryCategory string `json:"lottery_category"`
	// 投注期号
	IssueNo string `json:"issue_no"`
	// 投注金额（元，2 位小数）
	Amount pgtype.Numeric `json:"amount"`
	// 结算盈亏（元，2 位小数；未开奖为 0）
	Pnl pgtype.Numeric `json:"pnl"`
	// 状态：pending=未开奖，win=已中奖，lose=未中奖，cancel=已撤单
	Status string `json:"status"`
	// 投注时间（UTC）
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
	// 结算时间（UTC）；未开奖/撤单为 NULL
	SettledAt pgtype.Timestamptz `json:"settled_at"`
	// 记录创建时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 玩法展示名（如 定位胆万位），供结算引擎解析
	PlayMethod pgtype.Text `json:"play_method"`
	// 结算用 JSON：groupContent / playTypeId / subPlayId 等
	BetPayload []byte `json:"bet_payload"`
	// 下单时第三方彩种对接码快照（C41）
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
	// 下单时第三方玩法对接码快照 template:type_id:sub_id（C43）
	OutboundPlayCode pgtype.Text `json:"outbound_play_code"`
	// 下单时启用的第三方授权账号 id（real；sim/本地为 NULL）
	GuajiAccountID pgtype.Int8 `json:"guaji_account_id"`
	// 第三方 web_bets/lott 接单返回的注单号（real）
	ThirdPartyBetID pgtype.Text `json:"third_party_bet_id"`
	// 下单时主币种快照 USDT/TRX/CNY（real）
	Currency pgtype.Text `json:"currency"`
}

// 会员追号订单表：按期数追投记录
type ChaseOrder struct {
	// 主键
	ID int64 `json:"id"`
	// 追号单号，全局唯一
	ChaseNo string `json:"chase_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 彩种编码（对内）
	LotteryCode string `json:"lottery_code"`
	// 彩种展示名称（对外）
	LotteryName string `json:"lottery_name"`
	// 彩种大类：ssc、pk10、k3、x5、other
	LotteryCategory string `json:"lottery_category"`
	// 追号总期数
	TotalIssues int32 `json:"total_issues"`
	// 已完成期数
	DoneIssues int32 `json:"done_issues"`
	// 追号总金额（元，2 位小数）
	Amount pgtype.Numeric `json:"amount"`
	// 状态：running=追号中，completed=已完成，cancelled=已取消
	Status string `json:"status"`
	// 追号开始时间（UTC）
	StartedAt pgtype.Timestamptz `json:"started_at"`
	// 追号结束时间（UTC）；进行中为 NULL
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// 记录创建时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 云端方案投注明细：按会员+方案聚合展示（BetRecordsView / 云端近 N 日）
type CloudBetRecord struct {
	// 主键
	ID int64 `json:"id"`
	// 明细编号，全局唯一
	RecordNo string `json:"record_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 云端方案 ID（实例/方案标识）
	SchemeID string `json:"scheme_id"`
	// 方案展示名称
	SchemeName string `json:"scheme_name"`
	// 期号
	PeriodNo string `json:"period_no"`
	// 玩法类型（如 万位定位）
	PlayType string `json:"play_type"`
	// 倍数展示文本
	Multiplier string `json:"multiplier"`
	// 轮次展示（如 1/3）
	RoundLabel string `json:"round_label"`
	// 投注金额（元，2 位小数）
	Amount pgtype.Numeric `json:"amount"`
	// 盈亏（元，2 位小数；负数为亏损）
	Pnl pgtype.Numeric `json:"pnl"`
	// 结果：hit=中，miss=未中
	Status string `json:"status"`
	// 投注时间（UTC）
	PlacedAt pgtype.Timestamptz `json:"placed_at"`
	// 记录创建时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 实际下注号码内容（多行按位，与方案内容同格式）
	BetContent string `json:"bet_content"`
	// real 投注明细关联的第三方授权账号 id；sim 为 NULL
	GuajiAccountID pgtype.Int8 `json:"guaji_account_id"`
	// 第三方 web_bets 注单编号（real）
	ThirdPartyBetID pgtype.Text `json:"third_party_bet_id"`
	// 本平台 bet_orders.order_no，派奖同步回写 cloud 状态
	BetOrderNo pgtype.Text `json:"bet_order_no"`
	// 第三方 web_bets/lott 接单返回的 periods（real）
	ThirdPartyPeriod pgtype.Text `json:"third_party_period"`
	SimBet           bool        `json:"sim_bet"`
}

// 平台公告（会员端列表/详情）
type CmsAnnouncement struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	// draft=草稿 published=已发布
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	// 富文本正文 HTML
	BodyHtml  string             `json:"body_html"`
	Pinned    bool               `json:"pinned"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 会员端联系客服配置（Admin 维护）
type CmsCustomerServiceAgent struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// Telegram 链接或 @用户名
	TgLink string `json:"tg_link"`
	// 上班时间说明
	WorkHours string             `json:"work_hours"`
	Sort      int32              `json:"sort"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 常见问题条目
type CmsFaqArticle struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Sort      int32              `json:"sort"`
	BodyHtml  string             `json:"body_html"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 帮助中心折叠条目
type CmsHelpArticle struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	Sort      int32              `json:"sort"`
	BodyHtml  string             `json:"body_html"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 游戏大厅运营位配置
type CmsLobbySlot struct {
	ID string `json:"id"`
	// 运营位唯一键，如 hero_main
	SlotKey string `json:"slot_key"`
	Title   string `json:"title"`
	// 运营说明/占位文案
	Brief     string             `json:"brief"`
	Sort      int32              `json:"sort"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 全站维护开关（单例，id=default）
type CmsMaintenance struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
	// 维护弹窗关联的已发布公告 id
	PopupAnnouncementID pgtype.Text        `json:"popup_announcement_id"`
	Title               string             `json:"title"`
	Message             string             `json:"message"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// 推广与渠道全局配置（单例 id=default）
type CmsPromoChannel struct {
	ID                 string             `json:"id"`
	DefaultMaterial    string             `json:"default_material"`
	InviteCodeRequired bool               `json:"invite_code_required"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// 站点品牌配置（单例，id=default）
type CmsSiteBrand struct {
	ID string `json:"id"`
	// 站点名称
	SiteName string `json:"site_name"`
	// Logo 图片 URL
	LogoUrl string `json:"logo_url"`
	// 一句话介绍
	Tagline   string             `json:"tagline"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 跟单大厅榜单 Top10（大神榜/反买榜，按彩种）
type CopyHallRankSlot struct {
	ID int64 `json:"id"`
	// 彩种 code，如 tencent_ffc
	LotteryCode string `json:"lottery_code"`
	// 榜单类型：master 大神榜 / contrary 反买榜
	BoardKind string `json:"board_kind"`
	// 名次 1–10
	Rank int32 `json:"rank"`
	// 方案/快照 ID（跟单入口）
	SchemeID string `json:"scheme_id"`
	// 方案展示名
	SchemeName string `json:"scheme_name"`
	// 玩法展示，如定位胆万位
	PlayMethod string             `json:"play_method"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// 玩法段 ID：dingwei / hou4 / qian3 / zhong3
	PlayTypeID string `json:"play_type_id"`
	// 子玩法 ID：zhixuan_fs / zhixuan_ds / zuxuan_fs；定位胆可为空
	SubPlayID string `json:"sub_play_id"`
}

// 彩种目录：code 创建后不可变，对外展示名与详情别名可运营
type LotteryCatalog struct {
	// 对内稳定 code，如 tencent_ffc
	Code string `json:"code"`
	// 对外中文展示名
	DisplayName string `json:"display_name"`
	// 列表排序，升序
	SortOrder int32 `json:"sort_order"`
	// 是否在售
	OnSale    bool               `json:"on_sale"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 大类：ffc/jisu/lhc/syxw/pk10/k3/ssc/pc28
	CategoryCode pgtype.Text `json:"category_code"`
	// 玩法模板：ssc_std/lhc_std/...
	PlayTemplate pgtype.Text `json:"play_template"`
	// 开奖位数
	BallCount pgtype.Int2 `json:"ball_count"`
	// 1m/3m/5m/jisu，空=无固定间隔
	DrawInterval pgtype.Text `json:"draw_interval"`
	// 第三方 HTTP 下单 game_id（数字字符串，文档 §8 平台彩种序号）
	OutboundLotteryCode pgtype.Text `json:"outbound_lottery_code"`
	// 上架 on_sale / 维护 maintenance
	SaleStatus interface{} `json:"sale_status"`
	// 第三方开奖 WS 彩种线键（lottery_logXXX / eth_lottery_log / tw_lottery_log）
	GuajiWsKey pgtype.Text `json:"guaji_ws_key"`
}

// 旧 9 彩种 purge 幂等标记（startup 一次）
type LotteryCatalogPurgeState struct {
	ID          int16              `json:"id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Note        string             `json:"note"`
}

// 彩种历史开奖（玩法详情 · 历史开奖 Tab）
type LotteryDraw struct {
	ID int64 `json:"id"`
	// 彩种 code
	LotteryCode string `json:"lottery_code"`
	// 官方期号
	IssueNo string `json:"issue_no"`
	// 短期号展示，如 031
	PeriodShort string `json:"period_short"`
	// 开奖号码 JSON 数组
	Balls []byte `json:"balls"`
	// 号码总和
	SumValue  int32              `json:"sum_value"`
	DrawnAt   pgtype.Timestamptz `json:"drawn_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 彩种方案选项种子（运行/玩法/子玩法，只读）
type LotterySchemeOptionSet struct {
	// 彩种 code；_default 为兜底
	LotteryCode string `json:"lottery_code"`
	// 运行类型选项 [{value,label}]
	RunTypes []byte `json:"run_types"`
	// 玩法类型选项 [{value,label}]
	PlayTypes []byte `json:"play_types"`
	// 子玩法选项 [{value,label}]
	SubPlays  []byte             `json:"sub_plays"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 会员账号主表：登录、资料、代理归属与账号状态
type Member struct {
	// 内部主键
	ID int64 `json:"id"`
	// 登录账号，全局唯一
	Account string `json:"account"`
	// 登录密码哈希（bcrypt 等，禁止明文）
	PasswordHash string `json:"password_hash"`
	// 会员展示昵称
	DisplayName string `json:"display_name"`
	// 账号状态：active=正常，frozen=冻结
	Status string `json:"status"`
	// 注册时间（UTC）
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	// 最近登录时间（UTC）；未登录过为 NULL
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	// 记录创建时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 记录最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 资金密码哈希（bcrypt）；NULL 表示尚未设置，未设置不可真实投注
	FundPasswordHash pgtype.Text `json:"fund_password_hash"`
	// 主币种：USDT/TRX/CNY；方案运行与顶栏余额按此币种（默认 CNY）
	PrimaryCurrency string `json:"primary_currency"`
}

// 会员公告已读标记
type MemberAnnouncementRead struct {
	MemberID       int64              `json:"member_id"`
	AnnouncementID string             `json:"announcement_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

// 会员云端全局规则（总止损止盈、断期停投等）
type MemberCloudSetting struct {
	MemberID int64 `json:"member_id"`
	// 总止损（元）
	TotalStopLoss pgtype.Numeric `json:"total_stop_loss"`
	// 总止盈（元）
	TotalTakeProfit pgtype.Numeric `json:"total_take_profit"`
	// 方案倍数系数
	PlanMultiplier pgtype.Numeric `json:"plan_multiplier"`
	// 断期停投开关
	BreakPeriodStop bool               `json:"break_period_stop"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// 会员意见回馈
type MemberFeedback struct {
	ID        int64              `json:"id"`
	MemberID  int64              `json:"member_id"`
	Subject   string             `json:"subject"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 第三方 Hash 挂机授权账号；guaji_username 全局唯一
type MemberGuajiAccount struct {
	ID              int64              `json:"id"`
	MemberID        int64              `json:"member_id"`
	GuajiUsername   string             `json:"guaji_username"`
	PasswordEnc     string             `json:"password_enc"`
	MfaMaterialEnc  pgtype.Text        `json:"mfa_material_enc"`
	AccessTokenEnc  pgtype.Text        `json:"access_token_enc"`
	RefreshTokenEnc pgtype.Text        `json:"refresh_token_enc"`
	TokenExpiresAt  pgtype.Timestamptz `json:"token_expires_at"`
	IsActive        bool               `json:"is_active"`
	BoundAt         pgtype.Timestamptz `json:"bound_at"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastTokenError  pgtype.Text        `json:"last_token_error"`
	LastBetAt       pgtype.Timestamptz `json:"last_bet_at"`
	ReauthFailCount int32              `json:"reauth_fail_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	// 第三方 USDT 可用余额快照（用户端 balance 同步写入）
	BalanceUsdt pgtype.Numeric `json:"balance_usdt"`
	// 第三方 TRX 可用余额快照（用户端 balance 同步写入）
	BalanceTrx pgtype.Numeric `json:"balance_trx"`
	// 第三方 CNY 可用余额快照（用户端 balance 同步写入）
	BalanceCny pgtype.Numeric `json:"balance_cny"`
}

// 会员回头运行时累计（整体判断用）
type MemberLookbackRuntime struct {
	MemberID int64 `json:"member_id"`
	// 整体回头累计盈亏（元）
	SessionPnl pgtype.Numeric `json:"session_pnl"`
	// 当前统计期号
	PeriodIssue string `json:"period_issue"`
	// 当期累计盈亏（元）
	PeriodPnl pgtype.Numeric `json:"period_pnl"`
	// 当期命中方案数
	PeriodHitCount int32              `json:"period_hit_count"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SimBet         bool               `json:"sim_bet"`
	// 跨期累计中奖次数（整体几回头）
	TotalHitCount int32 `json:"total_hit_count"`
}

// 会员云端回头设置（按会员持久化）
type MemberLookbackSetting struct {
	MemberID int64 `json:"member_id"`
	// 逗号分隔：real 正式 / sim 模拟；空表示未选择
	RunMode string `json:"run_mode"`
	// individual 个别判断 / overall 整体判断 / 空 未选择
	Judgment string `json:"judgment"`
	// 单方案盈利阈值（元）
	SingleProfitThreshold pgtype.Numeric `json:"single_profit_threshold"`
	// 单方案亏损阈值（元）
	SingleLossThreshold    pgtype.Numeric     `json:"single_loss_threshold"`
	OverallProfitThreshold pgtype.Numeric     `json:"overall_profit_threshold"`
	OverallLossThreshold   pgtype.Numeric     `json:"overall_loss_threshold"`
	SchemeWinsMin          pgtype.Numeric     `json:"scheme_wins_min"`
	SchemeWinsMax          pgtype.Numeric     `json:"scheme_wins_max"`
	PeriodProfit           pgtype.Numeric     `json:"period_profit"`
	PeriodLoss             pgtype.Numeric     `json:"period_loss"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	// 正式通道(simBet=false)是否启用回头
	ApplyFormal bool `json:"apply_formal"`
	// 模拟通道(simBet=true)是否启用回头
	ApplySim bool `json:"apply_sim"`
}

// 会员出款账户：银行卡、USDT 地址、第三方钱包等
type MemberPayoutAccount struct {
	// 主键
	ID int64 `json:"id"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 账户类型：bank_card、usdt_trc20、alipay 等
	AccountType string `json:"account_type"`
	// 会员自定义标签，便于列表展示
	Label string `json:"label"`
	// 持卡人/账户姓名；链上地址类可为 NULL
	HolderName pgtype.Text `json:"holder_name"`
	// 卡号/链上地址/账号（存储时可脱敏，展示层再处理）
	AccountNo string `json:"account_no"`
	// 银行名称；非银行卡为 NULL
	BankName pgtype.Text `json:"bank_name"`
	// 开户支行；非银行卡为 NULL
	BranchName pgtype.Text `json:"branch_name"`
	// 是否默认出款账户
	IsDefault bool `json:"is_default"`
	// 状态：pending_review=待审核，active=可用，rejected=驳回，disabled=停用
	Status string `json:"status"`
	// 审核驳回原因；未驳回为 NULL
	RejectReason pgtype.Text `json:"reject_reason"`
	// 绑定时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 会员收藏的跟单大厅方案快照（内置计画选择来源）
type MemberSchemeFavorite struct {
	ID       int64 `json:"id"`
	MemberID int64 `json:"member_id"`
	// 关联 scheme_share_snapshots.id
	SnapshotID string             `json:"snapshot_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// 会员钱包表：可用余额与冻结余额，与 members 一对一
type MemberWallet struct {
	// 主键
	ID int64 `json:"id"`
	// 会员 ID，关联 members.id，唯一
	MemberID int64 `json:"member_id"`
	// 可用余额（元，2 位小数），不得为负
	Balance pgtype.Numeric `json:"balance"`
	// 冻结余额（元，2 位小数），如提现审核中
	FrozenBalance pgtype.Numeric `json:"frozen_balance"`
	// 币种 ISO 4217 三字码，默认 CNY
	Currency string `json:"currency"`
	// 乐观锁版本号，每次余额变更 +1
	Version int64 `json:"version"`
	// 创建时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlayTemplate struct {
	Code    string `json:"code"`
	Label   string `json:"label"`
	Version int32  `json:"version"`
	// 第三方 rules/v2 顶层键（玩法类型模板 id，如 1=时时彩）
	GuajiRulesTypeID pgtype.Text `json:"guaji_rules_type_id"`
}

type PlayType struct {
	ID           int64              `json:"id"`
	TemplateCode string             `json:"template_code"`
	TypeID       string             `json:"type_id"`
	Label        string             `json:"label"`
	SortOrder    int32              `json:"sort_order"`
	PanelType    pgtype.Text        `json:"panel_type"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 会员充值订单表
type RechargeOrder struct {
	// 主键
	ID int64 `json:"id"`
	// 充值订单号，全局唯一
	OrderNo string `json:"order_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 充值金额（元，2 位小数），必须大于 0
	Amount pgtype.Numeric `json:"amount"`
	// 充值渠道编码（对接支付通道）
	Channel string `json:"channel"`
	// 订单状态：pending=待支付，paid=已到账，cancelled=已取消，failed=失败
	Status string `json:"status"`
	// 到账时间（UTC）；未到账为 NULL
	PaidAt pgtype.Timestamptz `json:"paid_at"`
	// 下单时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 会员私池方案定义
type SchemeDefinition struct {
	// 方案定义 ID
	ID string `json:"id"`
	// 所属会员 ID
	MemberID int64 `json:"member_id"`
	// 方案类型：custom 自创 / contrary 反买 / follow 跟单
	Kind string `json:"kind"`
	// 方案名称（同会员内唯一）
	SchemeName string `json:"scheme_name"`
	// 彩种 code（对内）
	LotteryCode string `json:"lottery_code"`
	// 彩种展示名（对外）
	LotteryLabel string `json:"lottery_label"`
	// 分享状态（跟单/反买恒为 private）
	ShareStatus string `json:"share_status"`
	// 分享状态是否已锁定（添加至云端后 true）
	ShareStatusLocked bool `json:"share_status_locked"`
	// 方案配置 JSON
	Config []byte `json:"config"`
	// 来源分享池快照 ID（跟单下载时）
	SourceSnapshotID pgtype.Text        `json:"source_snapshot_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// 云端方案实例（1 方案定义 : 1 实例）
type SchemeInstance struct {
	ID string `json:"id"`
	// 关联 scheme_definitions.id
	DefinitionID string `json:"definition_id"`
	MemberID     int64  `json:"member_id"`
	Kind         string `json:"kind"`
	SchemeName   string `json:"scheme_name"`
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
	// pending / running / paused / soft_stopped
	Status       string             `json:"status"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	// 倍投轮次索引（0-based，对应 config.rounds）
	RoundIndex int32 `json:"round_index"`
	// Worker 已结算的最后一期官方期号
	LastSettledIssue pgtype.Text `json:"last_settled_issue"`
	// paused/run 子状态：await_next_bet 下期投注 / cloud_active 云端挂机中 等
	StatusReason string `json:"status_reason"`
	// 出号游标：定码轮换组游标 / 高级定码轮换当前局数（0=未初始化）
	PickIndex int32 `json:"pick_index"`
	// 当前号码池（冷热温/随机跨期保号）
	CurrentPick string `json:"current_pick"`
	// 开某投某上一局投向：pos 正投 / neg 反投
	LastDirection string `json:"last_direction"`
	// 本次运行累计盈亏（从 pending 开启时归零）
	SessionPnl pgtype.Numeric `json:"session_pnl"`
	// 当前 running 段开始时刻；暂停时累加至 run_time_sec 并清空
	RunningSince pgtype.Timestamptz `json:"running_since"`
	// 投注失败时第三方返回原因（展示用）
	BetFailedDetail pgtype.Text `json:"bet_failed_detail"`
	// 方案开启时无条件跳过的第三方 periods 期号（开启瞬间快照）
	StartSkipPeriod pgtype.Text `json:"start_skip_period"`
	// 开启时跳过期封盘时刻（开启瞬间快照，用于激活与倒计时）
	StartSkipCloseAt pgtype.Timestamptz `json:"start_skip_close_at"`
}

// 分享池快照：仅自创型，与会员私池脱钩
type SchemeShareSnapshot struct {
	// 快照 ID，如 SD10001
	ID string `json:"id"`
	// 固定 custom（自创）
	Kind string `json:"kind"`
	// 方案展示名
	SchemeName string `json:"scheme_name"`
	// 彩种 code（对内）
	LotteryCode string `json:"lottery_code"`
	// 彩种展示名（对外）
	LotteryLabel string `json:"lottery_label"`
	// 玩法展示文案
	PlayMethod string `json:"play_method"`
	// 方案资金（元）
	FundYuan pgtype.Numeric `json:"fund_yuan"`
	// 完整方案配置 JSON
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 高级方案模板库：Admin 维护，Client 倍投设定展示
type SchemeTemplate struct {
	// 模板 ID，全局唯一
	ID string `json:"id"`
	// 模板名称
	Name string `json:"name"`
	// 默认彩种编码，关联 lottery_catalog.code
	LotteryCode string `json:"lottery_code"`
	// 运营说明
	Brief pgtype.Text `json:"brief"`
	// 排序权重，越小越靠前
	SortOrder int32 `json:"sort_order"`
	// 是否对会员可见
	Enabled      bool               `json:"enabled"`
	Config       []byte             `json:"config"`
	MemberID     pgtype.Int8        `json:"member_id"`
	DefinitionID pgtype.Text        `json:"definition_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SubPlay struct {
	ID               int64              `json:"id"`
	TemplateCode     string             `json:"template_code"`
	TypeID           string             `json:"type_id"`
	SubID            string             `json:"sub_id"`
	Label            string             `json:"label"`
	SortOrder        int32              `json:"sort_order"`
	BetMode          pgtype.Text        `json:"bet_mode"`
	SegmentRule      []byte             `json:"segment_rule"`
	OutboundPlayCode pgtype.Text        `json:"outbound_play_code"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// 会员帐变流水表：只增不改，记录每笔资金变动及变动后余额
type WalletLedger struct {
	// 主键
	ID int64 `json:"id"`
	// 帐变流水号，全局唯一
	LedgerNo string `json:"ledger_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 帐变类型：deposit=入款，withdraw=出款，bet_debit=投注扣款，payout=派奖，withdraw_freeze=提现冻结，adjust=调账
	TxnType string `json:"txn_type"`
	// 变动金额（元，2 位小数；正为增加，负为减少）
	DeltaAmount pgtype.Numeric `json:"delta_amount"`
	// 变动后可用余额（元，2 位小数）
	BalanceAfter pgtype.Numeric `json:"balance_after"`
	// 关联业务单号（充值/提现/投注等）；无关联时为 NULL
	OrderRef pgtype.Text `json:"order_ref"`
	// 备注或运营说明；可为空
	Remark pgtype.Text `json:"remark"`
	// 帐变发生时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 第三方授权账号 id（real 镜像行；本地/历史为 NULL）
	GuajiAccountID pgtype.Int8 `json:"guaji_account_id"`
	// real 镜像行主币种 USDT/TRX/CNY；balance_after 为该币种第三方余额快照
	Currency pgtype.Text `json:"currency"`
}

// 会员提现订单表：审核与打款流程
type WithdrawOrder struct {
	// 主键
	ID int64 `json:"id"`
	// 提现订单号，全局唯一（如 WD00001）
	OrderNo string `json:"order_no"`
	// 会员 ID，关联 members.id
	MemberID int64 `json:"member_id"`
	// 提现金额（元，2 位小数），必须大于 0
	Amount pgtype.Numeric `json:"amount"`
	// 提现渠道：bank_card、usdt_trc20、alipay 等
	Channel string `json:"channel"`
	// 出款账户 ID，关联 member_payout_accounts.id；提交时可为空
	PayoutAccountID pgtype.Int8 `json:"payout_account_id"`
	// 状态：pending_review=待审核，pending_payout=待打款，paid=已打款，rejected=已驳回
	Status string `json:"status"`
	// 审核完成时间（UTC）；未审核为 NULL
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	// 打款完成时间（UTC）；未打款为 NULL
	PaidAt pgtype.Timestamptz `json:"paid_at"`
	// 驳回原因；未驳回为 NULL
	RejectReason pgtype.Text `json:"reject_reason"`
	// 申请时间（UTC）
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 最后更新时间（UTC）
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
