// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payout_accounts.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertWalletLedger = `-- name: InsertWalletLedger :exec
INSERT INTO wallet_ledger (
    ledger_no, member_id, txn_type, delta_amount, balance_after, order_ref
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertWalletLedgerParams struct {
	LedgerNo     string         `json:"ledger_no"`
	MemberID     int64          `json:"member_id"`
	TxnType      string         `json:"txn_type"`
	DeltaAmount  pgtype.Numeric `json:"delta_amount"`
	BalanceAfter pgtype.Numeric `json:"balance_after"`
	OrderRef     pgtype.Text    `json:"order_ref"`
}

func (q *Queries) InsertWalletLedger(ctx context.Context, arg InsertWalletLedgerParams) error {
	_, err := q.db.Exec(ctx, insertWalletLedger,
		arg.LedgerNo,
		arg.MemberID,
		arg.TxnType,
		arg.DeltaAmount,
		arg.BalanceAfter,
		arg.OrderRef,
	)
	return err
}

const insertWalletLedgerMirror = `-- name: InsertWalletLedgerMirror :exec
INSERT INTO wallet_ledger (
    ledger_no, member_id, txn_type, delta_amount, balance_after, order_ref,
    guaji_account_id, currency, remark
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertWalletLedgerMirrorParams struct {
	LedgerNo       string         `json:"ledger_no"`
	MemberID       int64          `json:"member_id"`
	TxnType        string         `json:"txn_type"`
	DeltaAmount    pgtype.Numeric `json:"delta_amount"`
	BalanceAfter   pgtype.Numeric `json:"balance_after"`
	OrderRef       pgtype.Text    `json:"order_ref"`
	GuajiAccountID pgtype.Int8    `json:"guaji_account_id"`
	Currency       pgtype.Text    `json:"currency"`
	Remark         pgtype.Text    `json:"remark"`
}

func (q *Queries) InsertWalletLedgerMirror(ctx context.Context, arg InsertWalletLedgerMirrorParams) error {
	_, err := q.db.Exec(ctx, insertWalletLedgerMirror,
		arg.LedgerNo,
		arg.MemberID,
		arg.TxnType,
		arg.DeltaAmount,
		arg.BalanceAfter,
		arg.OrderRef,
		arg.GuajiAccountID,
		arg.Currency,
		arg.Remark,
	)
	return err
}

const lockMemberWallet = `-- name: LockMemberWallet :one

SELECT
    w.id,
    w.balance::float8 AS balance,
    w.frozen_balance::float8 AS frozen_balance,
    w.version
FROM member_wallets w
WHERE w.member_id = $1
FOR UPDATE
`

type LockMemberWalletRow struct {
	ID            int64   `json:"id"`
	Balance       float64 `json:"balance"`
	FrozenBalance float64 `json:"frozen_balance"`
	Version       int64   `json:"version"`
}

// ?? / ???????????????????????????????
func (q *Queries) LockMemberWallet(ctx context.Context, memberID int64) (LockMemberWalletRow, error) {
	row := q.db.QueryRow(ctx, lockMemberWallet, memberID)
	var i LockMemberWalletRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.FrozenBalance,
		&i.Version,
	)
	return i, err
}

const sumBetVolumeByMember = `-- name: SumBetVolumeByMember :one
SELECT COALESCE(SUM(b.amount), 0)::float8 AS total
FROM bet_orders b
WHERE b.member_id = $1
  AND b.status IN ('pending', 'win', 'lose')
`

func (q *Queries) SumBetVolumeByMember(ctx context.Context, memberID int64) (float64, error) {
	row := q.db.QueryRow(ctx, sumBetVolumeByMember, memberID)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const updateMemberWalletBalances = `-- name: UpdateMemberWalletBalances :execrows
UPDATE member_wallets
SET balance = $2,
    frozen_balance = $3,
    version = version + 1,
    updated_at = now()
WHERE member_id = $1
  AND version = $4
`

type UpdateMemberWalletBalancesParams struct {
	MemberID      int64          `json:"member_id"`
	Balance       pgtype.Numeric `json:"balance"`
	FrozenBalance pgtype.Numeric `json:"frozen_balance"`
	Version       int64          `json:"version"`
}

func (q *Queries) UpdateMemberWalletBalances(ctx context.Context, arg UpdateMemberWalletBalancesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberWalletBalances,
		arg.MemberID,
		arg.Balance,
		arg.FrozenBalance,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
