// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: play_catalog.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubPlays = `-- name: CountSubPlays :one
SELECT COUNT(*)::int AS count FROM sub_plays
`

func (q *Queries) CountSubPlays(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countSubPlays)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getLotteryCatalogPurgeState = `-- name: GetLotteryCatalogPurgeState :one
SELECT id, completed_at, note
FROM lottery_catalog_purge_state
WHERE id = 1
`

func (q *Queries) GetLotteryCatalogPurgeState(ctx context.Context) (LotteryCatalogPurgeState, error) {
	row := q.db.QueryRow(ctx, getLotteryCatalogPurgeState)
	var i LotteryCatalogPurgeState
	err := row.Scan(&i.ID, &i.CompletedAt, &i.Note)
	return i, err
}

const getSubPlay = `-- name: GetSubPlay :one
SELECT
    template_code,
    type_id,
    sub_id,
    label,
    sort_order,
    bet_mode,
    segment_rule,
    outbound_play_code,
    enabled
FROM sub_plays
WHERE template_code = $1
  AND type_id = $2
  AND sub_id = $3
`

type GetSubPlayParams struct {
	TemplateCode string `json:"template_code"`
	TypeID       string `json:"type_id"`
	SubID        string `json:"sub_id"`
}

type GetSubPlayRow struct {
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	Label            string      `json:"label"`
	SortOrder        int32       `json:"sort_order"`
	BetMode          pgtype.Text `json:"bet_mode"`
	SegmentRule      []byte      `json:"segment_rule"`
	OutboundPlayCode pgtype.Text `json:"outbound_play_code"`
	Enabled          bool        `json:"enabled"`
}

func (q *Queries) GetSubPlay(ctx context.Context, arg GetSubPlayParams) (GetSubPlayRow, error) {
	row := q.db.QueryRow(ctx, getSubPlay, arg.TemplateCode, arg.TypeID, arg.SubID)
	var i GetSubPlayRow
	err := row.Scan(
		&i.TemplateCode,
		&i.TypeID,
		&i.SubID,
		&i.Label,
		&i.SortOrder,
		&i.BetMode,
		&i.SegmentRule,
		&i.OutboundPlayCode,
		&i.Enabled,
	)
	return i, err
}

const insertLotteryCatalogPurgeState = `-- name: InsertLotteryCatalogPurgeState :exec
INSERT INTO lottery_catalog_purge_state (id, note)
VALUES (1, $1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) InsertLotteryCatalogPurgeState(ctx context.Context, note string) error {
	_, err := q.db.Exec(ctx, insertLotteryCatalogPurgeState, note)
	return err
}

const listPlayTemplates = `-- name: ListPlayTemplates :many
SELECT code, label, version
FROM play_templates
ORDER BY code ASC
`

type ListPlayTemplatesRow struct {
	Code    string `json:"code"`
	Label   string `json:"label"`
	Version int32  `json:"version"`
}

func (q *Queries) ListPlayTemplates(ctx context.Context) ([]ListPlayTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPlayTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayTemplatesRow{}
	for rows.Next() {
		var i ListPlayTemplatesRow
		if err := rows.Scan(&i.Code, &i.Label, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayTypesByTemplate = `-- name: ListPlayTypesByTemplate :many
SELECT template_code, type_id, label, sort_order, panel_type, enabled
FROM play_types
WHERE template_code = $1
ORDER BY sort_order ASC, type_id ASC
`

type ListPlayTypesByTemplateRow struct {
	TemplateCode string      `json:"template_code"`
	TypeID       string      `json:"type_id"`
	Label        string      `json:"label"`
	SortOrder    int32       `json:"sort_order"`
	PanelType    pgtype.Text `json:"panel_type"`
	Enabled      bool        `json:"enabled"`
}

func (q *Queries) ListPlayTypesByTemplate(ctx context.Context, templateCode string) ([]ListPlayTypesByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listPlayTypesByTemplate, templateCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayTypesByTemplateRow{}
	for rows.Next() {
		var i ListPlayTypesByTemplateRow
		if err := rows.Scan(
			&i.TemplateCode,
			&i.TypeID,
			&i.Label,
			&i.SortOrder,
			&i.PanelType,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubPlaysByTemplate = `-- name: ListSubPlaysByTemplate :many
SELECT
    template_code,
    type_id,
    sub_id,
    label,
    sort_order,
    bet_mode,
    segment_rule,
    outbound_play_code,
    enabled
FROM sub_plays
WHERE template_code = $1
ORDER BY type_id ASC, sort_order ASC, sub_id ASC
`

type ListSubPlaysByTemplateRow struct {
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	Label            string      `json:"label"`
	SortOrder        int32       `json:"sort_order"`
	BetMode          pgtype.Text `json:"bet_mode"`
	SegmentRule      []byte      `json:"segment_rule"`
	OutboundPlayCode pgtype.Text `json:"outbound_play_code"`
	Enabled          bool        `json:"enabled"`
}

func (q *Queries) ListSubPlaysByTemplate(ctx context.Context, templateCode string) ([]ListSubPlaysByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listSubPlaysByTemplate, templateCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubPlaysByTemplateRow{}
	for rows.Next() {
		var i ListSubPlaysByTemplateRow
		if err := rows.Scan(
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.Label,
			&i.SortOrder,
			&i.BetMode,
			&i.SegmentRule,
			&i.OutboundPlayCode,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
