// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: play_rule_specs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayRuleSpecRevisionForPublish = `-- name: GetPlayRuleSpecRevisionForPublish :one
SELECT id,
       rule_spec_id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       revision,
       status,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       actor,
       change_reason,
       verified_at,
       published_at,
       created_at
FROM play_rule_spec_revisions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPlayRuleSpecRevisionForPublish(ctx context.Context, id int64) (PlayRuleSpecRevision, error) {
	row := q.db.QueryRow(ctx, getPlayRuleSpecRevisionForPublish, id)
	var i PlayRuleSpecRevision
	err := row.Scan(
		&i.ID,
		&i.RuleSpecID,
		&i.TemplateCode,
		&i.TypeID,
		&i.SubID,
		&i.LotteryCode,
		&i.Revision,
		&i.Status,
		&i.EvaluatorKey,
		&i.EvaluatorVersion,
		&i.EvaluationSpec,
		&i.SampleCases,
		&i.SourceMeta,
		&i.Actor,
		&i.ChangeReason,
		&i.VerifiedAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlayRuleSpecRevision = `-- name: InsertPlayRuleSpecRevision :one
INSERT INTO play_rule_spec_revisions (
    rule_spec_id, template_code, type_id, sub_id, lottery_code,
    revision, status, evaluator_key, evaluator_version,
    evaluation_spec, sample_cases, source_meta, actor, change_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING id, status, revision, created_at
`

type InsertPlayRuleSpecRevisionParams struct {
	RuleSpecID       pgtype.Int8 `json:"rule_spec_id"`
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	LotteryCode      pgtype.Text `json:"lottery_code"`
	Revision         int32       `json:"revision"`
	Status           string      `json:"status"`
	EvaluatorKey     string      `json:"evaluator_key"`
	EvaluatorVersion int32       `json:"evaluator_version"`
	EvaluationSpec   []byte      `json:"evaluation_spec"`
	SampleCases      []byte      `json:"sample_cases"`
	SourceMeta       []byte      `json:"source_meta"`
	Actor            string      `json:"actor"`
	ChangeReason     string      `json:"change_reason"`
}

type InsertPlayRuleSpecRevisionRow struct {
	ID        int64              `json:"id"`
	Status    string             `json:"status"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlayRuleSpecRevision(ctx context.Context, arg InsertPlayRuleSpecRevisionParams) (InsertPlayRuleSpecRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertPlayRuleSpecRevision,
		arg.RuleSpecID,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
		arg.Revision,
		arg.Status,
		arg.EvaluatorKey,
		arg.EvaluatorVersion,
		arg.EvaluationSpec,
		arg.SampleCases,
		arg.SourceMeta,
		arg.Actor,
		arg.ChangeReason,
	)
	var i InsertPlayRuleSpecRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledPlayRuleSpecs = `-- name: ListEnabledPlayRuleSpecs :many
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       rule_version,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       strategy_enabled,
       published_at,
       updated_at
FROM play_rule_specs
WHERE strategy_enabled
ORDER BY template_code, type_id, sub_id, lottery_code NULLS FIRST
`

func (q *Queries) ListEnabledPlayRuleSpecs(ctx context.Context) ([]PlayRuleSpec, error) {
	rows, err := q.db.Query(ctx, listEnabledPlayRuleSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayRuleSpec{}
	for rows.Next() {
		var i PlayRuleSpec
		if err := rows.Scan(
			&i.ID,
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.LotteryCode,
			&i.RuleVersion,
			&i.EvaluatorKey,
			&i.EvaluatorVersion,
			&i.EvaluationSpec,
			&i.SampleCases,
			&i.SourceMeta,
			&i.StrategyEnabled,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayRuleSpecRevisionPublished = `-- name: MarkPlayRuleSpecRevisionPublished :execrows
UPDATE play_rule_spec_revisions
SET status = 'published', published_at = now()
WHERE id = $1
  AND status = 'verified'
`

func (q *Queries) MarkPlayRuleSpecRevisionPublished(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPlayRuleSpecRevisionPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPlayRuleSpecRevisionVerified = `-- name: MarkPlayRuleSpecRevisionVerified :execrows
UPDATE play_rule_spec_revisions
SET status = 'verified', verified_at = now()
WHERE id = $1
  AND status = 'draft'
`

func (q *Queries) MarkPlayRuleSpecRevisionVerified(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPlayRuleSpecRevisionVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePublishedPlayRuleSpec = `-- name: ResolvePublishedPlayRuleSpec :one
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       rule_version,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       strategy_enabled,
       published_at,
       updated_at
FROM play_rule_specs
WHERE template_code = $1
  AND type_id = $2
  AND sub_id = $3
  AND (lottery_code = $4 OR lottery_code IS NULL)
ORDER BY CASE WHEN lottery_code = $4 THEN 0 ELSE 1 END
LIMIT 1
`

type ResolvePublishedPlayRuleSpecParams struct {
	TemplateCode string      `json:"template_code"`
	TypeID       string      `json:"type_id"`
	SubID        string      `json:"sub_id"`
	LotteryCode  pgtype.Text `json:"lottery_code"`
}

func (q *Queries) ResolvePublishedPlayRuleSpec(ctx context.Context, arg ResolvePublishedPlayRuleSpecParams) (PlayRuleSpec, error) {
	row := q.db.QueryRow(ctx, resolvePublishedPlayRuleSpec,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
	)
	var i PlayRuleSpec
	err := row.Scan(
		&i.ID,
		&i.TemplateCode,
		&i.TypeID,
		&i.SubID,
		&i.LotteryCode,
		&i.RuleVersion,
		&i.EvaluatorKey,
		&i.EvaluatorVersion,
		&i.EvaluationSpec,
		&i.SampleCases,
		&i.SourceMeta,
		&i.StrategyEnabled,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPublishedPlayRuleSpec = `-- name: UpsertPublishedPlayRuleSpec :one
INSERT INTO play_rule_specs (
    template_code, type_id, sub_id, lottery_code, rule_version,
    evaluator_key, evaluator_version, evaluation_spec, sample_cases,
    source_meta, strategy_enabled, published_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, now(), now()
)
ON CONFLICT (template_code, type_id, sub_id, lottery_code)
DO UPDATE SET
    rule_version = EXCLUDED.rule_version,
    evaluator_key = EXCLUDED.evaluator_key,
    evaluator_version = EXCLUDED.evaluator_version,
    evaluation_spec = EXCLUDED.evaluation_spec,
    sample_cases = EXCLUDED.sample_cases,
    source_meta = EXCLUDED.source_meta,
    strategy_enabled = EXCLUDED.strategy_enabled,
    published_at = now(),
    updated_at = now()
RETURNING id, rule_version, strategy_enabled, updated_at
`

type UpsertPublishedPlayRuleSpecParams struct {
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	LotteryCode      pgtype.Text `json:"lottery_code"`
	RuleVersion      int32       `json:"rule_version"`
	EvaluatorKey     string      `json:"evaluator_key"`
	EvaluatorVersion int32       `json:"evaluator_version"`
	EvaluationSpec   []byte      `json:"evaluation_spec"`
	SampleCases      []byte      `json:"sample_cases"`
	SourceMeta       []byte      `json:"source_meta"`
	StrategyEnabled  bool        `json:"strategy_enabled"`
}

type UpsertPublishedPlayRuleSpecRow struct {
	ID              int64              `json:"id"`
	RuleVersion     int32              `json:"rule_version"`
	StrategyEnabled bool               `json:"strategy_enabled"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPublishedPlayRuleSpec(ctx context.Context, arg UpsertPublishedPlayRuleSpecParams) (UpsertPublishedPlayRuleSpecRow, error) {
	row := q.db.QueryRow(ctx, upsertPublishedPlayRuleSpec,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
		arg.RuleVersion,
		arg.EvaluatorKey,
		arg.EvaluatorVersion,
		arg.EvaluationSpec,
		arg.SampleCases,
		arg.SourceMeta,
		arg.StrategyEnabled,
	)
	var i UpsertPublishedPlayRuleSpecRow
	err := row.Scan(
		&i.ID,
		&i.RuleVersion,
		&i.StrategyEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
