// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: play_rule_specs.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayRuleSpecRevisionForPublish = `-- name: GetPlayRuleSpecRevisionForPublish :one
SELECT id,
       rule_spec_id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       revision,
       status,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       actor,
       change_reason,
       verified_at,
       published_at,
       created_at
FROM play_rule_spec_revisions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPlayRuleSpecRevisionForPublish(ctx context.Context, id int64) (PlayRuleSpecRevision, error) {
	row := q.db.QueryRow(ctx, getPlayRuleSpecRevisionForPublish, id)
	var i PlayRuleSpecRevision
	err := row.Scan(
		&i.ID,
		&i.RuleSpecID,
		&i.TemplateCode,
		&i.TypeID,
		&i.SubID,
		&i.LotteryCode,
		&i.Revision,
		&i.Status,
		&i.EvaluatorKey,
		&i.EvaluatorVersion,
		&i.EvaluationSpec,
		&i.SampleCases,
		&i.SourceMeta,
		&i.Actor,
		&i.ChangeReason,
		&i.VerifiedAt,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlayRuleSpecRevision = `-- name: InsertPlayRuleSpecRevision :one
INSERT INTO play_rule_spec_revisions (
    rule_spec_id, template_code, type_id, sub_id, lottery_code,
    revision, status, evaluator_key, evaluator_version,
    evaluation_spec, sample_cases, source_meta, actor, change_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
RETURNING id, status, revision, created_at
`

type InsertPlayRuleSpecRevisionParams struct {
	RuleSpecID       pgtype.Int8 `json:"rule_spec_id"`
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	LotteryCode      pgtype.Text `json:"lottery_code"`
	Revision         int32       `json:"revision"`
	Status           string      `json:"status"`
	EvaluatorKey     string      `json:"evaluator_key"`
	EvaluatorVersion int32       `json:"evaluator_version"`
	EvaluationSpec   []byte      `json:"evaluation_spec"`
	SampleCases      []byte      `json:"sample_cases"`
	SourceMeta       []byte      `json:"source_meta"`
	Actor            string      `json:"actor"`
	ChangeReason     string      `json:"change_reason"`
}

type InsertPlayRuleSpecRevisionRow struct {
	ID        int64              `json:"id"`
	Status    string             `json:"status"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPlayRuleSpecRevision(ctx context.Context, arg InsertPlayRuleSpecRevisionParams) (InsertPlayRuleSpecRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertPlayRuleSpecRevision,
		arg.RuleSpecID,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
		arg.Revision,
		arg.Status,
		arg.EvaluatorKey,
		arg.EvaluatorVersion,
		arg.EvaluationSpec,
		arg.SampleCases,
		arg.SourceMeta,
		arg.Actor,
		arg.ChangeReason,
	)
	var i InsertPlayRuleSpecRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listDraftPlayRuleSpecRevisions = `-- name: ListDraftPlayRuleSpecRevisions :many
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       revision,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta
FROM play_rule_spec_revisions
WHERE status = 'draft'
ORDER BY id
`

type ListDraftPlayRuleSpecRevisionsRow struct {
	ID               int64       `json:"id"`
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	LotteryCode      pgtype.Text `json:"lottery_code"`
	Revision         int32       `json:"revision"`
	EvaluatorKey     string      `json:"evaluator_key"`
	EvaluatorVersion int32       `json:"evaluator_version"`
	EvaluationSpec   []byte      `json:"evaluation_spec"`
	SampleCases      []byte      `json:"sample_cases"`
	SourceMeta       []byte      `json:"source_meta"`
}

func (q *Queries) ListDraftPlayRuleSpecRevisions(ctx context.Context) ([]ListDraftPlayRuleSpecRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listDraftPlayRuleSpecRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftPlayRuleSpecRevisionsRow{}
	for rows.Next() {
		var i ListDraftPlayRuleSpecRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.LotteryCode,
			&i.Revision,
			&i.EvaluatorKey,
			&i.EvaluatorVersion,
			&i.EvaluationSpec,
			&i.SampleCases,
			&i.SourceMeta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPlayRuleSpecs = `-- name: ListEnabledPlayRuleSpecs :many
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       rule_version,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       strategy_enabled,
       published_at,
       updated_at
FROM play_rule_specs
WHERE strategy_enabled
ORDER BY template_code, type_id, sub_id, lottery_code NULLS FIRST
`

func (q *Queries) ListEnabledPlayRuleSpecs(ctx context.Context) ([]PlayRuleSpec, error) {
	rows, err := q.db.Query(ctx, listEnabledPlayRuleSpecs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayRuleSpec{}
	for rows.Next() {
		var i PlayRuleSpec
		if err := rows.Scan(
			&i.ID,
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.LotteryCode,
			&i.RuleVersion,
			&i.EvaluatorKey,
			&i.EvaluatorVersion,
			&i.EvaluationSpec,
			&i.SampleCases,
			&i.SourceMeta,
			&i.StrategyEnabled,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoricalRuleReplayCandidates = `-- name: ListHistoricalRuleReplayCandidates :many
SELECT c.id,
       c.status,
       c.bet_content,
       si.lottery_code,
       sd.config,
       d.balls
FROM cloud_bet_records c
JOIN scheme_instances si ON si.id = c.scheme_id AND si.member_id = c.member_id
JOIN scheme_definitions sd ON sd.id = si.definition_id AND sd.member_id = c.member_id
JOIN lottery_draws d ON d.lottery_code = si.lottery_code AND d.issue_no = c.period_no
WHERE NOT c.sim_bet
  AND c.status IN ('hit', 'miss')
  AND NULLIF(TRIM(c.bet_content), '') IS NOT NULL
ORDER BY c.id
`

type ListHistoricalRuleReplayCandidatesRow struct {
	ID          int64  `json:"id"`
	Status      string `json:"status"`
	BetContent  string `json:"bet_content"`
	LotteryCode string `json:"lottery_code"`
	Config      []byte `json:"config"`
	Balls       []byte `json:"balls"`
}

func (q *Queries) ListHistoricalRuleReplayCandidates(ctx context.Context) ([]ListHistoricalRuleReplayCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listHistoricalRuleReplayCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoricalRuleReplayCandidatesRow{}
	for rows.Next() {
		var i ListHistoricalRuleReplayCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.BetContent,
			&i.LotteryCode,
			&i.Config,
			&i.Balls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayRuleImportCandidates = `-- name: ListPlayRuleImportCandidates :many
SELECT sp.template_code,
       sp.type_id,
       sp.sub_id,
       COALESCE(sp.bet_mode, '') AS bet_mode,
       COALESCE(sp.segment_rule ->> 'guajiRuleId', sp.outbound_play_code, sp.sub_id) AS rule_id,
       COALESCE(sp.segment_rule ->> 'guajiFullName', sp.label) AS full_name
FROM sub_plays sp
WHERE sp.enabled
ORDER BY sp.template_code, sp.type_id, sp.sub_id
`

type ListPlayRuleImportCandidatesRow struct {
	TemplateCode string `json:"template_code"`
	TypeID       string `json:"type_id"`
	SubID        string `json:"sub_id"`
	BetMode      string `json:"bet_mode"`
	RuleID       string `json:"rule_id"`
	FullName     string `json:"full_name"`
}

func (q *Queries) ListPlayRuleImportCandidates(ctx context.Context) ([]ListPlayRuleImportCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPlayRuleImportCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayRuleImportCandidatesRow{}
	for rows.Next() {
		var i ListPlayRuleImportCandidatesRow
		if err := rows.Scan(
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.BetMode,
			&i.RuleID,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPlayRuleSpecsForAdmin = `-- name: ListPublishedPlayRuleSpecsForAdmin :many
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       rule_version,
       evaluator_key,
       evaluator_version,
       strategy_enabled,
       published_at,
       updated_at
FROM play_rule_specs
ORDER BY template_code, type_id, sub_id, lottery_code NULLS FIRST
`

type ListPublishedPlayRuleSpecsForAdminRow struct {
	ID               int64              `json:"id"`
	TemplateCode     string             `json:"template_code"`
	TypeID           string             `json:"type_id"`
	SubID            string             `json:"sub_id"`
	LotteryCode      pgtype.Text        `json:"lottery_code"`
	RuleVersion      int32              `json:"rule_version"`
	EvaluatorKey     string             `json:"evaluator_key"`
	EvaluatorVersion int32              `json:"evaluator_version"`
	StrategyEnabled  bool               `json:"strategy_enabled"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPlayRuleSpecsForAdmin(ctx context.Context) ([]ListPublishedPlayRuleSpecsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPlayRuleSpecsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPlayRuleSpecsForAdminRow{}
	for rows.Next() {
		var i ListPublishedPlayRuleSpecsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateCode,
			&i.TypeID,
			&i.SubID,
			&i.LotteryCode,
			&i.RuleVersion,
			&i.EvaluatorKey,
			&i.EvaluatorVersion,
			&i.StrategyEnabled,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayRuleSpecRevisionPublished = `-- name: MarkPlayRuleSpecRevisionPublished :execrows
UPDATE play_rule_spec_revisions
SET status = 'published', published_at = now()
WHERE id = $1
  AND status = 'verified'
`

func (q *Queries) MarkPlayRuleSpecRevisionPublished(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPlayRuleSpecRevisionPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPlayRuleSpecRevisionVerified = `-- name: MarkPlayRuleSpecRevisionVerified :execrows
UPDATE play_rule_spec_revisions
SET status = 'verified', verified_at = now()
WHERE id = $1
  AND status = 'draft'
`

func (q *Queries) MarkPlayRuleSpecRevisionVerified(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markPlayRuleSpecRevisionVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextPlayRuleSpecRevision = `-- name: NextPlayRuleSpecRevision :one
SELECT COALESCE(MAX(revision), 0)::int + 1 AS next_revision
FROM play_rule_spec_revisions
WHERE template_code = $1
  AND type_id = $2
  AND sub_id = $3
  AND lottery_code IS NOT DISTINCT FROM $4
`

type NextPlayRuleSpecRevisionParams struct {
	TemplateCode string      `json:"template_code"`
	TypeID       string      `json:"type_id"`
	SubID        string      `json:"sub_id"`
	LotteryCode  pgtype.Text `json:"lottery_code"`
}

func (q *Queries) NextPlayRuleSpecRevision(ctx context.Context, arg NextPlayRuleSpecRevisionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPlayRuleSpecRevision,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
	)
	var next_revision int32
	err := row.Scan(&next_revision)
	return next_revision, err
}

const resolvePublishedPlayRuleSpec = `-- name: ResolvePublishedPlayRuleSpec :one
SELECT id,
       template_code,
       type_id,
       sub_id,
       lottery_code,
       rule_version,
       evaluator_key,
       evaluator_version,
       evaluation_spec,
       sample_cases,
       source_meta,
       strategy_enabled,
       published_at,
       updated_at
FROM play_rule_specs
WHERE template_code = $1
  AND type_id = $2
  AND sub_id = $3
  AND (lottery_code = $4 OR lottery_code IS NULL)
ORDER BY CASE WHEN lottery_code = $4 THEN 0 ELSE 1 END
LIMIT 1
`

type ResolvePublishedPlayRuleSpecParams struct {
	TemplateCode string      `json:"template_code"`
	TypeID       string      `json:"type_id"`
	SubID        string      `json:"sub_id"`
	LotteryCode  pgtype.Text `json:"lottery_code"`
}

func (q *Queries) ResolvePublishedPlayRuleSpec(ctx context.Context, arg ResolvePublishedPlayRuleSpecParams) (PlayRuleSpec, error) {
	row := q.db.QueryRow(ctx, resolvePublishedPlayRuleSpec,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
	)
	var i PlayRuleSpec
	err := row.Scan(
		&i.ID,
		&i.TemplateCode,
		&i.TypeID,
		&i.SubID,
		&i.LotteryCode,
		&i.RuleVersion,
		&i.EvaluatorKey,
		&i.EvaluatorVersion,
		&i.EvaluationSpec,
		&i.SampleCases,
		&i.SourceMeta,
		&i.StrategyEnabled,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraftPlayRuleSpecRevisionCompiled = `-- name: UpdateDraftPlayRuleSpecRevisionCompiled :execrows
UPDATE play_rule_spec_revisions
SET evaluator_key = $1,
    evaluator_version = $2,
    evaluation_spec = $3,
    change_reason = $4
WHERE id = $5
  AND status = 'draft'
`

type UpdateDraftPlayRuleSpecRevisionCompiledParams struct {
	EvaluatorKey     string `json:"evaluator_key"`
	EvaluatorVersion int32  `json:"evaluator_version"`
	EvaluationSpec   []byte `json:"evaluation_spec"`
	ChangeReason     string `json:"change_reason"`
	ID               int64  `json:"id"`
}

func (q *Queries) UpdateDraftPlayRuleSpecRevisionCompiled(ctx context.Context, arg UpdateDraftPlayRuleSpecRevisionCompiledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDraftPlayRuleSpecRevisionCompiled,
		arg.EvaluatorKey,
		arg.EvaluatorVersion,
		arg.EvaluationSpec,
		arg.ChangeReason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPublishedPlayRuleSpec = `-- name: UpsertPublishedPlayRuleSpec :one
INSERT INTO play_rule_specs (
    template_code, type_id, sub_id, lottery_code, rule_version,
    evaluator_key, evaluator_version, evaluation_spec, sample_cases,
    source_meta, strategy_enabled, published_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, now(), now()
)
ON CONFLICT (template_code, type_id, sub_id, lottery_code)
DO UPDATE SET
    rule_version = EXCLUDED.rule_version,
    evaluator_key = EXCLUDED.evaluator_key,
    evaluator_version = EXCLUDED.evaluator_version,
    evaluation_spec = EXCLUDED.evaluation_spec,
    sample_cases = EXCLUDED.sample_cases,
    source_meta = EXCLUDED.source_meta,
    strategy_enabled = EXCLUDED.strategy_enabled,
    published_at = now(),
    updated_at = now()
RETURNING id, rule_version, strategy_enabled, updated_at
`

type UpsertPublishedPlayRuleSpecParams struct {
	TemplateCode     string      `json:"template_code"`
	TypeID           string      `json:"type_id"`
	SubID            string      `json:"sub_id"`
	LotteryCode      pgtype.Text `json:"lottery_code"`
	RuleVersion      int32       `json:"rule_version"`
	EvaluatorKey     string      `json:"evaluator_key"`
	EvaluatorVersion int32       `json:"evaluator_version"`
	EvaluationSpec   []byte      `json:"evaluation_spec"`
	SampleCases      []byte      `json:"sample_cases"`
	SourceMeta       []byte      `json:"source_meta"`
	StrategyEnabled  bool        `json:"strategy_enabled"`
}

type UpsertPublishedPlayRuleSpecRow struct {
	ID              int64              `json:"id"`
	RuleVersion     int32              `json:"rule_version"`
	StrategyEnabled bool               `json:"strategy_enabled"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPublishedPlayRuleSpec(ctx context.Context, arg UpsertPublishedPlayRuleSpecParams) (UpsertPublishedPlayRuleSpecRow, error) {
	row := q.db.QueryRow(ctx, upsertPublishedPlayRuleSpec,
		arg.TemplateCode,
		arg.TypeID,
		arg.SubID,
		arg.LotteryCode,
		arg.RuleVersion,
		arg.EvaluatorKey,
		arg.EvaluatorVersion,
		arg.EvaluationSpec,
		arg.SampleCases,
		arg.SourceMeta,
		arg.StrategyEnabled,
	)
	var i UpsertPublishedPlayRuleSpecRow
	err := row.Scan(
		&i.ID,
		&i.RuleVersion,
		&i.StrategyEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
