// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheme_favorites.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMemberSchemeFavorite = `-- name: DeleteMemberSchemeFavorite :execrows
DELETE FROM member_scheme_favorites
WHERE member_id = $1 AND snapshot_id = $2
`

type DeleteMemberSchemeFavoriteParams struct {
	MemberID   int64  `json:"member_id"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) DeleteMemberSchemeFavorite(ctx context.Context, arg DeleteMemberSchemeFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemberSchemeFavorite, arg.MemberID, arg.SnapshotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsMemberSchemeFavorite = `-- name: ExistsMemberSchemeFavorite :one
SELECT EXISTS (
    SELECT 1 FROM member_scheme_favorites
    WHERE member_id = $1 AND snapshot_id = $2
)
`

type ExistsMemberSchemeFavoriteParams struct {
	MemberID   int64  `json:"member_id"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) ExistsMemberSchemeFavorite(ctx context.Context, arg ExistsMemberSchemeFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsMemberSchemeFavorite, arg.MemberID, arg.SnapshotID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertMemberSchemeFavorite = `-- name: InsertMemberSchemeFavorite :execrows
INSERT INTO member_scheme_favorites (member_id, snapshot_id)
VALUES ($1, $2)
ON CONFLICT (member_id, snapshot_id) DO NOTHING
`

type InsertMemberSchemeFavoriteParams struct {
	MemberID   int64  `json:"member_id"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) InsertMemberSchemeFavorite(ctx context.Context, arg InsertMemberSchemeFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMemberSchemeFavorite, arg.MemberID, arg.SnapshotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMemberSchemeFavorites = `-- name: ListMemberSchemeFavorites :many
SELECT
    f.snapshot_id, f.created_at,
    s.scheme_name, s.lottery_code, s.lottery_label, s.play_method, s.fund_yuan, s.config
FROM member_scheme_favorites f
JOIN scheme_share_snapshots s ON s.id = f.snapshot_id
WHERE f.member_id = $1
ORDER BY f.created_at DESC
`

type ListMemberSchemeFavoritesRow struct {
	SnapshotID   string             `json:"snapshot_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	PlayMethod   string             `json:"play_method"`
	FundYuan     pgtype.Numeric     `json:"fund_yuan"`
	Config       []byte             `json:"config"`
}

func (q *Queries) ListMemberSchemeFavorites(ctx context.Context, memberID int64) ([]ListMemberSchemeFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listMemberSchemeFavorites, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberSchemeFavoritesRow{}
	for rows.Next() {
		var i ListMemberSchemeFavoritesRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.CreatedAt,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.PlayMethod,
			&i.FundYuan,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchemeDefinitionLottery = `-- name: UpdateSchemeDefinitionLottery :exec
UPDATE scheme_definitions
SET lottery_code = $3, lottery_label = $4, updated_at = now()
WHERE id = $1 AND member_id = $2
`

type UpdateSchemeDefinitionLotteryParams struct {
	ID           string `json:"id"`
	MemberID     int64  `json:"member_id"`
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
}

func (q *Queries) UpdateSchemeDefinitionLottery(ctx context.Context, arg UpdateSchemeDefinitionLotteryParams) error {
	_, err := q.db.Exec(ctx, updateSchemeDefinitionLottery,
		arg.ID,
		arg.MemberID,
		arg.LotteryCode,
		arg.LotteryLabel,
	)
	return err
}
