// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheme_instances.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSchemeInstanceCountdown = `-- name: AdvanceSchemeInstanceCountdown :execrows

UPDATE scheme_instances

SET countdown_sec = GREATEST(countdown_sec - $2, 0),

    updated_at = now()

WHERE id = $1

  AND status = 'running'
`

type AdvanceSchemeInstanceCountdownParams struct {
	ID           string `json:"id"`
	CountdownSec int32  `json:"countdown_sec"`
}

func (q *Queries) AdvanceSchemeInstanceCountdown(ctx context.Context, arg AdvanceSchemeInstanceCountdownParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSchemeInstanceCountdown, arg.ID, arg.CountdownSec)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applySchemeInstanceBet = `-- name: ApplySchemeInstanceBet :one

UPDATE scheme_instances

SET countdown_sec = $2,

    turnover = turnover + $3,

    pnl = pnl + $4,

    session_pnl = session_pnl + $4,

    lookback_pnl = lookback_pnl + $8,

    multiplier = $5,

    round_index = $6,

    last_settled_issue = $7,

    pick_index = $9,

    current_pick = $10,

    last_direction = $11,

    status_reason = 'cloud_active',

    updated_at = now()

WHERE id = $1

  AND status = 'running'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    round_index, last_settled_issue, pick_index, current_pick, last_direction,

    created_at, updated_at
`

type ApplySchemeInstanceBetParams struct {
	ID               string         `json:"id"`
	CountdownSec     int32          `json:"countdown_sec"`
	Turnover         pgtype.Numeric `json:"turnover"`
	Pnl              pgtype.Numeric `json:"pnl"`
	Multiplier       pgtype.Numeric `json:"multiplier"`
	RoundIndex       int32          `json:"round_index"`
	LastSettledIssue pgtype.Text    `json:"last_settled_issue"`
	LookbackPnl      pgtype.Numeric `json:"lookback_pnl"`
	PickIndex        int32          `json:"pick_index"`
	CurrentPick      string         `json:"current_pick"`
	LastDirection    string         `json:"last_direction"`
}

type ApplySchemeInstanceBetRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	StatusReason     string             `json:"status_reason"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	RoundIndex       int32              `json:"round_index"`
	LastSettledIssue pgtype.Text        `json:"last_settled_issue"`
	PickIndex        int32              `json:"pick_index"`
	CurrentPick      string             `json:"current_pick"`
	LastDirection    string             `json:"last_direction"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ApplySchemeInstanceBet(ctx context.Context, arg ApplySchemeInstanceBetParams) (ApplySchemeInstanceBetRow, error) {
	row := q.db.QueryRow(ctx, applySchemeInstanceBet,
		arg.ID,
		arg.CountdownSec,
		arg.Turnover,
		arg.Pnl,
		arg.Multiplier,
		arg.RoundIndex,
		arg.LastSettledIssue,
		arg.LookbackPnl,
		arg.PickIndex,
		arg.CurrentPick,
		arg.LastDirection,
	)
	var i ApplySchemeInstanceBetRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RoundIndex,
		&i.LastSettledIssue,
		&i.PickIndex,
		&i.CurrentPick,
		&i.LastDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSchemeInstancesByMember = `-- name: CountSchemeInstancesByMember :one

SELECT COUNT(*)::bigint AS total

FROM scheme_instances

WHERE member_id = $1

  AND ($2::text IS NULL OR $2::text = '' OR ($2::text = 'real' AND sim_bet = false) OR ($2::text = 'sim' AND sim_bet = true))
`

type CountSchemeInstancesByMemberParams struct {
	MemberID int64  `json:"member_id"`
	Column2  string `json:"column_2"`
}

func (q *Queries) CountSchemeInstancesByMember(ctx context.Context, arg CountSchemeInstancesByMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSchemeInstancesByMember, arg.MemberID, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getSchemeInstanceByIDAndMember = `-- name: GetSchemeInstanceByIDAndMember :one

SELECT

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, bet_failed_detail, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at

FROM scheme_instances

WHERE id = $1 AND member_id = $2
`

type GetSchemeInstanceByIDAndMemberParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
}

type GetSchemeInstanceByIDAndMemberRow struct {
	ID              string             `json:"id"`
	DefinitionID    string             `json:"definition_id"`
	MemberID        int64              `json:"member_id"`
	Kind            string             `json:"kind"`
	SchemeName      string             `json:"scheme_name"`
	LotteryCode     string             `json:"lottery_code"`
	LotteryLabel    string             `json:"lottery_label"`
	Status          string             `json:"status"`
	StatusReason    string             `json:"status_reason"`
	BetFailedDetail pgtype.Text        `json:"bet_failed_detail"`
	Turnover        pgtype.Numeric     `json:"turnover"`
	Pnl             pgtype.Numeric     `json:"pnl"`
	RunTimeSec      int32              `json:"run_time_sec"`
	LookbackPnl     pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl      pgtype.Numeric     `json:"session_pnl"`
	Multiplier      pgtype.Numeric     `json:"multiplier"`
	CountdownSec    int32              `json:"countdown_sec"`
	SimBet          bool               `json:"sim_bet"`
	RunningSince    pgtype.Timestamptz `json:"running_since"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchemeInstanceByIDAndMember(ctx context.Context, arg GetSchemeInstanceByIDAndMemberParams) (GetSchemeInstanceByIDAndMemberRow, error) {
	row := q.db.QueryRow(ctx, getSchemeInstanceByIDAndMember, arg.ID, arg.MemberID)
	var i GetSchemeInstanceByIDAndMemberRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.BetFailedDetail,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaintenanceStoppedInstances = `-- name: ListMaintenanceStoppedInstances :many
SELECT
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    round_index, last_settled_issue, pick_index, current_pick, last_direction,
    start_skip_period, start_skip_close_at,
    created_at, updated_at
FROM scheme_instances
WHERE status = 'pending'
  AND status_reason = 'maintenance'
ORDER BY updated_at ASC
LIMIT $1
`

type ListMaintenanceStoppedInstancesRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	StatusReason     string             `json:"status_reason"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	RoundIndex       int32              `json:"round_index"`
	LastSettledIssue pgtype.Text        `json:"last_settled_issue"`
	PickIndex        int32              `json:"pick_index"`
	CurrentPick      string             `json:"current_pick"`
	LastDirection    string             `json:"last_direction"`
	StartSkipPeriod  pgtype.Text        `json:"start_skip_period"`
	StartSkipCloseAt pgtype.Timestamptz `json:"start_skip_close_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMaintenanceStoppedInstances(ctx context.Context, limit int32) ([]ListMaintenanceStoppedInstancesRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceStoppedInstances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceStoppedInstancesRow{}
	for rows.Next() {
		var i ListMaintenanceStoppedInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.RoundIndex,
			&i.LastSettledIssue,
			&i.PickIndex,
			&i.CurrentPick,
			&i.LastDirection,
			&i.StartSkipPeriod,
			&i.StartSkipCloseAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningSchemeInstances = `-- name: ListRunningSchemeInstances :many

SELECT

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    round_index, last_settled_issue, pick_index, current_pick, last_direction,

    start_skip_period, start_skip_close_at,

    created_at, updated_at

FROM scheme_instances

WHERE status = 'running'

ORDER BY updated_at
`

type ListRunningSchemeInstancesRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	StatusReason     string             `json:"status_reason"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	RoundIndex       int32              `json:"round_index"`
	LastSettledIssue pgtype.Text        `json:"last_settled_issue"`
	PickIndex        int32              `json:"pick_index"`
	CurrentPick      string             `json:"current_pick"`
	LastDirection    string             `json:"last_direction"`
	StartSkipPeriod  pgtype.Text        `json:"start_skip_period"`
	StartSkipCloseAt pgtype.Timestamptz `json:"start_skip_close_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRunningSchemeInstances(ctx context.Context) ([]ListRunningSchemeInstancesRow, error) {
	rows, err := q.db.Query(ctx, listRunningSchemeInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningSchemeInstancesRow{}
	for rows.Next() {
		var i ListRunningSchemeInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.RoundIndex,
			&i.LastSettledIssue,
			&i.PickIndex,
			&i.CurrentPick,
			&i.LastDirection,
			&i.StartSkipPeriod,
			&i.StartSkipCloseAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemeInstancesByMember = `-- name: ListSchemeInstancesByMember :many

SELECT

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, bet_failed_detail, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    start_skip_period, start_skip_close_at,

    running_since, created_at, updated_at

FROM scheme_instances

WHERE member_id = $1

ORDER BY updated_at DESC
`

type ListSchemeInstancesByMemberRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	StatusReason     string             `json:"status_reason"`
	BetFailedDetail  pgtype.Text        `json:"bet_failed_detail"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	StartSkipPeriod  pgtype.Text        `json:"start_skip_period"`
	StartSkipCloseAt pgtype.Timestamptz `json:"start_skip_close_at"`
	RunningSince     pgtype.Timestamptz `json:"running_since"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSchemeInstancesByMember(ctx context.Context, memberID int64) ([]ListSchemeInstancesByMemberRow, error) {
	rows, err := q.db.Query(ctx, listSchemeInstancesByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchemeInstancesByMemberRow{}
	for rows.Next() {
		var i ListSchemeInstancesByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.BetFailedDetail,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.StartSkipPeriod,
			&i.StartSkipCloseAt,
			&i.RunningSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemeInstancesByMemberIDs = `-- name: ListSchemeInstancesByMemberIDs :many

SELECT

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, bet_failed_detail, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at

FROM scheme_instances

WHERE member_id = $1

  AND id = ANY($2::text[])
`

type ListSchemeInstancesByMemberIDsParams struct {
	MemberID int64    `json:"member_id"`
	Column2  []string `json:"column_2"`
}

type ListSchemeInstancesByMemberIDsRow struct {
	ID              string             `json:"id"`
	DefinitionID    string             `json:"definition_id"`
	MemberID        int64              `json:"member_id"`
	Kind            string             `json:"kind"`
	SchemeName      string             `json:"scheme_name"`
	LotteryCode     string             `json:"lottery_code"`
	LotteryLabel    string             `json:"lottery_label"`
	Status          string             `json:"status"`
	StatusReason    string             `json:"status_reason"`
	BetFailedDetail pgtype.Text        `json:"bet_failed_detail"`
	Turnover        pgtype.Numeric     `json:"turnover"`
	Pnl             pgtype.Numeric     `json:"pnl"`
	RunTimeSec      int32              `json:"run_time_sec"`
	LookbackPnl     pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl      pgtype.Numeric     `json:"session_pnl"`
	Multiplier      pgtype.Numeric     `json:"multiplier"`
	CountdownSec    int32              `json:"countdown_sec"`
	SimBet          bool               `json:"sim_bet"`
	RunningSince    pgtype.Timestamptz `json:"running_since"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSchemeInstancesByMemberIDs(ctx context.Context, arg ListSchemeInstancesByMemberIDsParams) ([]ListSchemeInstancesByMemberIDsRow, error) {
	rows, err := q.db.Query(ctx, listSchemeInstancesByMemberIDs, arg.MemberID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchemeInstancesByMemberIDsRow{}
	for rows.Next() {
		var i ListSchemeInstancesByMemberIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.BetFailedDetail,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.RunningSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemeInstancesByMemberPaginated = `-- name: ListSchemeInstancesByMemberPaginated :many

SELECT

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, bet_failed_detail, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at

FROM scheme_instances

WHERE member_id = $1

  AND ($2::text IS NULL OR $2::text = '' OR ($2::text = 'real' AND sim_bet = false) OR ($2::text = 'sim' AND sim_bet = true))

  AND (

    $3::timestamptz IS NULL

    OR updated_at < $3

    OR (updated_at = $3 AND id < $4::text)

  )

ORDER BY updated_at DESC, id DESC

LIMIT $5
`

type ListSchemeInstancesByMemberPaginatedParams struct {
	MemberID int64              `json:"member_id"`
	Column2  string             `json:"column_2"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Column4  string             `json:"column_4"`
	Limit    int32              `json:"limit"`
}

type ListSchemeInstancesByMemberPaginatedRow struct {
	ID              string             `json:"id"`
	DefinitionID    string             `json:"definition_id"`
	MemberID        int64              `json:"member_id"`
	Kind            string             `json:"kind"`
	SchemeName      string             `json:"scheme_name"`
	LotteryCode     string             `json:"lottery_code"`
	LotteryLabel    string             `json:"lottery_label"`
	Status          string             `json:"status"`
	StatusReason    string             `json:"status_reason"`
	BetFailedDetail pgtype.Text        `json:"bet_failed_detail"`
	Turnover        pgtype.Numeric     `json:"turnover"`
	Pnl             pgtype.Numeric     `json:"pnl"`
	RunTimeSec      int32              `json:"run_time_sec"`
	LookbackPnl     pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl      pgtype.Numeric     `json:"session_pnl"`
	Multiplier      pgtype.Numeric     `json:"multiplier"`
	CountdownSec    int32              `json:"countdown_sec"`
	SimBet          bool               `json:"sim_bet"`
	RunningSince    pgtype.Timestamptz `json:"running_since"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSchemeInstancesByMemberPaginated(ctx context.Context, arg ListSchemeInstancesByMemberPaginatedParams) ([]ListSchemeInstancesByMemberPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSchemeInstancesByMemberPaginated,
		arg.MemberID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchemeInstancesByMemberPaginatedRow{}
	for rows.Next() {
		var i ListSchemeInstancesByMemberPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.BetFailedDetail,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.RunningSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSchemeInstanceForBet = `-- name: LockSchemeInstanceForBet :one
SELECT id FROM scheme_instances WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSchemeInstanceForBet(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockSchemeInstanceForBet, id)
	err := row.Scan(&id)
	return id, err
}

const pauseAllRunningInstancesByMember = `-- name: PauseAllRunningInstancesByMember :many
UPDATE scheme_instances
SET status = 'pending',
    status_reason = $2,
    bet_failed_detail = NULL,
    run_time_sec = run_time_sec + CASE
        WHEN running_since IS NOT NULL THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - running_since))::int)
        ELSE 0
    END,
    running_since = NULL,
    updated_at = now()
WHERE member_id = $1
  AND status = 'running'
RETURNING
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, bet_failed_detail, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    round_index, last_settled_issue, pick_index, current_pick, last_direction,
    running_since, created_at, updated_at
`

type PauseAllRunningInstancesByMemberParams struct {
	MemberID     int64  `json:"member_id"`
	StatusReason string `json:"status_reason"`
}

type PauseAllRunningInstancesByMemberRow struct {
	ID               string             `json:"id"`
	DefinitionID     string             `json:"definition_id"`
	MemberID         int64              `json:"member_id"`
	Kind             string             `json:"kind"`
	SchemeName       string             `json:"scheme_name"`
	LotteryCode      string             `json:"lottery_code"`
	LotteryLabel     string             `json:"lottery_label"`
	Status           string             `json:"status"`
	StatusReason     string             `json:"status_reason"`
	BetFailedDetail  pgtype.Text        `json:"bet_failed_detail"`
	Turnover         pgtype.Numeric     `json:"turnover"`
	Pnl              pgtype.Numeric     `json:"pnl"`
	RunTimeSec       int32              `json:"run_time_sec"`
	LookbackPnl      pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl       pgtype.Numeric     `json:"session_pnl"`
	Multiplier       pgtype.Numeric     `json:"multiplier"`
	CountdownSec     int32              `json:"countdown_sec"`
	SimBet           bool               `json:"sim_bet"`
	RoundIndex       int32              `json:"round_index"`
	LastSettledIssue pgtype.Text        `json:"last_settled_issue"`
	PickIndex        int32              `json:"pick_index"`
	CurrentPick      string             `json:"current_pick"`
	LastDirection    string             `json:"last_direction"`
	RunningSince     pgtype.Timestamptz `json:"running_since"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PauseAllRunningInstancesByMember(ctx context.Context, arg PauseAllRunningInstancesByMemberParams) ([]PauseAllRunningInstancesByMemberRow, error) {
	rows, err := q.db.Query(ctx, pauseAllRunningInstancesByMember, arg.MemberID, arg.StatusReason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PauseAllRunningInstancesByMemberRow{}
	for rows.Next() {
		var i PauseAllRunningInstancesByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.BetFailedDetail,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.RoundIndex,
			&i.LastSettledIssue,
			&i.PickIndex,
			&i.CurrentPick,
			&i.LastDirection,
			&i.RunningSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseRunningPendingInstancesByMember = `-- name: PauseRunningPendingInstancesByMember :many

UPDATE scheme_instances

SET status = 'paused',

    status_reason = 'manual',

    updated_at = now()

WHERE member_id = $1

  AND status IN ('running', 'pending')

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    created_at, updated_at
`

type PauseRunningPendingInstancesByMemberRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) PauseRunningPendingInstancesByMember(ctx context.Context, memberID int64) ([]PauseRunningPendingInstancesByMemberRow, error) {
	rows, err := q.db.Query(ctx, pauseRunningPendingInstancesByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PauseRunningPendingInstancesByMemberRow{}
	for rows.Next() {
		var i PauseRunningPendingInstancesByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.MemberID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.Status,
			&i.StatusReason,
			&i.Turnover,
			&i.Pnl,
			&i.RunTimeSec,
			&i.LookbackPnl,
			&i.SessionPnl,
			&i.Multiplier,
			&i.CountdownSec,
			&i.SimBet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseSchemeInstanceByWorker = `-- name: PauseSchemeInstanceByWorker :execrows

UPDATE scheme_instances

SET status = 'pending',

    status_reason = $2,

    bet_failed_detail = CASE WHEN $2::varchar = 'bet_failed' THEN NULLIF($3::varchar, '') ELSE NULL END,

    run_time_sec = run_time_sec + CASE
        WHEN running_since IS NOT NULL THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - running_since))::int)
        ELSE 0
    END,

    running_since = NULL,

    updated_at = now()

WHERE id = $1

  AND status = 'running'
`

type PauseSchemeInstanceByWorkerParams struct {
	ID           string `json:"id"`
	StatusReason string `json:"status_reason"`
	Column3      string `json:"column_3"`
}

func (q *Queries) PauseSchemeInstanceByWorker(ctx context.Context, arg PauseSchemeInstanceByWorkerParams) (int64, error) {
	result, err := q.db.Exec(ctx, pauseSchemeInstanceByWorker, arg.ID, arg.StatusReason, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumeSchemeInstanceAfterMaintenance = `-- name: ResumeSchemeInstanceAfterMaintenance :one
UPDATE scheme_instances
SET status = 'running',
    status_reason = 'await_next_bet',
    bet_failed_detail = NULL,
    running_since = now(),
    updated_at = now()
WHERE id = $1
  AND member_id = $2
  AND status = 'pending'
  AND status_reason = 'maintenance'
RETURNING
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    running_since, created_at, updated_at
`

type ResumeSchemeInstanceAfterMaintenanceParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
}

type ResumeSchemeInstanceAfterMaintenanceRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResumeSchemeInstanceAfterMaintenance(ctx context.Context, arg ResumeSchemeInstanceAfterMaintenanceParams) (ResumeSchemeInstanceAfterMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, resumeSchemeInstanceAfterMaintenance, arg.ID, arg.MemberID)
	var i ResumeSchemeInstanceAfterMaintenanceRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skipSchemeInstanceStartPeriod = `-- name: SkipSchemeInstanceStartPeriod :execrows

UPDATE scheme_instances

SET last_settled_issue = $2,

    updated_at = now()

WHERE id = $1

  AND status = 'running'

  AND status_reason = 'await_next_bet'

  AND last_settled_issue IS NULL
`

type SkipSchemeInstanceStartPeriodParams struct {
	ID               string      `json:"id"`
	LastSettledIssue pgtype.Text `json:"last_settled_issue"`
}

func (q *Queries) SkipSchemeInstanceStartPeriod(ctx context.Context, arg SkipSchemeInstanceStartPeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, skipSchemeInstanceStartPeriod, arg.ID, arg.LastSettledIssue)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumMemberFormalSessionPnl = `-- name: SumMemberFormalSessionPnl :one
SELECT COALESCE(SUM(session_pnl), 0)::numeric AS total
FROM scheme_instances
WHERE member_id = $1
  AND sim_bet = false
`

func (q *Queries) SumMemberFormalSessionPnl(ctx context.Context, memberID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumMemberFormalSessionPnl, memberID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateSchemeInstanceMultiplier = `-- name: UpdateSchemeInstanceMultiplier :one

UPDATE scheme_instances

SET multiplier = $3,

    updated_at = now()

WHERE id = $1 AND member_id = $2

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceMultiplierParams struct {
	ID         string         `json:"id"`
	MemberID   int64          `json:"member_id"`
	Multiplier pgtype.Numeric `json:"multiplier"`
}

type UpdateSchemeInstanceMultiplierRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceMultiplier(ctx context.Context, arg UpdateSchemeInstanceMultiplierParams) (UpdateSchemeInstanceMultiplierRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceMultiplier, arg.ID, arg.MemberID, arg.Multiplier)
	var i UpdateSchemeInstanceMultiplierRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceSimBet = `-- name: UpdateSchemeInstanceSimBet :one

UPDATE scheme_instances

SET sim_bet = $3,

    updated_at = now()

WHERE id = $1 AND member_id = $2

  AND status <> 'running'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceSimBetParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
	SimBet   bool   `json:"sim_bet"`
}

type UpdateSchemeInstanceSimBetRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceSimBet(ctx context.Context, arg UpdateSchemeInstanceSimBetParams) (UpdateSchemeInstanceSimBetRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceSimBet, arg.ID, arg.MemberID, arg.SimBet)
	var i UpdateSchemeInstanceSimBetRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceStatus = `-- name: UpdateSchemeInstanceStatus :one

UPDATE scheme_instances

SET status = $3,

    status_reason = CASE
        WHEN $3 = 'paused' THEN COALESCE(NULLIF($4, ''), 'manual')
        WHEN $3 = 'running' THEN COALESCE(NULLIF($4, ''), '')
        ELSE ''
    END,

    updated_at = now()

WHERE id = $1 AND member_id = $2

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceStatusParams struct {
	ID       string      `json:"id"`
	MemberID int64       `json:"member_id"`
	Status   string      `json:"status"`
	Column4  interface{} `json:"column_4"`
}

type UpdateSchemeInstanceStatusRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatus(ctx context.Context, arg UpdateSchemeInstanceStatusParams) (UpdateSchemeInstanceStatusRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatus,
		arg.ID,
		arg.MemberID,
		arg.Status,
		arg.Column4,
	)
	var i UpdateSchemeInstanceStatusRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceStatusFromPausedToRunning = `-- name: UpdateSchemeInstanceStatusFromPausedToRunning :one

UPDATE scheme_instances

SET status = 'running',

    status_reason = COALESCE(NULLIF($3, ''), ''),

    running_since = now(),

    updated_at = now()

WHERE id = $1 AND member_id = $2 AND status = 'paused'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceStatusFromPausedToRunningParams struct {
	ID       string      `json:"id"`
	MemberID int64       `json:"member_id"`
	Column3  interface{} `json:"column_3"`
}

type UpdateSchemeInstanceStatusFromPausedToRunningRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatusFromPausedToRunning(ctx context.Context, arg UpdateSchemeInstanceStatusFromPausedToRunningParams) (UpdateSchemeInstanceStatusFromPausedToRunningRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatusFromPausedToRunning, arg.ID, arg.MemberID, arg.Column3)
	var i UpdateSchemeInstanceStatusFromPausedToRunningRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceStatusFromPendingToRunning = `-- name: UpdateSchemeInstanceStatusFromPendingToRunning :one

UPDATE scheme_instances

SET status = 'running',

    status_reason = COALESCE(NULLIF($3, ''), 'await_next_bet'),

    session_pnl = 0,

    turnover = 0,

    pnl = 0,

    lookback_pnl = 0,

    run_time_sec = 0,

    round_index = 0,

    last_settled_issue = NULL,

    start_skip_period = NULL,

    start_skip_close_at = NULL,

    pick_index = 0,

    current_pick = '',

    last_direction = '',

    bet_failed_detail = NULL,

    running_since = now(),

    updated_at = now()

WHERE id = $1 AND member_id = $2 AND status IN ('pending', 'paused')

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceStatusFromPendingToRunningParams struct {
	ID       string      `json:"id"`
	MemberID int64       `json:"member_id"`
	Column3  interface{} `json:"column_3"`
}

type UpdateSchemeInstanceStatusFromPendingToRunningRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatusFromPendingToRunning(ctx context.Context, arg UpdateSchemeInstanceStatusFromPendingToRunningParams) (UpdateSchemeInstanceStatusFromPendingToRunningRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatusFromPendingToRunning, arg.ID, arg.MemberID, arg.Column3)
	var i UpdateSchemeInstanceStatusFromPendingToRunningRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceStatusFromRunningToPending = `-- name: UpdateSchemeInstanceStatusFromRunningToPending :one

UPDATE scheme_instances

SET status = 'pending',

    status_reason = '',

    last_settled_issue = NULL,

    start_skip_period = NULL,

    start_skip_close_at = NULL,

    run_time_sec = run_time_sec + CASE
        WHEN running_since IS NOT NULL THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - running_since))::int)
        ELSE 0
    END,

    running_since = NULL,

    updated_at = now()

WHERE id = $1 AND member_id = $2 AND status = 'running'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceStatusFromRunningToPendingParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
}

type UpdateSchemeInstanceStatusFromRunningToPendingRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatusFromRunningToPending(ctx context.Context, arg UpdateSchemeInstanceStatusFromRunningToPendingParams) (UpdateSchemeInstanceStatusFromRunningToPendingRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatusFromRunningToPending, arg.ID, arg.MemberID)
	var i UpdateSchemeInstanceStatusFromRunningToPendingRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeInstanceStatusToPaused = `-- name: UpdateSchemeInstanceStatusToPaused :one

UPDATE scheme_instances

SET status = 'paused',

    status_reason = COALESCE(NULLIF($3, ''), 'manual'),

    last_settled_issue = NULL,

    start_skip_period = NULL,

    start_skip_close_at = NULL,

    run_time_sec = run_time_sec + CASE
        WHEN running_since IS NOT NULL THEN GREATEST(0, EXTRACT(EPOCH FROM (now() - running_since))::int)
        ELSE 0
    END,

    running_since = NULL,

    updated_at = now()

WHERE id = $1 AND member_id = $2 AND status = 'running'

RETURNING

    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,

    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,

    running_since, created_at, updated_at
`

type UpdateSchemeInstanceStatusToPausedParams struct {
	ID       string      `json:"id"`
	MemberID int64       `json:"member_id"`
	Column3  interface{} `json:"column_3"`
}

type UpdateSchemeInstanceStatusToPausedRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	RunningSince pgtype.Timestamptz `json:"running_since"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeInstanceStatusToPaused(ctx context.Context, arg UpdateSchemeInstanceStatusToPausedParams) (UpdateSchemeInstanceStatusToPausedRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeInstanceStatusToPaused, arg.ID, arg.MemberID, arg.Column3)
	var i UpdateSchemeInstanceStatusToPausedRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.RunningSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
