// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheme_share_snapshots.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSchemeShareSnapshot = `-- name: InsertSchemeShareSnapshot :one
INSERT INTO scheme_share_snapshots (
    id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config
) VALUES (
    $1, 'custom', $2, $3, $4, $5, $6, $7
)
RETURNING id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config, created_at, updated_at
`

type InsertSchemeShareSnapshotParams struct {
	ID           string         `json:"id"`
	SchemeName   string         `json:"scheme_name"`
	LotteryCode  string         `json:"lottery_code"`
	LotteryLabel string         `json:"lottery_label"`
	PlayMethod   string         `json:"play_method"`
	FundYuan     pgtype.Numeric `json:"fund_yuan"`
	Config       []byte         `json:"config"`
}

func (q *Queries) InsertSchemeShareSnapshot(ctx context.Context, arg InsertSchemeShareSnapshotParams) (SchemeShareSnapshot, error) {
	row := q.db.QueryRow(ctx, insertSchemeShareSnapshot,
		arg.ID,
		arg.SchemeName,
		arg.LotteryCode,
		arg.LotteryLabel,
		arg.PlayMethod,
		arg.FundYuan,
		arg.Config,
	)
	var i SchemeShareSnapshot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.PlayMethod,
		&i.FundYuan,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchemeShareSnapshots = `-- name: ListSchemeShareSnapshots :many
SELECT id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config, created_at, updated_at
FROM scheme_share_snapshots
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR id ILIKE '%' || $1::text || '%'
    OR scheme_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR $2::text = ''
    OR id > $2::text
)
ORDER BY id ASC
LIMIT $3
`

type ListSchemeShareSnapshotsParams struct {
	Keyword  pgtype.Text `json:"keyword"`
	Cursor   pgtype.Text `json:"cursor"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListSchemeShareSnapshots(ctx context.Context, arg ListSchemeShareSnapshotsParams) ([]SchemeShareSnapshot, error) {
	rows, err := q.db.Query(ctx, listSchemeShareSnapshots, arg.Keyword, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemeShareSnapshot{}
	for rows.Next() {
		var i SchemeShareSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.PlayMethod,
			&i.FundYuan,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
