// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheme_options.sql

package sqlcdb

import (
	"context"
)

const getLotterySchemeOptionSet = `-- name: GetLotterySchemeOptionSet :one
SELECT lottery_code, run_types, play_types, sub_plays
FROM lottery_scheme_option_sets
WHERE lottery_code = $1
`

type GetLotterySchemeOptionSetRow struct {
	LotteryCode string `json:"lottery_code"`
	RunTypes    []byte `json:"run_types"`
	PlayTypes   []byte `json:"play_types"`
	SubPlays    []byte `json:"sub_plays"`
}

func (q *Queries) GetLotterySchemeOptionSet(ctx context.Context, lotteryCode string) (GetLotterySchemeOptionSetRow, error) {
	row := q.db.QueryRow(ctx, getLotterySchemeOptionSet, lotteryCode)
	var i GetLotterySchemeOptionSetRow
	err := row.Scan(
		&i.LotteryCode,
		&i.RunTypes,
		&i.PlayTypes,
		&i.SubPlays,
	)
	return i, err
}
