// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheme_definitions.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSchemeDefinitionByIDAndMember = `-- name: DeleteSchemeDefinitionByIDAndMember :execrows
DELETE FROM scheme_definitions
WHERE id = $1 AND member_id = $2
`

type DeleteSchemeDefinitionByIDAndMemberParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
}

func (q *Queries) DeleteSchemeDefinitionByIDAndMember(ctx context.Context, arg DeleteSchemeDefinitionByIDAndMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchemeDefinitionByIDAndMember, arg.ID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchemeDefinitionByID = `-- name: GetSchemeDefinitionByID :one
SELECT
    id, kind, scheme_name, lottery_code, lottery_label, share_status, share_status_locked,
    source_snapshot_id, config, created_at, updated_at
FROM scheme_definitions
WHERE id = $1
`

type GetSchemeDefinitionByIDRow struct {
	ID                string             `json:"id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchemeDefinitionByID(ctx context.Context, id string) (GetSchemeDefinitionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSchemeDefinitionByID, id)
	var i GetSchemeDefinitionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.ShareStatus,
		&i.ShareStatusLocked,
		&i.SourceSnapshotID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemeDefinitionByIDAndMember = `-- name: GetSchemeDefinitionByIDAndMember :one
SELECT
    id, kind, scheme_name, lottery_code, lottery_label, share_status, share_status_locked,
    source_snapshot_id, config, created_at, updated_at
FROM scheme_definitions
WHERE id = $1 AND member_id = $2
`

type GetSchemeDefinitionByIDAndMemberParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
}

type GetSchemeDefinitionByIDAndMemberRow struct {
	ID                string             `json:"id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchemeDefinitionByIDAndMember(ctx context.Context, arg GetSchemeDefinitionByIDAndMemberParams) (GetSchemeDefinitionByIDAndMemberRow, error) {
	row := q.db.QueryRow(ctx, getSchemeDefinitionByIDAndMember, arg.ID, arg.MemberID)
	var i GetSchemeDefinitionByIDAndMemberRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.ShareStatus,
		&i.ShareStatusLocked,
		&i.SourceSnapshotID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemeInstanceByDefinitionID = `-- name: GetSchemeInstanceByDefinitionID :one
SELECT
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    created_at, updated_at
FROM scheme_instances
WHERE definition_id = $1
`

type GetSchemeInstanceByDefinitionIDRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSchemeInstanceByDefinitionID(ctx context.Context, definitionID string) (GetSchemeInstanceByDefinitionIDRow, error) {
	row := q.db.QueryRow(ctx, getSchemeInstanceByDefinitionID, definitionID)
	var i GetSchemeInstanceByDefinitionIDRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemeShareSnapshotByID = `-- name: GetSchemeShareSnapshotByID :one
SELECT id, kind, scheme_name, lottery_code, lottery_label, play_method, fund_yuan, config, created_at, updated_at
FROM scheme_share_snapshots
WHERE id = $1
`

func (q *Queries) GetSchemeShareSnapshotByID(ctx context.Context, id string) (SchemeShareSnapshot, error) {
	row := q.db.QueryRow(ctx, getSchemeShareSnapshotByID, id)
	var i SchemeShareSnapshot
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.PlayMethod,
		&i.FundYuan,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasRunningSchemeInstanceByDefinition = `-- name: HasRunningSchemeInstanceByDefinition :one
SELECT EXISTS(
    SELECT 1 FROM scheme_instances
    WHERE definition_id = $1 AND status = 'running'
)::bool AS exists
`

func (q *Queries) HasRunningSchemeInstanceByDefinition(ctx context.Context, definitionID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunningSchemeInstanceByDefinition, definitionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertSchemeDefinition = `-- name: InsertSchemeDefinition :one
INSERT INTO scheme_definitions (
    id, member_id, kind, scheme_name, lottery_code, lottery_label,
    share_status, share_status_locked, source_snapshot_id, config
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, member_id, kind, scheme_name, lottery_code, lottery_label,
    share_status, share_status_locked, source_snapshot_id, config, created_at, updated_at
`

type InsertSchemeDefinitionParams struct {
	ID                string      `json:"id"`
	MemberID          int64       `json:"member_id"`
	Kind              string      `json:"kind"`
	SchemeName        string      `json:"scheme_name"`
	LotteryCode       string      `json:"lottery_code"`
	LotteryLabel      string      `json:"lottery_label"`
	ShareStatus       string      `json:"share_status"`
	ShareStatusLocked bool        `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text `json:"source_snapshot_id"`
	Config            []byte      `json:"config"`
}

type InsertSchemeDefinitionRow struct {
	ID                string             `json:"id"`
	MemberID          int64              `json:"member_id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertSchemeDefinition(ctx context.Context, arg InsertSchemeDefinitionParams) (InsertSchemeDefinitionRow, error) {
	row := q.db.QueryRow(ctx, insertSchemeDefinition,
		arg.ID,
		arg.MemberID,
		arg.Kind,
		arg.SchemeName,
		arg.LotteryCode,
		arg.LotteryLabel,
		arg.ShareStatus,
		arg.ShareStatusLocked,
		arg.SourceSnapshotID,
		arg.Config,
	)
	var i InsertSchemeDefinitionRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.ShareStatus,
		&i.ShareStatusLocked,
		&i.SourceSnapshotID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSchemeInstance = `-- name: InsertSchemeInstance :one
INSERT INTO scheme_instances (
    id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, sim_bet
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, definition_id, member_id, kind, scheme_name, lottery_code, lottery_label,
    status, status_reason, turnover, pnl, run_time_sec, lookback_pnl, session_pnl, multiplier, countdown_sec, sim_bet,
    created_at, updated_at
`

type InsertSchemeInstanceParams struct {
	ID           string `json:"id"`
	DefinitionID string `json:"definition_id"`
	MemberID     int64  `json:"member_id"`
	Kind         string `json:"kind"`
	SchemeName   string `json:"scheme_name"`
	LotteryCode  string `json:"lottery_code"`
	LotteryLabel string `json:"lottery_label"`
	Status       string `json:"status"`
	SimBet       bool   `json:"sim_bet"`
}

type InsertSchemeInstanceRow struct {
	ID           string             `json:"id"`
	DefinitionID string             `json:"definition_id"`
	MemberID     int64              `json:"member_id"`
	Kind         string             `json:"kind"`
	SchemeName   string             `json:"scheme_name"`
	LotteryCode  string             `json:"lottery_code"`
	LotteryLabel string             `json:"lottery_label"`
	Status       string             `json:"status"`
	StatusReason string             `json:"status_reason"`
	Turnover     pgtype.Numeric     `json:"turnover"`
	Pnl          pgtype.Numeric     `json:"pnl"`
	RunTimeSec   int32              `json:"run_time_sec"`
	LookbackPnl  pgtype.Numeric     `json:"lookback_pnl"`
	SessionPnl   pgtype.Numeric     `json:"session_pnl"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	CountdownSec int32              `json:"countdown_sec"`
	SimBet       bool               `json:"sim_bet"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertSchemeInstance(ctx context.Context, arg InsertSchemeInstanceParams) (InsertSchemeInstanceRow, error) {
	row := q.db.QueryRow(ctx, insertSchemeInstance,
		arg.ID,
		arg.DefinitionID,
		arg.MemberID,
		arg.Kind,
		arg.SchemeName,
		arg.LotteryCode,
		arg.LotteryLabel,
		arg.Status,
		arg.SimBet,
	)
	var i InsertSchemeInstanceRow
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.Status,
		&i.StatusReason,
		&i.Turnover,
		&i.Pnl,
		&i.RunTimeSec,
		&i.LookbackPnl,
		&i.SessionPnl,
		&i.Multiplier,
		&i.CountdownSec,
		&i.SimBet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchemeDefinitionNamesByMember = `-- name: ListSchemeDefinitionNamesByMember :many
SELECT scheme_name
FROM scheme_definitions
WHERE member_id = $1
`

func (q *Queries) ListSchemeDefinitionNamesByMember(ctx context.Context, memberID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listSchemeDefinitionNamesByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scheme_name string
		if err := rows.Scan(&scheme_name); err != nil {
			return nil, err
		}
		items = append(items, scheme_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemeDefinitionsByMember = `-- name: ListSchemeDefinitionsByMember :many
SELECT
    d.id,
    d.kind,
    d.scheme_name,
    d.lottery_code,
    d.lottery_label,
    d.share_status,
    d.share_status_locked,
    d.source_snapshot_id,
    d.config,
    d.created_at,
    d.updated_at,
    EXISTS (
        SELECT 1 FROM scheme_instances i WHERE i.definition_id = d.id
    ) AS has_instance
FROM scheme_definitions d
WHERE d.member_id = $1
  AND (
    $2::text IS NULL
    OR $2::text = ''
    OR d.kind = $2::text
  )
ORDER BY d.updated_at DESC
`

type ListSchemeDefinitionsByMemberParams struct {
	MemberID int64       `json:"member_id"`
	Kind     pgtype.Text `json:"kind"`
}

type ListSchemeDefinitionsByMemberRow struct {
	ID                string             `json:"id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	HasInstance       bool               `json:"has_instance"`
}

func (q *Queries) ListSchemeDefinitionsByMember(ctx context.Context, arg ListSchemeDefinitionsByMemberParams) ([]ListSchemeDefinitionsByMemberRow, error) {
	rows, err := q.db.Query(ctx, listSchemeDefinitionsByMember, arg.MemberID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchemeDefinitionsByMemberRow{}
	for rows.Next() {
		var i ListSchemeDefinitionsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SchemeName,
			&i.LotteryCode,
			&i.LotteryLabel,
			&i.ShareStatus,
			&i.ShareStatusLocked,
			&i.SourceSnapshotID,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasInstance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schemeDefinitionNameExistsByMember = `-- name: SchemeDefinitionNameExistsByMember :one
SELECT EXISTS(
    SELECT 1 FROM scheme_definitions
    WHERE member_id = $1 AND scheme_name = $2
) AS exists
`

type SchemeDefinitionNameExistsByMemberParams struct {
	MemberID   int64  `json:"member_id"`
	SchemeName string `json:"scheme_name"`
}

func (q *Queries) SchemeDefinitionNameExistsByMember(ctx context.Context, arg SchemeDefinitionNameExistsByMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, schemeDefinitionNameExistsByMember, arg.MemberID, arg.SchemeName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSchemeDefinitionNameStatusByMember = `-- name: GetSchemeDefinitionNameStatusByMember :one
SELECT
    d.id,
    EXISTS (SELECT 1 FROM scheme_instances i WHERE i.definition_id = d.id) AS has_instance
FROM scheme_definitions d
WHERE d.member_id = $1 AND d.scheme_name = $2
`

type GetSchemeDefinitionNameStatusByMemberParams struct {
	MemberID   int64  `json:"member_id"`
	SchemeName string `json:"scheme_name"`
}

type GetSchemeDefinitionNameStatusByMemberRow struct {
	ID          string `json:"id"`
	HasInstance bool   `json:"has_instance"`
}

func (q *Queries) GetSchemeDefinitionNameStatusByMember(ctx context.Context, arg GetSchemeDefinitionNameStatusByMemberParams) (GetSchemeDefinitionNameStatusByMemberRow, error) {
	row := q.db.QueryRow(ctx, getSchemeDefinitionNameStatusByMember, arg.MemberID, arg.SchemeName)
	var i GetSchemeDefinitionNameStatusByMemberRow
	err := row.Scan(&i.ID, &i.HasInstance)
	return i, err
}

const syncSchemeInstancesSimBetByDefinition = `-- name: SyncSchemeInstancesSimBetByDefinition :execrows
UPDATE scheme_instances
SET sim_bet = $2,
    updated_at = now()
WHERE definition_id = $1
  AND status <> 'running'
`

type SyncSchemeInstancesSimBetByDefinitionParams struct {
	DefinitionID string `json:"definition_id"`
	SimBet       bool   `json:"sim_bet"`
}

func (q *Queries) SyncSchemeInstancesSimBetByDefinition(ctx context.Context, arg SyncSchemeInstancesSimBetByDefinitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncSchemeInstancesSimBetByDefinition, arg.DefinitionID, arg.SimBet)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSchemeDefinitionConfig = `-- name: UpdateSchemeDefinitionConfig :one
UPDATE scheme_definitions
SET config = $3, updated_at = now()
WHERE id = $1 AND member_id = $2
RETURNING id, member_id, kind, scheme_name, lottery_code, lottery_label,
    share_status, share_status_locked, source_snapshot_id, config, created_at, updated_at
`

type UpdateSchemeDefinitionConfigParams struct {
	ID       string `json:"id"`
	MemberID int64  `json:"member_id"`
	Config   []byte `json:"config"`
}

type UpdateSchemeDefinitionConfigRow struct {
	ID                string             `json:"id"`
	MemberID          int64              `json:"member_id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeDefinitionConfig(ctx context.Context, arg UpdateSchemeDefinitionConfigParams) (UpdateSchemeDefinitionConfigRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeDefinitionConfig, arg.ID, arg.MemberID, arg.Config)
	var i UpdateSchemeDefinitionConfigRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.ShareStatus,
		&i.ShareStatusLocked,
		&i.SourceSnapshotID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchemeDefinitionForCloud = `-- name: UpdateSchemeDefinitionForCloud :one
UPDATE scheme_definitions
SET
    share_status = $3,
    share_status_locked = true,
    config = $4,
    updated_at = now()
WHERE id = $1 AND member_id = $2
RETURNING id, member_id, kind, scheme_name, lottery_code, lottery_label,
    share_status, share_status_locked, source_snapshot_id, config, created_at, updated_at
`

type UpdateSchemeDefinitionForCloudParams struct {
	ID          string `json:"id"`
	MemberID    int64  `json:"member_id"`
	ShareStatus string `json:"share_status"`
	Config      []byte `json:"config"`
}

type UpdateSchemeDefinitionForCloudRow struct {
	ID                string             `json:"id"`
	MemberID          int64              `json:"member_id"`
	Kind              string             `json:"kind"`
	SchemeName        string             `json:"scheme_name"`
	LotteryCode       string             `json:"lottery_code"`
	LotteryLabel      string             `json:"lottery_label"`
	ShareStatus       string             `json:"share_status"`
	ShareStatusLocked bool               `json:"share_status_locked"`
	SourceSnapshotID  pgtype.Text        `json:"source_snapshot_id"`
	Config            []byte             `json:"config"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSchemeDefinitionForCloud(ctx context.Context, arg UpdateSchemeDefinitionForCloudParams) (UpdateSchemeDefinitionForCloudRow, error) {
	row := q.db.QueryRow(ctx, updateSchemeDefinitionForCloud,
		arg.ID,
		arg.MemberID,
		arg.ShareStatus,
		arg.Config,
	)
	var i UpdateSchemeDefinitionForCloudRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Kind,
		&i.SchemeName,
		&i.LotteryCode,
		&i.LotteryLabel,
		&i.ShareStatus,
		&i.ShareStatusLocked,
		&i.SourceSnapshotID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
