// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: strategy_evaluations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSchemeStrategyEvaluation = `-- name: CompleteSchemeStrategyEvaluation :execrows
UPDATE scheme_strategy_evaluations
SET status = 'completed',
    cloud_bet_record_id = $1,
    bet_order_no = $2,
    rule_version = $3,
    rule_snapshot_hash = $4,
    local_hit = $5,
    winning_units = $6,
    diagnostics = $7,
    completed_at = now(),
    updated_at = now()
WHERE id = $8
  AND status = 'processing'
`

type CompleteSchemeStrategyEvaluationParams struct {
	CloudBetRecordID pgtype.Int8 `json:"cloud_bet_record_id"`
	BetOrderNo       pgtype.Text `json:"bet_order_no"`
	RuleVersion      pgtype.Int4 `json:"rule_version"`
	RuleSnapshotHash pgtype.Text `json:"rule_snapshot_hash"`
	LocalHit         pgtype.Bool `json:"local_hit"`
	WinningUnits     pgtype.Int4 `json:"winning_units"`
	Diagnostics      []byte      `json:"diagnostics"`
	ID               int64       `json:"id"`
}

func (q *Queries) CompleteSchemeStrategyEvaluation(ctx context.Context, arg CompleteSchemeStrategyEvaluationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeSchemeStrategyEvaluation,
		arg.CloudBetRecordID,
		arg.BetOrderNo,
		arg.RuleVersion,
		arg.RuleSnapshotHash,
		arg.LocalHit,
		arg.WinningUnits,
		arg.Diagnostics,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchemeStrategyEvaluation = `-- name: GetSchemeStrategyEvaluation :one
SELECT id,
       instance_id,
       lottery_code,
       period_no,
       cloud_bet_record_id,
       bet_order_no,
       status,
       rule_version,
       rule_snapshot_hash,
       local_hit,
       winning_units,
       diagnostics,
       claimed_at,
       completed_at,
       created_at,
       updated_at
FROM scheme_strategy_evaluations
WHERE instance_id = $1
  AND period_no = $2
`

type GetSchemeStrategyEvaluationParams struct {
	InstanceID string `json:"instance_id"`
	PeriodNo   string `json:"period_no"`
}

func (q *Queries) GetSchemeStrategyEvaluation(ctx context.Context, arg GetSchemeStrategyEvaluationParams) (SchemeStrategyEvaluation, error) {
	row := q.db.QueryRow(ctx, getSchemeStrategyEvaluation, arg.InstanceID, arg.PeriodNo)
	var i SchemeStrategyEvaluation
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.LotteryCode,
		&i.PeriodNo,
		&i.CloudBetRecordID,
		&i.BetOrderNo,
		&i.Status,
		&i.RuleVersion,
		&i.RuleSnapshotHash,
		&i.LocalHit,
		&i.WinningUnits,
		&i.Diagnostics,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecoverableSchemeStrategyEvaluations = `-- name: ListRecoverableSchemeStrategyEvaluations :many
SELECT id,
       instance_id,
       lottery_code,
       period_no,
       status,
       diagnostics,
       created_at
FROM scheme_strategy_evaluations
WHERE status IN ('pending', 'processing')
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ListRecoverableSchemeStrategyEvaluationsRow struct {
	ID          int64              `json:"id"`
	InstanceID  string             `json:"instance_id"`
	LotteryCode string             `json:"lottery_code"`
	PeriodNo    string             `json:"period_no"`
	Status      string             `json:"status"`
	Diagnostics []byte             `json:"diagnostics"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecoverableSchemeStrategyEvaluations(ctx context.Context, rowLimit int32) ([]ListRecoverableSchemeStrategyEvaluationsRow, error) {
	rows, err := q.db.Query(ctx, listRecoverableSchemeStrategyEvaluations, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecoverableSchemeStrategyEvaluationsRow{}
	for rows.Next() {
		var i ListRecoverableSchemeStrategyEvaluationsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.LotteryCode,
			&i.PeriodNo,
			&i.Status,
			&i.Diagnostics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSchemeStrategyEvaluationProcessing = `-- name: MarkSchemeStrategyEvaluationProcessing :execrows
UPDATE scheme_strategy_evaluations
SET status = 'processing', claimed_at = now(), updated_at = now()
WHERE id = $1
  AND status = 'pending'
`

func (q *Queries) MarkSchemeStrategyEvaluationProcessing(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markSchemeStrategyEvaluationProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipSchemeStrategyEvaluation = `-- name: SkipSchemeStrategyEvaluation :execrows
UPDATE scheme_strategy_evaluations
SET status = 'skipped', diagnostics = $1, completed_at = now(), updated_at = now()
WHERE id = $2
  AND status IN ('pending', 'processing')
`

type SkipSchemeStrategyEvaluationParams struct {
	Diagnostics []byte `json:"diagnostics"`
	ID          int64  `json:"id"`
}

func (q *Queries) SkipSchemeStrategyEvaluation(ctx context.Context, arg SkipSchemeStrategyEvaluationParams) (int64, error) {
	result, err := q.db.Exec(ctx, skipSchemeStrategyEvaluation, arg.Diagnostics, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryClaimSchemeStrategyEvaluation = `-- name: TryClaimSchemeStrategyEvaluation :one
WITH inserted AS (
    INSERT INTO scheme_strategy_evaluations (instance_id, lottery_code, period_no)
    VALUES ($1, $2, $3)
    ON CONFLICT (instance_id, period_no) DO NOTHING
    RETURNING 1
)
SELECT EXISTS(SELECT 1 FROM inserted)::bool AS claimed
`

type TryClaimSchemeStrategyEvaluationParams struct {
	InstanceID  string `json:"instance_id"`
	LotteryCode string `json:"lottery_code"`
	PeriodNo    string `json:"period_no"`
}

func (q *Queries) TryClaimSchemeStrategyEvaluation(ctx context.Context, arg TryClaimSchemeStrategyEvaluationParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryClaimSchemeStrategyEvaluation, arg.InstanceID, arg.LotteryCode, arg.PeriodNo)
	var claimed bool
	err := row.Scan(&claimed)
	return claimed, err
}
